### PR TITLE
byt: fix simultaneous playback and capture

### LINKED ISSUE #1677: [BUG][BYT] Failed while do playback and capture at same time on BYT MinnowBoard platform: I/O error (100%)
**Describe the bug**
Failed while do playback and capture at same time on MinnowBoard BYT-NOCODEC and BYT-rt5651 platform: I/O error (100%). Dmesg and sof-logger have not any abvious error traces.
I think it is caused by PR #1053 that I had reproduced on the 20190726.

**To Reproduce**
1.
terminal 1:
```
ubuntu@cd-byt-mb-rt5651-02:~$ aplay -Dhw:0,0 -fs16_LE -c2 -r 48000 audio-files/raw/test-c2-r48000-fs16_le-d60.raw -vv -i
Playing raw data 'audio-files/raw/test-c2-r48000-fs16_le-d60.raw' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
Hardware PCM card 0 'sof-bytcr-rt5651' device 0 subdevice 0
Its setup is:
  stream       : PLAYBACK
  access       : RW_INTERLEAVED
  format       : S16_LE
  subformat    : STD
  channels     : 2
  rate         : 48000
  exact rate   : 48000 (48000/1)
  msbits       : 16
  buffer_size  : 16368
  period_size  : 4080
  period_time  : 85000
  tstamp_mode  : NONE
  tstamp_type  : MONOTONIC
  period_step  : 1
  avail_min    : 4080
  period_event : 0
  start_threshold  : 16368
  stop_threshold   : 16368
  silence_threshold: 0
  silence_size : 0
  boundary     : 9214364837600034816
  appl_ptr     : 0
  hw_ptr       : 0
############                            +          | 79%
```
terminal 2:
```
ubuntu@cd-byt-mb-rt5651-02:~$ arecord -Dhw:0,0 -fs16_LE -c2 -r 48000 1.wav -vv -i
Recording WAVE '1.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
Hardware PCM card 0 'sof-bytcr-rt5651' device 0 subdevice 0
Its setup is:
  stream       : CAPTURE
  access       : RW_INTERLEAVED
  format       : S16_LE
  subformat    : STD
  channels     : 2
  rate         : 48000
  exact rate   : 48000 (48000/1)
  msbits       : 16
  buffer_size  : 16320
  period_size  : 4080
  period_time  : 85000
  tstamp_mode  : NONE
  tstamp_type  : MONOTONIC
  period_step  : 1
  avail_min    : 4080
  period_event : 0
  start_threshold  : 1
  stop_threshold   : 16320
  silence_threshold: 0
  silence_size : 0
  boundary     : 9187343239835811840
  appl_ptr     : 0
  hw_ptr       : 0
#+                                                 | 00%
```

2.
terminal 1:   ctrl+c stop the playback
```
Aborted by signal Interrupt...
#########                               +          | 79%
```
terminal 2:
```
arecord: pcm_read:2103: read error: Input/output error
```

**Reproduction Rate**
100%

**Expected behavior**
Playback from terminal 1 can not interrupt capture from  terminal 2.

**Environment**
Sof: f7809a2e on topic/sof-master
Kernel: f745362c on topic/sof-dev
platform: BYT  MinnowBoard NOCODEC and rt5651

**log file**
[dmesg.log](https://github.com/thesofproject/sof/files/3440579/dmesg.log)
[logger.log](https://github.com/thesofproject/sof/files/3440580/logger.log)

### PR DESCRIPTION
**Pull request by tlauda**
Fixes simultaneous playback and capture on byt/cht platforms.
It's a temporary fix and will be replaced with the proper solution
soon.

Fixes #1677.

Signed-off-by: Tomasz Lauda <tomasz.lauda@linux.intel.com>

### CODE REVIEW

File: src/drivers/dw/dma.c [hunk 1]
```diff
@@ -22,6 +22,7 @@
```
Comment (dbaluta) [inline src/drivers/dw/dma.c]: @tlauda can you explain a little bit more the problem? If this is an urgent fix then I'm ok with it as it is. But other than that we really need commit message to explain the problem in detail.

Comment (tlauda) [reply src/drivers/dw/dma.c]: @dbaluta It's an ugly solution, but this fix is urgent to make more CI tests to pass. I have already almost done with the better one, but it's huge change and needs to wait for the rest of the major changes to be merged.
