### PR TITLE
drivers: intel: M/N initial driver and fixes

### LINKED ISSUE #2084: [BUG][TGL] SSP clocks generated are not as per topology configured
**Describe the bug**
1) SSP clocks generated are not correct and not matching with the values set in topology.
2) In topology Backend setting is,
#SSP 1 (ID: 0)
DAI_CONFIG(SSP, 1, 0, SSP1-Codec,
	SSP_CONFIG(I2S, SSP_CLOCK(mclk, 19200000, codec_mclk_in),
		      SSP_CLOCK(bclk, 2304000, codec_slave),
		      SSP_CLOCK(fsync, 48000, codec_slave),
		      SSP_TDM(2, 24, 3, 3),
		      SSP_CONFIG_DATA(SSP, 1, 24)))
#SSP 0 (ID: 1)
DAI_CONFIG(SSP, 0, 1, SSP0-Codec,
        SSP_CONFIG(I2S, SSP_CLOCK(mclk, 19200000, codec_mclk_in),
                      SSP_CLOCK(bclk, 2400000, codec_slave),
                      SSP_CLOCK(fsync, 48000, codec_slave),
                      SSP_TDM(2, 25, 3, 3),
                      SSP_CONFIG_DATA(SSP, 0, 24)))
3) SSP clocks observed are:
SSP1:  BCLK=2.3MHz, LRCLK=48Khz  (this is correct)
SSP0:  BCLK=1.5Mhz, LRCLK=30KHz, MCLK=19.2Mhz (because of BCLK is wrong, playback sound is bad)

**To Reproduce**

**Reproduction Rate**
100%

**Expected behavior**
SSP clocks should be right

**Impact**
Playback sound is not good

**Environment**
TGL.
Firmware is: latest from master. Fw built with: 6984e86b1561c8bdad26463753fe87f5181aae6c

### PR DESCRIPTION
**Pull request by jajanusz**
Initial MN driver version that should fix 2 major problems:
1) BCLK & MCLK logic was written like there were only 1 SSP port in existence, topologies with more SSPs in use could result in incorrect settings (config 2nd overriding source clock for config 1st etc).
2) ECS bit support was dropped in cAVS 2.0 and M/N is only supported source for BCLKs.
   
Fixes #2084

### CODE REVIEW

File: src/drivers/intel/cavs/mn.c [hunk 1]
```diff
@@ -142,73 +171,190 @@ static bool find_mn(uint32_t freq, uint32_t bclk,
...
+{
+	uint32_t m = 1;
+	uint32_t n = 1;
+	int ret = 0;
+	bool mn_in_use;
+
+	spin_lock(mn_lock);
 
-		mdivc |= MNDSS(ssp_freq_sources[clk_index]);
+	mn_in_use = is_bclk_source_in_use(MN_BCLK_SOURCE_MN);
```
Comment (ranj063) [inline src/drivers/intel/cavs/mn.c]: @jajanusz do we need this function? Can we init bclk_source_mn_clock to -1 in mn_init() and check if it is not negative?

File: src/drivers/intel/cavs/mn.c [hunk 2]
```diff
@@ -142,73 +171,190 @@ static bool find_mn(uint32_t freq, uint32_t bclk,
...
+		if (ssp_freq_sources[i] == SSP_CLOCK_XTAL_OSCILLATOR) {
+			/* XTAL turned out to be lowest source that can work
+			 * just with SCR, so use it
+			 */
+			*scr_div = ssp_freq[i].freq / bclk;
+			return true;
 		}
 
-		trace_mn("M = %d, N = %d", i2s_m, i2s_n);
+		/* check if can be handled in M/N setup */
```
Comment (ranj063) [inline src/drivers/intel/cavs/mn.c]: @jajanusz can you please explain what is checked for here? check if "what" can be handled in M/N setup?

File: src/drivers/intel/cavs/mn.c [hunk 3]
```diff
@@ -142,73 +171,190 @@ static bool find_mn(uint32_t freq, uint32_t bclk,
...
+	for (i = 0; i <= MAX_SSP_FREQ_INDEX; i++)
+		if (find_mn(ssp_freq[i].freq, bclk,
+			    scr_div, m, n))
+			return i;
 
-	/* searching the smallest possible bclk source */
-	for (i = MAX_SSP_FREQ_INDEX; i >= 0; i--) {
-		if (bclk_rate > ssp_freq[i].freq)
-			break;
+	return -1;
```
Comment (ranj063) [inline src/drivers/intel/cavs/mn.c]: -EINVAL?

File: src/drivers/intel/cavs/mn.c [hunk 4]
```diff
@@ -142,73 +171,190 @@ static bool find_mn(uint32_t freq, uint32_t bclk,
...
-		for (i = 0; i <= MAX_SSP_FREQ_INDEX; i++) {
-			if (find_mn(ssp_freq[i].freq, bclk_rate,
-				    out_scr_div, &i2s_m, &i2s_n)) {
-				clk_index = i;
-				break;
-			}
-		}
+	bclk_source_mn_clock = clk_index;
+
+	mn_reg_write(0x0, (mn_reg_read(0x0) |
```
Comment (ranj063) [inline src/drivers/intel/cavs/mn.c]: @jajanusz can you please add a comment here as to what reg we're writing to here?

File: src/drivers/intel/cavs/mn.c [hunk 5]
```diff
@@ -142,73 +171,190 @@ static bool find_mn(uint32_t freq, uint32_t bclk,
...
+/**
+ * \brief Finds valid M/(N * SCR) values for source clock that is already locked
+ *	  because other ports use it.
+ * \param[in] bclk Bit clock frequency.
+ * \param[out] scr_div SCR divisor.
+ * \param[out] m M value of M/N divider.
+ * \param[out] n N value of M/N divider.
+ * \return 0 on success, error code otherwise.
+ */
+static inline int setup_current_bclk_mn_source(uint32_t bclk, uint32_t *scr_div,
```
Comment (ranj063) [inline src/drivers/intel/cavs/mn.c]: @jajanusz I feel like we can condense setup_current_bclk_mn_source() and setup_initial_bclk_mn_source() into 1 function based on either mn_in_use as argument or just using bclk_source_mn_clock

File: src/drivers/intel/cavs/mn.c [hunk 6]
```diff
@@ -55,7 +55,7 @@ int mn_set_mclk(uint16_t mclk_id, uint32_t mclk_rate)
 	int clk_index = -1;
 	int ret = 0;
 
-	if (mclk_id > 1) {
+	if (mclk_id >= DAI_NUM_SSP_MCLK) {
```
Comment (ranj063) [inline src/drivers/intel/cavs/mn.c]: @jajanusz this change doesnt seem quite intuitive. You're changing from a value of 1 to a platform-specific value of 2 for all platforms?

File: src/drivers/intel/cavs/mn.c [hunk 7]
```diff
@@ -61,28 +85,49 @@ int mn_set_mclk(uint16_t mclk_id, uint32_t mclk_rate)
...
-		if (ssp_freq[i].freq % mclk_rate == 0)
-			clk_index = i;
-	}
+		if (ssp_freq[clk_index].freq % mclk_rate != 0) {
+			trace_mn_error("error: MCLK %d, no valid configuration for already selected source = %d",
+				       mclk_rate, mclk_source_clock);
+			ret = -EINVAL;
+			goto out;
+		}
+	} else {
```
Comment (ranj063) [inline src/drivers/intel/cavs/mn.c]: we can remove the else and reduce the indentation here because of the goto above

Comment (ranj063) [reply src/drivers/intel/cavs/mn.c]: oh no wait, sorry I misread it. ignore this comment

File: src/drivers/intel/cavs/mn.c [hunk 8]
```diff
@@ -19,6 +19,11 @@
 #define tracev_mn(__e, ...) \
 	tracev_event(TRACE_CLASS_MN, __e, ##__VA_ARGS__)
 
+enum mclk_source {
+	MN_MCLK_SOURCE_NONE = 0,
+	MN_MCLK_SOURCE_MN,
```
Comment (ranj063) [inline src/drivers/intel/cavs/mn.c]: I'm trying to understand this but what does MN_MCLK_SOURCE_MN really stand for?

File: src/drivers/intel/cavs/mn.c [hunk 9]
```diff
@@ -61,28 +85,49 @@ int mn_set_mclk(uint16_t mclk_id, uint32_t mclk_rate)
...
-	for (i = MAX_SSP_FREQ_INDEX; i >= 0; i--) {
-		if (mclk_rate > ssp_freq[i].freq)
-			break;
+	if (is_mclk_source_in_use()) {
+		clk_index = mclk_source_clock;
 
-		if (ssp_freq[i].freq % mclk_rate == 0)
-			clk_index = i;
-	}
+		if (ssp_freq[clk_index].freq % mclk_rate != 0) {
```
Comment (ranj063) [inline src/drivers/intel/cavs/mn.c]: @jajanusz for my education, in the case that this is 0, are we going to overwrite the mdivr based on the mdvir_val computed for the mclk_rate for the current SSP port being configured. Is this intentional?

**Comment by ranj063** [comment]
@jajanusz Thanks for starting this. I have a few questions on the logic but one pattern that I notice is that the code that is implemented in one patch is being refactored  in the very next. It makes reviewing a bit difficult. Can we maybe think of aligning the code from the beginning to you dont have to change the code within the same PR?

**Comment by paulstelian97** [comment]
> @jajanusz Thanks for starting this. I have a few questions on the logic but one pattern that I notice is that the code that is implemented in one patch is being refactored in the very next. It makes reviewing a bit difficult. Can we maybe think of aligning the code from the beginning to you dont have to change the code within the same PR?

@ranj063 From a quick look I see that the code being refactored actually existed beforehand, in a different file. I'd argue the order in which he does the move and then refactor does make sense.

File: src/drivers/intel/cavs/mn.c (hunk 1 above)
Comment (jajanusz) [reply src/drivers/intel/cavs/mn.c]: @ranj063 You have multiple MCLKs (on our devices I think we have 2 everywhere), with negative/nonnegative check you don't know if user count is f.e. 1 or 2. Alternative to the table used here is ref counting (-/+ on get/put), but it's more error prone if you do 2 config and reconfig f.e. without releasing it in-between.

File: src/drivers/intel/cavs/mn.c (hunk 2 above)
Comment (jajanusz) [reply src/drivers/intel/cavs/mn.c]: What is checked is shown in code - if mn is already busy & if it's busy then maybe we can use it cos it's set to desired clock already, if we can, then just quit this function, because code for setting up M/N source (instead of XTAL) will handle it. Comment just says why, what is done I guess is visible in `if` statement. This whole function is just for special case for CAVS<2 where we can bypass XTAL instead of using M/N.

File: src/drivers/intel/cavs/mn.c (hunk 3 above)
Comment (jajanusz) [reply src/drivers/intel/cavs/mn.c]: `EINVAL` is for invalid argument, here's result is `not found`. Usually functions that look for index return 0-based index or -1 on `not found`. `-1` here is not error code it's result indicating that value wasn't find in table.

File: src/drivers/intel/cavs/mn.c (hunk 4 above)
Comment (jajanusz) [reply src/drivers/intel/cavs/mn.c]: Yea, all numbers like thta just should be symbols, just forgot about that in haste ;)

File: src/drivers/intel/cavs/mn.c (hunk 5 above)
Comment (jajanusz) [reply src/drivers/intel/cavs/mn.c]: But I split it intentionally to have more smaller functions instead of 1 bigger ;p
I really think we have too many too long functions what makes them harder to read/understand.

File: src/drivers/intel/cavs/mn.c (hunk 6 above)
Comment (jajanusz) [reply src/drivers/intel/cavs/mn.c]: I just don't want to have hardcoded value `1` here. We can now have it as f.e. `DAI_MCLK_MAX_ID=1` or `DAI_NUM_SSP_MCLK=2`, that is more similar to other values in dai.h, there are all NUMs, and having one MAX_ID would be inconsistent. Another problem here is that I have to define it in many places to have the same value `2`, alternatively I can create new file in intel/cavs/.../dai.h just for 1 define and include it from platform-specific DAIs, but it's even weirder to do that for 1 symbol.

However I should change also that hardcoded `1` in next line.

File: src/drivers/intel/cavs/mn.c (hunk 8 above)
Comment (jajanusz) [reply src/drivers/intel/cavs/mn.c]: That MCLK is driven by clock coming from M/N. I think it can be just bool, because we have only 1 possible source atm (M/N), it makes sense to have it like this for BCLK and I did it also for MCLK to keep logic similar, but I understand it may cause more confusion.

File: src/drivers/intel/cavs/mn.c (hunk 9 above)
Comment (jajanusz) [reply src/drivers/intel/cavs/mn.c]: MCLKs are not bound to SSP ports, they are independent. You have f.e. 6 SSP ports and 2 MCLKs. You configure which MCLK to use from topology with mclk_id in SSP configs. If you use some source for mclk_id==0 and then want to configure mclk_id==1, then you cannot switch source that is shared by both 0&1 and only option is to get requested value by configuring divider.

Going back to your question - if you configure mclk_id==0 with some rate and then do it again for mclk_id==0, then you may overwrite it, but I assumed driver knows what it's doing, do you think we should check it? I wanted to keep it backwards compatible, because doing mentioned check would require to first `free` mclk for current divider and could make some flows fail. You would have to be sure that you destroyed DAI before using it for next SSP+MCLK config (IDK how you do it in driver).

Anyway even if you want me to do that check I'd do it in another PR, this one has too many changes at this point and I want to add more.

**Comment by jajanusz** [comment]
> > @jajanusz Thanks for starting this. I have a few questions on the logic but one pattern that I notice is that the code that is implemented in one patch is being refactored in the very next. It makes reviewing a bit difficult. Can we maybe think of aligning the code from the beginning to you dont have to change the code within the same PR?
> 
> @ranj063 From a quick look I see that the code being refactored actually existed beforehand, in a different file. I'd argue the order in which he does the move and then refactor does make sense.

I did it on purpose to have smaller deltas - to not do fix and refactor in the same path, because often maintainers complain when you do 2 things in 1 commit. I can squash refactor into previous commit.

File: src/drivers/intel/cavs/mn.c [hunk 10]
```diff
@@ -0,0 +1,191 @@
...
+
+/* tracing */
+#define trace_mn(__e, ...) \
+	trace_event(TRACE_CLASS_MN, __e, ##__VA_ARGS__)
+#define trace_mn_error(__e, ...) \
+	trace_error(TRACE_CLASS_MN, __e, ##__VA_ARGS__)
+#define tracev_mn(__e, ...) \
+	tracev_event(TRACE_CLASS_MN, __e, ##__VA_ARGS__)
+
+int mn_set_mclk(uint16_t mclk_id, uint32_t mclk_rate)
```
Comment (plbossart) [inline src/drivers/intel/cavs/mn.c]: this is a bit misleading. Here you don't actually support all cases of M/N, you assume an integer relationship with the ssp-freq.

If this was a true M/N support for the MCLK, then we'd need to allow for M different from 1, similar to the bclock?

File: src/drivers/intel/cavs/mn.c [hunk 11]
```diff
@@ -8,6 +8,7 @@
 #include <sof/drivers/ssp.h>
 #include <sof/lib/shim.h>
 #include <sof/math/numbers.h>
+#include <sof/spinlock.h>
```
Comment (plbossart) [inline src/drivers/intel/cavs/mn.c]: typo in commit message: multiple

File: src/drivers/intel/cavs/mn.c (hunk 6 above)
Comment (plbossart) [inline src/drivers/intel/cavs/mn.c]: off-by-one?

the mclk ID is 0 or 1, here you test >= 2

File: src/drivers/intel/cavs/mn.c [hunk 12]
```diff
@@ -318,6 +369,8 @@ int mn_set_bclk(uint32_t dai_index, uint32_t bclk_rate,
 
 	spin_lock(mn_lock);
 
+	bclk_sources[dai_index] = MN_BCLK_SOURCE_NONE;
+
```
Comment (plbossart) [inline src/drivers/intel/cavs/mn.c]: why is this here? Should be in different patch related to blck?

File: src/drivers/intel/cavs/mn.c (hunk 10 above)
Comment (jajanusz) [reply src/drivers/intel/cavs/mn.c]: But we don't have M in M/N for MCLK, we just have mdiv, for me it's also weird but it's how hardware is implemented. The same goes for that XTAL bypassing, also it ignores M/N but is managed by M/N part of hardware and is in the same registers...

File: src/drivers/intel/cavs/mn.c (hunk 6 above)
Comment (jajanusz) [reply src/drivers/intel/cavs/mn.c]: Because it's test for *invalid* id, 0 1 are valid with 2 you'll get error etc

File: src/drivers/intel/cavs/mn.c (hunk 12 above)
Comment (jajanusz) [reply src/drivers/intel/cavs/mn.c]: You are right, thanks for catching this

**Comment by jajanusz** [comment]
> The idea of moving the BCLK and MCLK to a separate driver makes sense. I am not hot on the 'mn' naming, we have M/N support on Baytrail but it's a completely different implementation.
> 
This patch is just for cAVS, SSP stuff diverged some time ago for nonCAVS and CAVS. Baytrail stays as it is.

> Also I wonder if we should have different calls for
> 
> * set_rate
> * prepare-enable
>   as Linux does it.
> 
> It'd be very handy to allow the MCLK/BCLK to be turned on at different times.

Yes it can be handy, but it would require real ABI changes, because driver would have to call 2 things. In current form patch fixes problems that are imporant for us and requires no co-op on driver side.
I can add requested features in another PR.

File: src/drivers/intel/cavs/mn.c (hunk 10 above)
Comment (plbossart) [reply src/drivers/intel/cavs/mn.c]: ah, yes, but in that case it'd be useful to state it, I thought it was a miss when it was a feature

File: src/drivers/intel/cavs/mn.c (hunk 6 above)
Comment (plbossart) [reply src/drivers/intel/cavs/mn.c]: need more coffee

**Comment by plbossart** [comment]
> > The idea of moving the BCLK and MCLK to a separate driver makes sense. I am not hot on the 'mn' naming, we have M/N support on Baytrail but it's a completely different implementation.
> 
> This patch is just for cAVS, SSP stuff diverged some time ago for nonCAVS and CAVS. Baytrail stays as it is.
> 
> > Also I wonder if we should have different calls for
> > 
> > * set_rate
> > * prepare-enable
> >   as Linux does it.
> > 
> > It'd be very handy to allow the MCLK/BCLK to be turned on at different times.
> 
> Yes it can be handy, but it would require real ABI changes, because driver would have to call 2 things. In current form patch fixes problems that are imporant for us and requires no co-op on driver side.
> I can add requested features in another PR.

I am fine with doing things in steps, but BCLK/MCLK can be considered as. well. clocks, and having a proper clock API would help others as well.

File: src/drivers/intel/cavs/mn.c (hunk 10 above)
Comment (jajanusz) [reply src/drivers/intel/cavs/mn.c]: Added that info to doxygen of this function - if function is globally visible then doxygen comments are in header file (mn.h)

File: src/drivers/intel/cavs/mn.c (hunk 9 above)
Comment (jajanusz) [reply src/drivers/intel/cavs/mn.c]: @ranj063 Did I answer your question?

File: src/drivers/intel/cavs/mn.c (hunk 8 above)
Comment (jajanusz) [reply src/drivers/intel/cavs/mn.c]: Changed to bool table and changed description + added some desc to bclk enum

File: src/drivers/intel/cavs/mn.c (hunk 6 above)
Comment (jajanusz) [reply src/drivers/intel/cavs/mn.c]: Did I give ok arguments behind it or you still don't like this change? ;)

File: src/drivers/intel/cavs/mn.c (hunk 4 above)
Comment (jajanusz) [reply src/drivers/intel/cavs/mn.c]: Changed to defines

File: src/drivers/intel/cavs/mn.c (hunk 2 above)
Comment (jajanusz) [reply src/drivers/intel/cavs/mn.c]: Added more descriptive comment

File: src/drivers/intel/cavs/mn.c (hunk 1 above)
Comment (jajanusz) [reply src/drivers/intel/cavs/mn.c]: Changed to bools to not cause confusion with unnecessary enum

File: src/drivers/intel/cavs/mn.c (hunk 5 above)
Comment (jajanusz) [reply src/drivers/intel/cavs/mn.c]: Is it ok?

**Comment by jajanusz** [comment]
@ranj063 @plbossart Please re-review

File: src/drivers/intel/cavs/mn.c [hunk 13]
```diff
@@ -19,10 +19,31 @@
 #define tracev_mn(__e, ...) \
 	tracev_event(TRACE_CLASS_MN, __e, ##__VA_ARGS__)
 
+/** \brief BCLKs can be driven by multiple sources - M/N or XTAL directly,
```
Comment (plbossart) [inline src/drivers/intel/cavs/mn.c]: nit-pick: 
the description can be improved a bit. Even in the case of M/N, the actual clock source can be XTAL, Audio cardinal clock (24.576) or 96 MHz PLL. The MN block is not really the source of clocks, but rather an intermediate component.

File: src/drivers/intel/cavs/mn.c (hunk 6 above)
Comment (plbossart) [reply src/drivers/intel/cavs/mn.c]: fine with me

File: src/drivers/intel/cavs/mn.c (hunk 5 above)
Comment (ranj063) [reply src/drivers/intel/cavs/mn.c]: yes, its fine @jajanusz. It doesn make it more readable.

File: src/drivers/intel/cavs/mn.c (hunk 6 above)
Comment (ranj063) [reply src/drivers/intel/cavs/mn.c]: @jajanusz yes, the change itself looks fine. I was just arguing about the commit message not conveying the intention properly.

File: src/drivers/intel/cavs/mn.c [hunk 14]
```diff
@@ -102,19 +148,53 @@ int mn_set_mclk(uint16_t mclk_id, uint32_t mclk_rate)
...
+	else
+		ret = setup_initial_mclk_source(mclk_rate);
+
+	if (ret < 0)
+		goto out;
+
+	mclk_sources_used[mclk_id] = true;
+
+	ret = set_mclk_divider(mclk_id,
+			       ssp_freq[mclk_source_clock].freq / mclk_rate);
```
Comment (ranj063) [inline src/drivers/intel/cavs/mn.c]: @jajanusz just to clear my confusion: This means that the last SSP port to be configured determines the mdivr, right? Is the expectation that all the mclk rates requested in topology should be the same for all SSP ports?

**Comment by ranj063** [comment]
@jajanusz looks good now, thanks. @sathya-nujella FYI

File: src/drivers/intel/cavs/mn.c (hunk 14 above)
Comment (jajanusz) [reply src/drivers/intel/cavs/mn.c]: Unfortunetly yes, if you configure MCLK0 for SSP0 and then also MCLK0 for SSP1 then you gonna overwrite first config, it was like that all the time, idk if assumption here was that it's driver/topology responsibility to know what it does. Only improvement IRT to that in this PR is that now you are not gonna overwrite source for MCLK0 when playing with MCLK1. We can add these checks tho.

File: src/drivers/intel/cavs/mn.c (hunk 13 above)
Comment (jajanusz) [reply src/drivers/intel/cavs/mn.c]: Thanks, added this explanation to description.

File: src/drivers/intel/cavs/mn.c (hunk 14 above)
Comment (ranj063) [reply src/drivers/intel/cavs/mn.c]: OK thanks for clarifying!

**Comment by lgirdwood** [comment]
@jajanusz can you check the CI.

**Comment by jajanusz** [comment]
> @jajanusz can you check the CI.

CI was right this time, need to wait for rerun with changes

**Comment by jajanusz** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
@jajanusz @mmaka1  @plbossart @ranj063 I'm seeing the ICL runtime PM test fail on jenkins now for other FW PRs, could this be a kernel issue ?

**Comment by jajanusz** [comment]
SOFCI TEST

**Comment by jajanusz** [comment]
@xiulipan is CI failing randomly or regression got to sof-ci/jenkins?

**Comment by lgirdwood** [comment]
@jajanusz both jenkins failure looks like test script issues rather than FW fails. I've reported the ICL runtime PM test bug as it's showing up on everything now (dmesg is good, but tails fails).

**Comment by xiulipan** [comment]
@jajanusz For BYT it seems to be random issue.
But for ICL, this maybe a known issue related to PM. https://github.com/thesofproject/sof-test/issues/47

PS: we got some regression on sof-dev code base, so all BYT/BSW platform will fail.

**Comment by lgirdwood** [comment]
@xiulipan looks like BYT speaker test is also failing when there is no error in dmesg or trace ?
@jajanusz can you rebase.

**Comment by lgirdwood** [comment]
SOFCI TEST
