### PR TITLE
ll_schedule: fix task insertion

### LINKED ISSUE #2219: [BUG]Unexpected sof error trace print when trigger aplay/arecord
**Describe the bug**
Unexpected sof error trace print when trigger aplay/arecord, but aplay/arecord can work normally, just an error message output

**To Reproduce**
1.sudo reboot
2.aplay -Dhw:0,1 -r48000 -c2 -fs16_le wav/48California_Dreaming.wav -vv -i -d 1 
3.sudo sof-logger -l /etc/sof/sof-*.ldc

**Reproduction Rate**
10/10

**Expected behavior**
There is no sof error trace print when aplay/arecord

**Actual result**
There is sof error trace output when aplay/arecord,but function can work normally

```
CORE  LEVEL      COMP_ID                TIMESTAMP            DELTA                FILE_NAME	CONTENT
    0      1           SA          76527513.697917  76527512.000000      src/lib/agent.c:55  	validate(), ll drift detected, delta = 40493
```

**Environment**
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev commit:c5e4a391
Firmware:https://github.com/thesofproject/sof/commits/master commit: 85e462ad
Can reproduce on all below platforms: TGL RT711 in HDA mode, ICL rt711 in HDA mode, APL-UP2 nocodec, APL-up2 PCM512x in I2S mode, BYT nocode, BYT 5682 in I2S mode.

[dmesg20191217.log](https://github.com/thesofproject/sof/files/3972776/dmesg20191217.log)
[sof_errortrace1217.log](https://github.com/thesofproject/sof/files/3972777/sof_errortrace1217.log)
[sof_trace1217.log](https://github.com/thesofproject/sof/files/3972778/sof_trace1217.log)

### PR DESCRIPTION
**Pull request by tlauda**
Fixes low latency task insertion into the priority list.
From now on tasks will be inserted in the right order based
on their priority and time of insertion.

Signed-off-by: Tomasz Lauda <tomasz.lauda@linux.intel.com>

Fixes #2219.

### CODE REVIEW

File: src/schedule/ll_schedule.c [hunk 1]
```diff
@@ -223,7 +223,7 @@ static void schedule_ll_task_insert(struct task *task, struct list_item *tasks)
 	/* tasks are added into the list in order */
```
Comment (dbaluta) [inline src/schedule/ll_schedule.c]: @tlauda thanks for the patch. Please describe the initial problem in the commit message. What does 'right' order means.

Comment (jajanusz) [reply src/schedule/ll_schedule.c]: Just by looking at code I understand it as - previously task of the same priority that was added later would be triggered earlier, now they it should be intuitive so task are 'sorted by' priority and then order in which they were added.
@tlauda is it right?

**Comment by tlauda** [comment]
SOFCI TEST

**Comment by ranj063** [comment]
@tlauda does this mean tasks with the same priority will be served on a first-come-first-served basis?

File: src/schedule/ll_schedule.c (hunk 1 above)
Comment (dbaluta) [reply src/schedule/ll_schedule.c]: @jajanusz i think you are right but it is not trivial to understand this. Commits should always try to educate the reader and to clarify things.

A commit message should really state: WHY are we making this change. In particular in this case what is the problem and how it was solved:

So, instead of:

``
From now on tasks will be inserted in the right order based
on their priority and time of insertion

``
commit should read:

``There is a problem with the insertion of a task in the list of active(?) tasks. The list should
be sorted by task priority first and then when two tasks have the same priority we should look
of time of insertion. Newer tasks should be placed after older tasks in the list. Anyhow, in the
current implementaion newer task are placed before older tasks thus scheduled first. 

Fix this"

**Comment by dbaluta** [comment]
> @tlauda does this mean tasks with the same priority will be served on a first-come-first-served basis?

After this patch yes. Before this patch they were served last-come-first-served.

**Comment by singalsu** [comment]
I tested this PR and it seems to avoid the DSP panic that is reported in issue #2225.

**Comment by lgirdwood** [comment]
@tlauda can you check CI for ICL

**Comment by tlauda** [comment]
@mmaka1 @dbaluta Commit message changed. Please let me know if it's enough.

**Comment by dbaluta** [comment]
@tlauda thanks a lot! Looks good.

**Comment by lgirdwood** [comment]
CI usual suspects.
