### PR TITLE
probe: small fixes for p3 issues

### LINKED ISSUE #2453: [BUG][WHL][APL]  - stream stall on test with multi probe extraction.
**Describe the bug**
Creating topology with playback and capture pipelines containing 2 volume component for each pipeline and connecting probe points for extracting data from 6 buffers.
Then running simultaneous capture and playback on timer driven pipelines, pipelines stop copping data after trigger_start on playback pipleline and stream stalls.

Bug occurs only with these audio formats:

- 24k 24/32 8ch
- 48k 16/16 8ch
- 48k 24/32 4ch
- 48k 24/32 8ch
- 48k 32/32 4ch
- 48k 32/32 8ch

**Topology**
```
                    pipe_plb
                    +-----------------------------------------+
    +----------+    | +---+  +---+  +---+  +---+  +---+  +---+|   +----+
    | Host plb |----->|Buf|->|Vol|->|Buf|->|Vol|->|Buf|->|Dai|--->|SSP0|
    +----------+    | +---+  +---+  +---+  +---+  +---+  +---+|   +----+
                    +-----------------------------------------+    |  |
                                                                   |  |
                    pipe_cap                                       |  |
                    +-----------------------------------------+    |  |
    +----------+    | +---+  +---+  +---+  +---+  +---+  +---+|   +----+
    | Host cap |<-----|Buf|<-|Vol|<-|Buf|<-|Vol|<-|Buf|<-|Dai|<----|SSP0|
    +----------+    | +---+  +---+  +---+  +---+  +---+  +---+|   +----+
                    +-----------------------------------------+
```

**To Reproduce**
Run slimdriver python tests:
test_03_multi_probe_extraction.py for given formats
--playback_iterations = 1

This also occurs on tests:
- TestProbeParallel48000Hz32b32b8ch
- TestProbeParallel48000Hz24b32b8ch 

**Reproduction Rate**
100 %

**Environment**
SOF master branch 109450e6fdaa9308732e0358dc10680e673f7d58

**Example log**
[2020_02_27_08_09_21.zip](https://github.com/thesofproject/sof/files/4261199/2020_02_27_08_09_21.zip)

### LINKED ISSUE #2548: [BUG]Invalid data in probe point.
**Describe the bug**
When new extraction probe point is added purpose isn't verified by FW.
Also, after adding several extraction probe points, returned Node ID is different when all extraction probe points use the same dma.

**To Reproduce**
On rvp 10.91.113.87 with linux setup:
run: crecord -c0 -d22 -b8192 -f4 -FS32_LE -R48000 -C4 /tmp/extract.wav
login as superuser
echo 2,5,6 > /sys/kernel/debug/sof/probe_points
echo 3,5,8 > /sys/kernel/debug/sof/probe_points
cat /sys/kernel/debug/sof/probe_points

**Reproduction Rate**
100 %

**Expected behavior**
When adding new extraction probe point, purpose should be verified.
Returned value Node id in info params on the extraction probe points should return real id of the dma being used.

**Environment**
WHL RVP
SOF PR: https://github.com/thesofproject/sof/pull/2517 + https://github.com/thesofproject/sof/pull/2508

### PR DESCRIPTION
**Pull request by abonislawski**
This will close all remaining probe issues

Fixes #2548 
Fixes #2453

### CODE REVIEW

File: src/probe/probe.c [hunk 1]
```diff
@@ -1010,6 +1010,8 @@ int probe_point_add(uint32_t count, struct probe_point *probe)
 				tracev_probe("probe_point_add(): start probe task");
 				schedule_task(&_probe->dmap_work, 1000, 1000);
 			}
+			/* ignore probe stream tag for extraction probes */
+			probe[i].stream_tag = _probe->ext_dma.stream_tag;
```
Comment (lgirdwood) [inline src/probe/probe.c]: Should we update the ABI to show it's unused ?

File: src/probe/probe.c [hunk 2]
```diff
@@ -800,6 +800,9 @@ static void probe_cb_produce(void *arg, enum notify_id type, void *data)
 			if (ret < 0)
 				goto err;
 		}
+		/* check if more than 75% of buffer size is already used */
+		if (_probe->ext_dma.dmapb.avail > 0.75 * _probe->ext_dma.dmapb.size)
```
Comment (lgirdwood) [inline src/probe/probe.c]: We should be able to pass thsi in via the command line, alongside the buffer size (otherwise we use defaults).

File: src/probe/probe.c (hunk 1 above)
Comment (abonislawski) [reply src/probe/probe.c]: No, it was ignored in-design for extraction, only valid for injection
To add probe point user have to enter 3x u32 and depending on purpose (extraction/injection): FW will use 2 or 3 of them
No changes for usage flow for user, kernel and FW, we will just not save this ignored field.

File: src/probe/probe.c (hunk 2 above)
Comment (abonislawski) [reply src/probe/probe.c]: Are you sure this is FW change? Looks like you was thinking about probe app

Comment (lgirdwood) [reply src/probe/probe.c]: Your right, the floating point made me think it was the app ! There should be no floating point here, but can do
```
if (avail > size >> 2)
```

File: src/probe/probe.c [hunk 3]
```diff
@@ -800,6 +800,10 @@ static void probe_cb_produce(void *arg, enum notify_id type, void *data)
 			if (ret < 0)
 				goto err;
 		}
+		/* check if more than 75% of buffer size is already used */
+		if (_probe->ext_dma.dmapb.size - _probe->ext_dma.dmapb.avail <
+		    _probe->ext_dma.dmapb.size >> 2)
```
Comment (paulstelian97) [inline src/probe/probe.c]: I still feel like the comment and code have their logic inverted to one another. 75% used means 25% available, yet you check for 25% of size-available (=used).

File: src/probe/probe.c (hunk 2 above)
Comment (abonislawski) [reply src/probe/probe.c]: ups, sorry then, updated with your approach

File: src/probe/probe.c (hunk 3 above)
Comment (abonislawski) [reply src/probe/probe.c]: avail means available data, not free so size-available = free

**Comment by abonislawski** [comment]
@jajanusz checkpatch clear

File: src/probe/probe.c (hunk 3 above)
Comment (paulstelian97) [reply src/probe/probe.c]: Ah okay.

**Comment by lgirdwood** [comment]
@jajanusz Internal CI still not complete ?

**Comment by abonislawski** [comment]
@lgirdwood there is no probe build in CI anyway :)

**Comment by jajanusz** [comment]
> @jajanusz Internal CI still not complete ?

`Expected` means that it's not even started and is in queue.

File: src/probe/probe.c (hunk 1 above)
Comment (ranj063) [reply src/probe/probe.c]: @abonislawski the commit title and comment are misleading. It should say "Overriding the user-provided stream tag for extraction probe points"

File: src/probe/probe.c [hunk 4]
```diff
@@ -1012,6 +1012,11 @@ int probe_point_add(uint32_t count, struct probe_point *probe)
 			}
 			/* ignore probe stream tag for extraction probes */
 			probe[i].stream_tag = _probe->ext_dma.stream_tag;
+		} else {
+			trace_probe_error("probe_point_add() error: invalid purpose %d",
+					  probe[i].purpose);
+
```
Comment (ranj063) [inline src/probe/probe.c]: although valid here, I'd think that this is the first sanity check that the function should be doing. we can simply check if probe[i].purpose > PROBE_PURPOSE_EXTRACTION and return invalid.

Also, the other concern I have is, Because there's the provision for adding multiple probe points with the same command, whats the logic here, do you add all "valid" probe points and ignore the "invalid" ones or you add the first "valid" probe points and return an error as soon as you encounter the first invalid input?

Comment (abonislawski) [reply src/probe/probe.c]: Good point, moved to the beginning.

Currently the logic is to stop and return error if the input is invalid, there are several returns in this function in the case of error.
Of course this can be changed but it should be requested for another PR.

Comment (ranj063) [reply src/probe/probe.c]: Thanks @abonislawski. I will file an issue for it.
