### PR TITLE
scheduler: guard against subdivision underflow on domain clear

### LINKED ISSUE #3947: [BUG][TGL-012-drop-stable] DSM Multicore Stream Stall
**Describe the bug**
In DSM test where DSM component is run on CORE 1 and rest of topology on default CORE 0 after triggering pipelines start, playback pipeline stops copying data.

**Topology**
```
    +----------------------------------------------+
    | +------+   +---+   +- -+   +---+   +-------+ |
    | | Host |-->|Buf|-->|Dsm|-->|Buf|-->|SSP Dai|-------+
    | +------+   +---+   +---+   +---+   +-------+ |     |
    +------------------+   ^   +-------------------+     |
                       |   |   |                         |
                       | +---+ |                         |
                       | |Buf| |                         |
                       | +---+ |                         |
                       +---^---+                         |
    +----------------------|------------------------+    |
    | +------+   +---+   +-|--+   +---+   +-------+ |    |
    | | Host |<--|Buf|<--|Dmux|<--|Buf|<--|SSP Dai|<-----+
    | +------+   +---+   +----+   +---+   +-------+ |
    +-----------------------------------------------+
```

**To Reproduce**
Run Python test:
22_05_TestDsmMulticoreSsp48000Hz24b32b2ch or 22_05_TestDsmMulticoreSsp48000Hz32b32b2ch
with parameters:
--playback-iterations=100

**Reproduction Rate**
~1/10

**Environment**
1) Name of the platform(s) on which the bug is observed.
    * Platform: TGL B0 RVP
2) Firmware branch name and commit 
    * Branch: tgl-012-drop-stable
    * Hash: fa35ee0
3) Python tests branch name and commit
    * Branch: master
    * Hash: 237e3511f3787aa9b45c53b43bea33cfa2646114

**Logs**
[22_05_TestDsmMulticoreSsp48000Hz32b32b2ch FAIL.zip](https://github.com/thesofproject/sof/files/6188732/22_05_TestDsmMulticoreSsp48000Hz32b32b2ch.FAIL.zip)

### LINKED ISSUE #3949: [BUG][TGL-012-drop-stable] PostProcessing Multicore Stream Stall
**Describe the bug**
In Post Processing test where Processor component is run on CORE 1 and rest of topology on default CORE 0 after triggering pipelines start, playback pipeline stops copying data.

**Topology**
```
                +------------------------------------+
    +------+    | +---+  +-------+  +---+  +-------+ |
    | Host |----->|Buf|->|GenProc|->|Buf|->|SSP Dai|---+
    +------+    | +---+  +-------+  +---+  +-------+ | |
                +------------------------------------+ |
                                                       |
                +------------------+                   |
    +------+    | +---+  +-------+ |                   |
    | Host |<-----|Buf|<-|SSP Dai|<--------------------+
    +------+    | +---+  +-------+ |
                +------------------+
```

**To Reproduce**
Run Python test:
25_06_TestGenericProcessorPplMultiCorePlb48000Hz16b16b4ch or 25_06_TestGenericProcessorPplMultiCorePlb48000Hz32b32b8ch
with parameters:
--playback-iterations=100

**Reproduction Rate**
~1/50

**Environment**
1) Name of the platform(s) on which the bug is observed.
    * Platform: TGL B0 RVP
2) Firmware branch name and commit 
    * Branch: tgl-012-drop-stable
    * Hash: fa35ee0
3) Python tests branch name and commit
    * Branch: master
    * Hash: 237e3511f3787aa9b45c53b43bea33cfa2646114

**Logs**
[25_06_TestGenericProcessorPplMultiCorePlb48000Hz16b16b4ch FAIL.zip](https://github.com/thesofproject/sof/files/6188976/25_06_TestGenericProcessorPplMultiCorePlb48000Hz16b16b4ch.FAIL.zip)

### LINKED ISSUE #3950: [BUG][TGL-012-drop-stable] SRC Multicore Stream Stall
**Describe the bug**
In SRC test where SRC component is run on CORE 1 and rest of topology on default CORE 0 after triggering pipelines start, playback pipeline stops copying data.

**Topology**
```
                    pipe_plb core 0, src core 1
           +--------------------------------+
    +----+ | +---+  +---+  +---+  +-------+ |
    |Host|-->|Buf|->|Src|->|Buf|->|SSP Dai|---+
    +----+ | +---+  +---+  +---+  +-------+ | |
           +--------------------------------+ |
                    pipe_cap core 0           |
           +------------------+               |
    +----+ | +---+  +-------+ |               |
    |Host|<--|Buf|<-|SSP Dai|<----------------+
    +----+ | +---+  +-------+ |
           +------------------+
```

**To Reproduce**
Run Python test:
17_06_TestMultiCoreCompSrcPlb48000Hz32b32b4c
with parameters:
--playback-iterations=100

**Reproduction Rate**
~1/50

**Environment**
1) Name of the platform(s) on which the bug is observed.
    * Platform: TGL B0 RVP
2) Firmware branch name and commit 
    * Branch: tgl-012-drop-stable
    * Hash: fa35ee0
3) Python tests branch name and commit
    * Branch: master
    * Hash: 237e3511f3787aa9b45c53b43bea33cfa2646114

**Logs**
[17_06_TestMultiCoreCompSrcPlb48000Hz32b32b4ch FAIL.zip](https://github.com/thesofproject/sof/files/6189004/17_06_TestMultiCoreCompSrcPlb48000Hz32b32b4ch.FAIL.zip)

### PR DESCRIPTION
**Pull request by slawblauciak**
In some situations the domain clear routine might encounter
a case, when the number of clients is decremented and 0,
as such, a subsequent subdivision will result in an integer underflow.

Signed-off-by: Slawomir Blauciak <slawomir.blauciak@linux.intel.com>

Fixes #3950 
Fixes #3949 
Fixes #3947

### CODE REVIEW

File: src/schedule/ll_schedule.c [hunk 1]
```diff
@@ -331,9 +331,11 @@ static void schedule_ll_domain_clear(struct ll_schedule_data *sch,
 	if (count == 1) {
 		sch->domain->registered[cpu_get_id()] = false;
 
-		count = atomic_sub(&sch->domain->num_clients, 1);
-		if (count == 1)
-			domain_clear(sch->domain);
+		if (atomic_read(&sch->domain->num_clients)) {
+			count = atomic_sub(&sch->domain->num_clients, 1);
```
Comment (jgunn0262) [inline src/schedule/ll_schedule.c:335]: What happens if num_clients changes here between reading and subtracting. @lgirdwood @plbossart what do you think ?

Comment (keyonjie) [reply src/schedule/ll_schedule.c:335]: > What happens if num_clients changes here between reading and subtracting. @lgirdwood @plbossart what do you think ?

We hold the domain->lock during these checks so that should not happen.

BTW, we are kind of mess in this client/task management, I am working on refining them, please see the PR here: https://github.com/thesofproject/sof/pull/4089

**Review by keyonjie — COMMENTED** [review]
Nice observation @slawblauciak , we are somewhat mess in this client/task management part, better to do a thorough cleanup here, please see my PR https://github.com/thesofproject/sof/pull/4089.

File: src/schedule/ll_schedule.c (hunk 1 above)
Comment (lgirdwood) [reply src/schedule/ll_schedule.c:335]: ok, this is fine with the locks held.

**Review by lgirdwood — APPROVED** [review]
Good find @slawblauciak !

**Comment by lgirdwood** [comment]
@keyonjie @slawblauciak can we use this in TGL 12 and integrate this alongside the cleanup in v1.8 ?

**Comment by slawblauciak** [comment]
> @keyonjie @slawblauciak can we use this in TGL 12 and integrate this alongside the cleanup in v1.8 ?

Yeah, the plan is to use it with TGL 12 for sure. Not certain about Keyon's change yet.

**Comment by lgirdwood** [comment]
@keyonjie lets clean up for v1.8 if things are messy today.

**Comment by keyonjie** [comment]
> @keyonjie lets clean up for v1.8 if things are messy today.

sounds good.
