### PR TITLE
trace: remove unused variables if TRACE disabled

### LINKED ISSUE #1574: [BUG] Build fails with TRACE disabled
**Describe the bug**
Disable all trace in Kconfig.
```
[ 83%] Building C object CMakeFiles/sof.dir/src/drivers/dw/dma.c.o
/home/lrg/work/sof/xtensa-cnl-elf/bin/xtensa-cnl-elf-gcc  -I/home/lrg/work/sof/sof/src/platform/intel/cavs/include -I/home/lrg/work/sof/sof/src/arch/xtensa/include -I/home/lrg/work/sof/sof/src/arch/xtensa/smp/include -I/home/lrg/work/sof/sof/src/arch/xtensa/smp/xtos -I/home/lrg/work/sof/sof/src/platform/icelake/include -I/home/lrg/work/sof/sof/src/platform/icelake/include/arch -I/home/lrg/work/sof/sof/../xtensa-root/xtensa-cnl-elf/include -I/home/lrg/work/sof/sof/src/include -I/home/lrg/work/sof/sof/build_icl_gcc/generated/include  -nostdlib -fno-inline-functions -mlongcalls -O2 -g -Wall -Werror -Wl,-EL -Wmissing-prototypes -mtext-section-literals -o CMakeFiles/sof.dir/src/drivers/dw/dma.c.o   -c /home/lrg/work/sof/sof/src/drivers/dw/dma.c
/home/lrg/work/sof/sof/src/drivers/intel/cavs/hda-dma.c: In function 'hda_dma_wait_for_buffer_full':
/home/lrg/work/sof/sof/src/drivers/intel/cavs/hda-dma.c:263:11: error: variable 'wp' set but not used [-Werror=unused-but-set-variable]
  uint32_t wp;
           ^~
/home/lrg/work/sof/sof/src/drivers/intel/cavs/hda-dma.c:262:11: error: variable 'rp' set but not used [-Werror=unused-but-set-variable]
  uint32_t rp;
           ^~
/home/lrg/work/sof/sof/src/drivers/intel/cavs/hda-dma.c: In function 'hda_dma_wait_for_buffer_empty':
/home/lrg/work/sof/sof/src/drivers/intel/cavs/hda-dma.c:291:11: error: variable 'wp' set but not used [-Werror=unused-but-set-variable]
  uint32_t wp;
           ^~
/home/lrg/work/sof/sof/src/drivers/intel/cavs/hda-dma.c:290:11: error: variable 'rp' set but not used [-Werror=unused-but-set-variable]
  uint32_t rp;
           ^~
```
Error trace should should write only to persistent/shared buffer when TRACE is disabled.

### PR DESCRIPTION
**Pull request by abonislawski**
gcc will show errors if variables are set but not used, this will remove such a situations in fw if TRACE disabled

This + #1579 will fix: issue #1574

### CODE REVIEW

File: src/audio/kpb.c [hunk 1]
```diff
@@ -794,12 +794,11 @@ static uint64_t kpb_draining_task(void *arg)
 	size_t size_to_copy;
 	bool move_buffer = false;
 	uint32_t drained = 0;
-	uint64_t time_start;
-	uint64_t time_end;
+	uint64_t timer;
```
Comment (jajanusz) [inline src/audio/kpb.c]: It's not a timer, ticks or time may be better names.

File: src/audio/kpb.c [hunk 2]
```diff
@@ -834,7 +833,7 @@ static uint64_t kpb_draining_task(void *arg)
 			comp_update_buffer_produce(sink, size_to_copy);
 	}
 
-	time_end =  platform_timer_get(platform_timer);
+	timer =  platform_timer_get(platform_timer) - timer;
```
Comment (jajanusz) [inline src/audio/kpb.c]: @lgirdwood We need config in CI that build something else that default config. F.e. debug or no-trace builds. Most developers while doing PRs just checks default config, just like CI. Maintaining traceless build that can fail on things like that will be hard.

File: src/audio/kpb.c (hunk 1 above)
Comment (abonislawski) [reply src/audio/kpb.c]: updated

File: src/audio/kpb.c [hunk 3]
```diff
@@ -834,7 +833,7 @@ static uint64_t kpb_draining_task(void *arg)
 			comp_update_buffer_produce(sink, size_to_copy);
 	}
 
-	time_end =  platform_timer_get(platform_timer);
+	time =  platform_timer_get(platform_timer) - time;
```
Comment (jajanusz) [inline src/audio/kpb.c]: I expected gcc to complain here, but turns out it warns about useless writes only if there is no read at all, doesn't matter when...

Comment (lgirdwood) [reply src/audio/kpb.c]: @jajanusz can you paste error here. It should be fixed by using ```if (0)``` as my review below.

**Comment by lgirdwood** [comment]
@abonislawski code check failing

File: src/audio/kpb.c (hunk 2 above)
Comment (xiulipan) [reply src/audio/kpb.c]: @jajanusz 
Can we change the config with some scripts? I prefer to do that with some scripts inside this repo so that we can make sure we can cover all config once it comes out.

**Comment by abonislawski** [comment]
> @abonislawski code check failing

Its random fail not related to this PR, all checks have passed now :)

**Comment by lgirdwood** [comment]
@abonislawski ok thanks, but now there is a conflict ;)

File: src/audio/kpb.c (hunk 2 above)
Comment (jajanusz) [reply src/audio/kpb.c]: @xiulipan You can change single configs like in scripts/xtensa-build-all.sh

**Comment by abonislawski** [comment]
> @abonislawski ok thanks, but now there is a conflict ;)

ok, resolved ;-)

File: src/audio/kpb.c (hunk 3 above)
Comment (jajanusz) [reply src/audio/kpb.c]: @lgirdwood I meant that I expected warn/error, but there isn't, so gcc disappointed me ;) In many compiles useless writes are warns.
