### PR TITLE
Fix playback and capture multiple runs which occasionally fails with Input/output error

### LINKED ISSUE #3809: [BUG IMX] Playback and capture occasionally fails
**Describe the bug**
Playback and capture occasionally fails with Input/output error

**To Reproduce**
Run playback and capture simultaneously.
Or run the script below:
```
#!/bin/bash

test_aplay()
{
    while true
    do
        aplay -Dhw:1,0 -f S32_LE -c 2 -r 48000 -t raw test_play.wav
    done
}

test_arecord()
{
    while true
    do
        arecord  -Dhw:1,0 -f S32_LE -c 2 -r 48000 -d 5 test_record.pcm
    done
}

test_aplay &
test_arecord
```

**Reproduction Rate**
20%

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: 5.10
    * SOF: master,  imx-stable-v1.5, imx-stable-v1.6.
2) Name of the topology file
    * Topology: sof-imx8qxp-wm8960.tplg, sof-imx8qxp-cs42888-mixer.tplg, sof-imx8mp-wm8960.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform:  i.MX8QXP/i.MX8QM/i.MX8MP

**Screenshots or console output**
```
root@imx8qmmek:~# audio_dsp_sof.sh -t 4 -c wm8960 -f p -n 50
DSP_SOF_PLAY_RECORD_WORK_TOGETHER    0  TINFO  :  test 4: DSP_SOF_PLAY_RECORD_WORK_TOGETHER 
TINFO  :  Do full hardware capacity test 
TINFO  :  Do full hardware capacity test 
TINFO  :  Start audio test, please check the HEADPHONE,hear if there is voice.
TINFO  :  Audio TEST: Total 3 combinations of formats. 
TINFO  :  No.[1] Now playing audio stream with format S16_LE, channel 2,sample rate 48000
TINFO  :  Test #1: ADC record test. Headphone is need to check the voice and quality of recording.
TINFO  :  Audio TEST: Total 3 combinations of formats. 
TINFO  :  No.[1] Now Recording audio stream with format S16_LE, channel 2,sample rate 48000
TINFO  :  No.[2] Now playing audio stream with format S24_LE, channel 2,sample rate 48000
TINFO  :  No.[3] Now playing audio stream with format S32_LE, channel 2,sample rate 48000
TINFO  :  No.[2] Now Recording audio stream with format S24_LE, channel 2,sample rate 48000
TINFO  :  Start audio test, please check the HEADPHONE,hear if there is voice.
TINFO  :  Audio TEST: Total 3 combinations of formats. 
TINFO  :  No.[4] Now playing audio stream with format S16_LE, channel 2,sample rate 48000
TINFO  :  No.[5] Now playing audio stream with format S24_LE, channel 2,sample rate 48000
TINFO  :  No.[3] Now Recording audio stream with format S32_LE, channel 2,sample rate 48000
TFAIL  :  ltpapicmd.c:188: Test #1: Playing back audio48k24b2c_sle.pcm Failed on hw:1,0
Playing raw data '/tmp/tmpfs/tmp.jWsafwNfuh/audio48k24b2c_sle.pcm' : Signed 24 bit Little Endian, Rate 48000 Hz, Stereo
aplay: pcm_write:2061: write error: Input/output error
TINFO  :  No.[6] Now playing audio stream with format S32_LE, channel 2,sample rate 48000
TINFO  :  Test #1: ADC record test. Headphone is need to check the voice and quality of recording.
TINFO  :  Audio TEST: Total 3 combinations of formats. 
TINFO  :  No.[4] Now Recording audio stream with format S16_LE, channel 2,sample rate 48000
TFAIL: Audio Playback test fails in loop time 2
TFAIL: Test Failed on below file: audio48k24b2c_sle.pcm 
TGE_LV_DAC2    1  TFAIL  :  ltpapicmd.c:188: Test FAIL
^CTFAIL: Test #1: Recording audio48k16b2c_sle.pcm Failed on hw:1,0
Recording raw data '/tmp/tmpfs/tmp.Nzsd3l5HpA/audio48k16b2c_sle.pcm' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
Aborted by signal Interrupt...
^C^Caplay: no process found
arecord: no process found

root@imx8qmmek:~# ^C
```

### PR DESCRIPTION
**Pull request by iuliana-prodan**
This pull request fixes #3809.

The first commit updates the correct order for DAI and DMA start/stop.
Before this update, on multiple start/stop runs for playback or record or combined,
we get an underrun/overflow.
That's because the DAI makes a DMA request, before the DMA channel is
enabled.

The second commit updates the start/stop operations for SAI.
Please see a more detailed explanation in the commit message.

After the first 3 commits, after multiple playback/capture runs (~700, ~1000)
everything seems ok. 
But, sometimes, when running a second/third time, the same 700 loop I get an "ipc timed out for 0x60050000 size 12".
Here's a log:
```
Playing raw data '16/j16.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
Playing raw data '16/j16.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
Recording WAVE 'test_record.pcm' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
[  582.814139] sof-audio-of 556e8000.dsp: error: ipc timed out for 0x60050000 size 12
[  582.821802] sof-audio-of 556e8000.dsp: info: preventing DSP entering D3 state to preserve context
[  582.830906] sof-audio-of 556e8000.dsp: invalid header size 0x2000200. FW oops is bogus
[  582.838989] sof-audio-of 556e8000.dsp: error: unexpected fault 0x00000000 trace 0x00000000
[  582.847530] sof-audio-of 556e8000.dsp: error: waking up any trace sleepers
[  582.854601] sof-audio-of 556e8000.dsp: error: trace IO error
[  582.861198] sof-audio-of 556e8000.dsp: ASoC: error at snd_soc_pcm_component_trigger on 556e8000.dsp: -110
[  582.871466]  Port0: ASoC: trigger FE cmd: 0 failed: -110
Playing raw data '16/j16.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
Recording WAVE 'test_record.pcm' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
aplay: pcm_write:2061: write error: Input/output error
(null)      1  TFAIL  :  ltpapicmd.c:188: Test 420 Playback failed
Recording WAVE 'test_record.pcm' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
Recording WAVE 'test_record.pcm' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
```
By looking in the trace I saw that the stop cmd is not triggered in DSP
and in SAI we get two start operations one after another.
Therefore, in the 3rd commit, we check in SAI, on start, if a start was already
triggered, disable just the DMA request and the data channel.

### CODE REVIEW

File: src/drivers/imx/sai.c [hunk 1]
```diff
@@ -264,6 +308,10 @@ static inline int sai_set_config(struct dai *dai,
 
 	val_cr2 |= REG_SAI_CR2_SYNC;
 	mask_cr2 |= REG_SAI_CR2_SYNC_MASK;
+
+	/* TODO: for the time being use half FIFO size as watermark */
+	dai_update_bits(dai, REG_SAI_XCR1(REG_RX_DIR),
+			REG_SAI_CR1_RFW_MASK, SAI_FIFO_WORD_SIZE / 2);
 	dai_update_bits(dai, REG_SAI_XCR2(REG_RX_DIR), mask_cr2, val_cr2);
 	dai_update_bits(dai, REG_SAI_XCR4(REG_RX_DIR), mask_cr4, val_cr4);
```
Comment (dbaluta) [inline src/drivers/imx/sai.c:339]: Ok, so you move FIFO_WORD_SIZE setting from sai_start to sai_set_config? I can understand this change but you need to add it in a separate patch and explain why is it needed. It doesn't look to be related to the current change.

File: src/drivers/imx/sai.c [hunk 2]
```diff
@@ -33,39 +33,62 @@ static void sai_start(struct dai *dai, int direction)
 
 	uint32_t xcsr = 0U;
```
Comment (dbaluta) [inline src/drivers/imx/sai.c:34]: @ranj063 @plbossart I wonder if you can share your experience with IPC here. In stress tests, we get an IPC timeouts for stream STOP command.

File: src/audio/dai.c [hunk 3]
```diff
@@ -651,11 +651,11 @@ static int dai_comp_trigger_internal(struct comp_dev *dev, int cmd)
 
 		/* only start the DAI if we are not XRUN handling */
```
Comment (dbaluta) [inline src/audio/dai.c:652]: @iuliana-prodan this is also the order ALSA uses to enable DAI and DMA, so in principle I agree with this change. Lets also hear Intel folks opinion on this as I remember they did the reverse change.

Comment (iuliana-prodan) [reply src/audio/dai.c:652]: The order is not my opinion, this is what is written in i.MX reference manual (one can check for "Suspend/resume a DMA channel with active hardware service requests").

File: src/drivers/imx/sai.c (hunk 1 above)
Comment (iuliana-prodan) [reply src/drivers/imx/sai.c:339]: Yes, I've missed this change. I'll add a new commit.
There's no need to set the FIFO size each time, on start.

File: src/drivers/imx/sai.c (hunk 2 above)
Comment (iuliana-prodan) [reply src/drivers/imx/sai.c:34]: @dbaluta if you refer to "ipc timed out", yes, you're right. I don't know exactly the root cause. The 3rd commit is optional, but the additional checks don't hurt :)

**Comment by aiChaoSONG** [comment]
SOFCI TEST

**Review by paulstelian97 — APPROVED** [review]

**Comment by keyonjie** [comment]
Looks this fails on some BYT platforms according to CI?

**Comment by aiChaoSONG** [comment]
The failures on BYT are all related to pipeline `PCM: PCM Deep Buffer [hw:0,1]`

File: src/drivers/imx/sai.c (hunk 1 above)
Comment (dbaluta) [reply src/drivers/imx/sai.c:339]: @iuliana-prodan you can add a new commit. That's an obvious change and if you want to be merged faster we can send it in a separate PR. 
For the rest of the changes lets give Intel people some time to look at this. I will also want to take my time to make some suggestions by the end of the week.

**Review by dbaluta — CHANGES_REQUESTED** [review]

**Comment by iuliana-prodan** [comment]
The only thing that might impact the CI tests it's the order from dai (commit 1).
I saw this commit 5c8c804766 ("dai: change starting sequence"), but it says "The purpose of this change is to allow slave interfaces to prepare their FIFOs before DMA starts transferring to them.".
I believe there are multiple Intel's topologies that uses slave interfaces, not just sof-byt-nocodec.tplg (this is from the failed test, but I cannot find it in sof repo).

Therefore, can somebody explain why, in the first place, the order for DAI and DMA was changed?
Where is this sof-byt-nocodec.tplg? Is it just for testing?

Thanks!

**Comment by iuliana-prodan** [comment]
I looked further into the error and the problems seems to be on [dw_dma_stop](https://github.com/thesofproject/sof/blob/master/src/drivers/dw/dma.c#L389), which expects for the [fifo to be cleared](https://github.com/thesofproject/sof/blob/master/src/drivers/dw/dma.c#L423).
Most probably this is not drained anymore because the peripheral was stopped before the DMA.
Why do you need to clear the fifo? We just stopped the operation, can we just reset the fifo?
Or, isn’t this fifo emptied by default? Sorry, I don’t know the hardware. 

In the imx case, this is not applicable.

If there is no other way to empty the fifo, maybe we can add the “#if CONFIG_DMA_SUSPEND_DRAIN” in dai.c and, for this case, we keep the old order for DAI and DMA.

**Comment by lgirdwood** [comment]
> @aiChaoSONG @keyonjie @lgirdwood @ranj063 @plbossart
> 
> I looked further into the error and the problems seems to be on [dw_dma_stop](https://github.com/thesofproject/sof/blob/master/src/drivers/dw/dma.c#L389), which expects for the [fifo to be cleared](https://github.com/thesofproject/sof/blob/master/src/drivers/dw/dma.c#L423).
> Most probably this is not drained anymore because the peripheral was stopped before the DMA.
> Why do you need to clear the fifo? 

The DW DMA needs the FIFO clear so it's in a empty state prior to next usage. i.e. no stale data is sent out.

We just stopped the operation, can we just reset the fifo?
> Or, isn’t this fifo emptied by default? Sorry, I don’t know the hardware.
> 
> In the imx case, this is not applicable.

ok, we need to differentiate then.

> 
> If there is no other way to empty the fifo, maybe we can add the “#if CONFIG_DMA_SUSPEND_DRAIN” in dai.c and, for this case, we keep the old order for DAI and DMA.

The best place for this is in the DMA driver and not any core logic. Btw, I dont see any reference to draining in dai.c, can you tell me where you would put the ifdef ?

**Comment by iuliana-prodan** [comment]
> > If there is no other way to empty the fifo, maybe we can add the “#if CONFIG_DMA_SUSPEND_DRAIN” in dai.c and, for this case, we keep the old order for DAI and DMA.
> 
> The best place for this is in the DMA driver and not any core logic. Btw, I dont see any reference to draining in dai.c, can you tell me where you would put the ifdef ?

@lgirdwood There is already a CONFIG_DMA_SUSPEND_DRAIN in [dw/dma.c](https://github.com/thesofproject/sof/blob/master/src/drivers/dw/dma.c#L415). 
I was thinking to add the same config (CONFIG_DMA_SUSPEND_DRAIN) in dai.c, in start and stop operations.
If the CONFIG_DMA_SUSPEND_DRAIN is set, we keep the order as before this change, otherwise we use the new order (added by commit 1 from this pull request).

**Comment by dbaluta** [comment]
@lgirdwood Linux kernel ALSA order of DAI/DMA start is as @iuliana-prodan fixed in her patch. Any idea, why the ALSA with a non-dsp setup works but the DSP has problems?

**Comment by lgirdwood** [comment]
> @lgirdwood Linux kernel ALSA order of DAI/DMA start is as @iuliana-prodan fixed in her patch. Any idea, why the ALSA with a non-dsp setup works but the DSP has problems?

Any update, could it be Pulseaudio searching for working configs on each PCM ?

**Comment by lgirdwood** [comment]
> > If there is no other way to empty the fifo, maybe we can add the “#if CONFIG_DMA_SUSPEND_DRAIN” in dai.c and, for this case, we keep the old order for DAI and DMA.
> 
> The best place for this is in the DMA driver and not any core logic. Btw, I dont see any reference to draining in dai.c, can you tell me where you would put the ifdef ?

@iuliana-prodan So looking at the code again this is high level ordering and IIRC we also have a similar configuration in ASoC.

I would agree now and say here that we cant easily do in dma driver, it's a higher level framework CONFIG_ Kconfig setting. i.e. IMX should enable this in the Kconfig, I'm gathering patches for v1.7-final so we should add this fix.

File: src/drivers/imx/sai.c (hunk 1 above)
Comment (iuliana-prodan) [reply src/drivers/imx/sai.c:339]: @dbaluta I've added a new commit just for the SAI watermark.

File: src/audio/dai.c [hunk 4]
```diff
@@ -695,8 +695,21 @@ static int dai_comp_trigger_internal(struct comp_dev *dev, int cmd)
...
+ */
+#if CONFIG_DMA_SUSPEND_DRAIN
 		ret = dma_stop(dd->chan);
 		dai_trigger(dd->dai, cmd, dev->direction);
+#else
+		dai_trigger(dd->dai, cmd, dev->direction);
+		ret = dma_stop(dd->chan);
+#endif
 		break;
 	case COMP_TRIGGER_PAUSE:
```
Comment (dbaluta) [inline src/audio/dai.c:714]: @iuliana-prodan shouldn't we do the same thing at start? I mean the order of dai/dma start/stop should be in reverse one to each other.

Comment (iuliana-prodan) [reply src/audio/dai.c:714]: At first, I thought the same thing.
But I've looked at the explanation for DMA_SUSPEND_DRAIN, from [Kconfig](https://github.com/thesofproject/sof/blob/master/Kconfig#L70) and this seems to happen only on stop.
Also, in the Intel's DMA driver this is only checked on [dw_dma_stop()](https://github.com/thesofproject/sof/blob/master/src/drivers/dw/dma.c#L389).

Comment (dbaluta) [reply src/audio/dai.c:714]: Ok, I see. So, I'm fine with patches 1 and 2. I need to better review 3) and I think it is fine. I have my doubts about 4.

File: src/drivers/imx/sai.c [hunk 5]
```diff
@@ -74,32 +110,39 @@ static void sai_stop(struct dai *dai, int direction)
...
+		}
+	} else {
+		/* Check if the opposite direction is also disabled */
+		xcsr = dai_read(dai, REG_SAI_XCSR(DAI_DIR_CAPTURE));
+		if (!(xcsr & REG_SAI_CSR_FRDE)) {
+			dai_update_bits(dai, REG_SAI_XCSR(DAI_DIR_PLAYBACK), REG_SAI_CSR_TERE, 0);
+			poll_for_register_delay(dai_base(dai) + REG_SAI_XCSR(DAI_DIR_PLAYBACK),
+						REG_SAI_CSR_TERE, 0, 100);
+		}
 	}
```
Comment (dbaluta) [inline src/drivers/imx/sai.c:169]: At least this part can be rewritten like this:

```
	/* Disable transmitter/receiver */
	if (direction == DAI_DIR_CAPTURE) {
		dai_update_bits(dai, REG_SAI_XCSR(DAI_DIR_CAPTURE), REG_SAI_CSR_TERE, 0);
		poll_for_register_delay(dai_base(dai) + REG_SAI_XCSR(DAI_DIR_CAPTURE),
					REG_SAI_CSR_TERE, 0, 100);
	}
	
	
	/* Check if the opposite direction is also disabled */
	xcsr = dai_read(dai, REG_SAI_XCSR(!direction));
	if (!(xcsr & REG_SAI_CSR_FRDE)) {
		dai_update_bits(dai, REG_SAI_XCSR(!direction), REG_SAI_CSR_TERE, 0);
		poll_for_register_delay(dai_base(dai) + REG_SAI_XCSR(!direction),
						REG_SAI_CSR_TERE, 0, 100);
	}
```

Comment (iuliana-prodan) [reply src/drivers/imx/sai.c:169]: It can be written like that only if this
```
if (!(xcsr & REG_SAI_CSR_FRDE)) {
		dai_update_bits(dai, REG_SAI_XCSR(!direction), REG_SAI_CSR_TERE, 0);
		poll_for_register_delay(dai_base(dai) + REG_SAI_XCSR(!direction),
						     REG_SAI_CSR_TERE, 0, 100);
}
```
changes to this:

```
if (!(xcsr & REG_SAI_CSR_FRDE)) {
		dai_update_bits(dai, REG_SAI_XCSR(DAI_DIR_PLAYBACK), REG_SAI_CSR_TERE, 0);
		poll_for_register_delay(dai_base(dai) + REG_SAI_XCSR(DAI_DIR_PLAYBACK),
						     REG_SAI_CSR_TERE, 0, 100);
}
```

**Comment by iuliana-prodan** [comment]
@dbaluta I've added a new version.
As per our discussion, I've dropped the 4th commit from my previous version (the extra checks for `ipc timed out` issue).
This needs more debugging and it will be handled in a separate pull request.

I've also separated the "sai start/stop operations" in 3 patches since some changes are not linked.

File: src/drivers/imx/sai.c (hunk 5 above)
Comment (iuliana-prodan) [reply src/drivers/imx/sai.c:139]: As per our discussion, I've kept the original code for a clear/better understanding.

**Review by dbaluta — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@zrombel this PR should have 0 impact on Intel systems but I do see it failing all codec PR tests ? Is this a false positive ?

**Comment by iuliana-prodan** [comment]
@lgirdwood @dbaluta 
"All checks have passed" - I think is good to be merged :)

**Comment by dbaluta** [comment]
Done. Iulia now we should backport these changes on 1.5 and 1.6 :D

**Comment by iuliana-prodan** [comment]
> Done. Iulia now we should backport these changes on 1.5 and 1.6 :D

Yes, I will backport these patches.
Thanks!
