### PR TITLE
LL scheduler domain refinement

### LINKED ISSUE #3947: [BUG][TGL-012-drop-stable] DSM Multicore Stream Stall
**Describe the bug**
In DSM test where DSM component is run on CORE 1 and rest of topology on default CORE 0 after triggering pipelines start, playback pipeline stops copying data.

**Topology**
```
    +----------------------------------------------+
    | +------+   +---+   +- -+   +---+   +-------+ |
    | | Host |-->|Buf|-->|Dsm|-->|Buf|-->|SSP Dai|-------+
    | +------+   +---+   +---+   +---+   +-------+ |     |
    +------------------+   ^   +-------------------+     |
                       |   |   |                         |
                       | +---+ |                         |
                       | |Buf| |                         |
                       | +---+ |                         |
                       +---^---+                         |
    +----------------------|------------------------+    |
    | +------+   +---+   +-|--+   +---+   +-------+ |    |
    | | Host |<--|Buf|<--|Dmux|<--|Buf|<--|SSP Dai|<-----+
    | +------+   +---+   +----+   +---+   +-------+ |
    +-----------------------------------------------+
```

**To Reproduce**
Run Python test:
22_05_TestDsmMulticoreSsp48000Hz24b32b2ch or 22_05_TestDsmMulticoreSsp48000Hz32b32b2ch
with parameters:
--playback-iterations=100

**Reproduction Rate**
~1/10

**Environment**
1) Name of the platform(s) on which the bug is observed.
    * Platform: TGL B0 RVP
2) Firmware branch name and commit 
    * Branch: tgl-012-drop-stable
    * Hash: fa35ee0
3) Python tests branch name and commit
    * Branch: master
    * Hash: 237e3511f3787aa9b45c53b43bea33cfa2646114

**Logs**
[22_05_TestDsmMulticoreSsp48000Hz32b32b2ch FAIL.zip](https://github.com/thesofproject/sof/files/6188732/22_05_TestDsmMulticoreSsp48000Hz32b32b2ch.FAIL.zip)

### PR DESCRIPTION
**Pull request by keyonjie**
clean up of the ll_scheduler domain clients/tasks management.

    ll_schedule: domain client/task refinement
    
    Refinement to make the domain client/task management more clear:
    
    a. update the total_num_tasks and num_clients in the helper pair
    domain_register/unregister().
    
    b. update the enabled[core] and enabled_clients in the helper pair
    domain_enable/disable().
    
    c. for the completed task, do the domain client/task update in the new
    created helper schedule_ll_task_done().
    
    d. cleanup and remove the client/task management from the ll_schedule
    helpers schedule_ll_clients_enable(), schedule_ll_tasks_run(),
    schedule_ll_domain_set() and schedule_ll_domain_clear().
    
    Signed-off-by: Keyon Jie <yang.jie@linux.intel.com>

    This is aim to fix #3947 #3949 #3950.

    Without those refinement, the num_clients was not used correctly, we wanted to use it for both num_registered_cores and 
    num_enabled_cores, with that @slawblauciak observed it may be changed to '-1' when component/pipeline is asked for 
    running on a slave core. That's why we are seeing issues #3947 #3949 #3950.

    This reverts changes in 'commit b500999477ca ("scheduler: guard against
    subdivision underflow on domain clear")' as it is not needed anymore.

### CODE REVIEW

File: src/schedule/dma_multi_chan_domain.c [hunk 1]
```diff
@@ -201,7 +202,7 @@ static void dma_multi_chan_domain_unregister(struct ll_schedule_domain *domain,
 
 	/* check if task should be unregistered */
 	if (!pipe_task->registrable)
-		return;
+		return -EINVAL;
```
Comment (jgunn0262) [inline src/schedule/dma_multi_chan_domain.c:205]: I dont know how failure will impact the scheduler, but this is probably important so should it be logged ?

File: src/schedule/dma_single_chan_domain.c [hunk 2]
```diff
@@ -370,27 +371,29 @@ static void dma_single_chan_domain_unregister(struct ll_schedule_domain *domain,
...
 	if (dma_domain->owner == core) {
 		dma_domain_unregister_owner(domain, data);
-		return;
+		return 0;
 	}
 
 	/* some channel still running, so return */
 	if (dma_chan_is_any_running(dmas, dma_domain->num_dma))
-		return;
+		return -EINVAL;
```
Comment (jgunn0262) [inline src/schedule/dma_single_chan_domain.c:388]: There are a lot more error paths now. This likely means more cause for failure and would be good to see this when debugging in the logs.

File: src/include/sof/schedule/ll_schedule_domain.h [hunk 3]
```diff
@@ -46,6 +46,7 @@ struct ll_schedule_domain {
 	spinlock_t lock;		/**< standard lock */
 	atomic_t total_num_tasks;	/**< total number of registered tasks */
 	atomic_t num_clients;		/**< number of registered cores */
+	atomic_t enabled_clients;	/**< number of enabled cores */
```
Comment (jgunn0262) [inline src/include/sof/schedule/ll_schedule_domain.h:49]: This is confusing - clients should be renamed to cores.

File: src/include/sof/schedule/ll_schedule_domain.h [hunk 4]
```diff
@@ -106,51 +125,65 @@ static inline int domain_register(struct ll_schedule_domain *domain,
 
 	ret = domain->ops->domain_register(domain, period, task, handler, arg);
 
+	if (!ret) {
```
Comment (jgunn0262) [inline src/include/sof/schedule/ll_schedule_domain.h:128]: I dont understand why we are increasing ref counts if registration fails ?

File: src/include/sof/schedule/ll_schedule_domain.h [hunk 5]
```diff
@@ -106,51 +125,65 @@ static inline int domain_register(struct ll_schedule_domain *domain,
...
 				     struct task *task, uint32_t num_tasks)
 {
+	int ret;
+
 	assert(domain->ops->domain_unregister);
 
-	domain->ops->domain_unregister(domain, task, num_tasks);
+	ret = domain->ops->domain_unregister(domain, task, num_tasks);
+
+	if (!ret) {
```
Comment (jgunn0262) [inline src/include/sof/schedule/ll_schedule_domain.h:151]: ditto, I dont understand this logic

**Review by jgunn0262 — CHANGES_REQUESTED** [review]
Sorry @keyonjie I really dont understand what you are fixing here.

File: src/include/sof/schedule/ll_schedule_domain.h (hunk 4 above)
Comment (keyonjie) [reply src/include/sof/schedule/ll_schedule_domain.h:128]: > I dont understand why we are increasing ref counts if registration fails ?

ret == 0 means succeed.

**Comment by keyonjie** [comment]
> Sorry @keyonjie I really dont understand what you are fixing here.

This is aim to fix https://github.com/thesofproject/sof/issues/3947 https://github.com/thesofproject/sof/issues/3949 https://github.com/thesofproject/sof/issues/3950.

File: src/schedule/dma_single_chan_domain.c (hunk 2 above)
Comment (keyonjie) [reply src/schedule/dma_single_chan_domain.c:388]: > There are a lot more error paths now. This likely means more cause for failure and would be good to see this when debugging in the logs.

I just use the returned value to check if the unregistering is success or not for the subsequent task/client status update, so only using the same '-EINVAL' to denote this at the moment. We can add more debugging logs later if we do need to debug this part.

**Comment by lgirdwood** [comment]
> > Sorry @keyonjie I really dont understand what you are fixing here.
> 
> This is aim to fix #3947 #3949 #3950.

@keyonjie I think @jgunn0262 means this is not clear in the commit message. i.e the commit message should explain the bug and why this PR fixes the bug,

File: src/include/sof/schedule/ll_schedule_domain.h (hunk 3 above)
Comment (keyonjie) [reply src/include/sof/schedule/ll_schedule_domain.h:49]: > This is confusing - clients should be renamed to cores.

yes, let me change them.

**Comment by keyonjie** [comment]
> > > Sorry @keyonjie I really dont understand what you are fixing here.
> > 
> > 
> > This is aim to fix #3947 #3949 #3950.
> 
> @keyonjie I think @jgunn0262 means this is not clear in the commit message. i.e the commit message should explain the bug and why this PR fixes the bug,

Got it. Basically the num_clients was not used currently, we wanted to use it for both num_registered_cores and num_enabled_cores, with that @slawblauciak observed it may be changed to '-1' when component/pipeline is asked for running on a slave core. 

@slawblauciak provided a fix here: https://github.com/thesofproject/sof/pull/4088, but we should really remove this mess to avoid encountering more similar issues.

**Comment by keyonjie** [comment]
@zrombel @slawblauciak @mwasko can you please help to check if this looks good to you?

**Review by lyakh — CHANGES_REQUESTED** [review]
This PR really has to explain what and why it changes...

File: src/schedule/dma_multi_chan_domain.c [hunk 6]
```diff
@@ -236,9 +237,11 @@ static void dma_multi_chan_domain_unregister(struct ll_schedule_domain *domain,
 			else if (!dma_domain->channel_mask[i][core])
 				dma_multi_chan_domain_irq_unregister(
 						dma_domain->arg[i][core]);
-			return;
+			return 0;
 		}
 	}
+
+	return -EINVAL;
```
[the remark this answers is not in the document]
Comment (keyonjie) [reply src/schedule/dma_multi_chan_domain.c:244]: yes, it could be either, so I use '-EINVAL' here.

File: src/schedule/dma_single_chan_domain.c [hunk 7]
```diff
@@ -370,27 +371,29 @@ static void dma_single_chan_domain_unregister(struct ll_schedule_domain *domain,
 
 	/* check if task should be unregistered */
 	if (!pipe_task->registrable)
-		return;
+		return -EINVAL;
```
[the remark this answers is not in the document]
Comment (keyonjie) [reply src/schedule/dma_single_chan_domain.c:374]: yes, let me make it consistent with the register() part.

File: src/schedule/dma_single_chan_domain.c (hunk 2 above)
Comment (keyonjie) [reply src/schedule/dma_single_chan_domain.c:388]: Makes sense, let me change.

File: src/schedule/ll_schedule.c [hunk 8]
```diff
@@ -94,13 +94,40 @@ static void schedule_ll_task_update_start(struct ll_schedule_data *sch,
...
+	list_item_del(&task->list);
+
+	/* the task finished, decrease the count */
+	atomic_sub(&sch->domain->total_num_tasks, 1);
+
+	/* decrease task number of the core */
+	atomic_sub(&sch->num_tasks, 1);
+
+	/* the last task of the core, unregister the client/core */
+	if (!atomic_read(&sch->num_tasks) &&
```
[the remark this answers is not in the document]
Comment (keyonjie) [reply src/schedule/ll_schedule.c:110]: as the lock is hold by the caller, so even the atomicity is broken we are still fine, I change it for readability improvement, otherwise we have to use this as the atomic_xx() returns the original value:

```
x = atomic_sub(y);
if (!(x-1))
```

File: src/schedule/timer_domain.c [hunk 9]
```diff
@@ -192,14 +192,16 @@ static void timer_domain_unregister(struct ll_schedule_domain *domain,
 
 	/* tasks still registered on this core */
 	if (!timer_domain->arg[core] || num_tasks)
-		return;
+		return -EINVAL;
```
[the remark this answers is not in the document]
Comment (keyonjie) [reply src/schedule/timer_domain.c:195]: yes.

File: src/schedule/ll_schedule.c [hunk 10]
```diff
@@ -94,13 +94,40 @@ static void schedule_ll_task_update_start(struct ll_schedule_data *sch,
...
+	    sch->domain->registered[cpu_get_id()]) {
+		sch->domain->registered[cpu_get_id()] = false;
+		atomic_sub(&sch->domain->registered_cores, 1);
+
+		/* no client anymore, clear the domain */
+		if (!atomic_read(&sch->domain->registered_cores))
+			domain_clear(sch->domain);
```
[the remark this answers is not in the document]
Comment (keyonjie) [reply src/schedule/ll_schedule.c:117]: good point.
the domain_clear() clears interrupts, so it should be called only at interrupt handler, should not call it here, or in domain_unregister(), or domain_disable().

Let me refine this part also. Thanks!

**Comment by lgirdwood** [comment]
@keyonjie before I review, does this fix the DSM issue ?

**Comment by keyonjie** [comment]
> @keyonjie before I review, does this fix the DSM issue ?

I would say it improves a lot for multi-core support, for the DSM issue, need @zrombel 's double check.

Without this PR, we see many errors in multi-core validation, see it here: https://sof-ci.sh.intel.com/#/result/planresultdetail/3832

I am waiting for the validation result with this PR applied here:
https://sof-ci.sh.intel.com/#/result/planresultdetail/3834

**Comment by keyonjie** [comment]
@lgirdwood the result is really good according to the report https://sof-ci.sh.intel.com/#/result/planresultdetail/3834.

some conflict with the latest main, let me rebase.

**Comment by gkbldcig** [comment]
Can one of the admins verify this patch?

**Comment by keyonjie** [comment]
SOFCI TEST

**Comment by zrombel** [comment]
I run some stress on this PR, a it seems that stream stall problem https://github.com/thesofproject/sof/issues/4101 is fixed!
There were no stream stalls in 200 iterations in DSM multicore tests.
No I can only see sporadic glitch in recorded file. 
Glitch can be seen in the beginning of the stream, or in whole stream like this shown below:
image

But this is reported here: https://github.com/thesofproject/sof/issues/4052

**Review by zrombel — APPROVED** [review]

File: src/schedule/ll_schedule.c (hunk 8 above)
[the remark this answers is not in the document]
Comment (keyonjie) [reply src/schedule/ll_schedule.c:111]: > I don't think it improves readability at all. It adds confusion why a wrong use of an API is allowed. Either we're protected by some external locking, then we should remove `atomic_t` and just make it an `int` and make sure it's consistently protected, or we use `atomic_t` and we understand why we need it and we use it correctly.

We don't have to make sure the atomicity, but we still need the make them as volatile to make sure not reading them from cache as we need sync from L1 cache of different Cores, @lyakh what do you suggest here?

**Comment by keyonjie** [comment]
@slawblauciak reschedule part refining added on top, please help to review.

**Comment by keyonjie** [comment]
SOFCI TEST

**Comment by keyonjie** [comment]
@lgirdwood This PR will address > 90% failed cases reported here: http://sof-ci.sh.intel.com/#/result/planresultdetail/3868 and some other multi-core related issues observed by slim driver, I think we need this for 1.8/

**Review by slawblauciak — APPROVED** [review]

File: src/schedule/ll_schedule.c (hunk 8 above)
[the remark this answers is not in the document]
Comment (lgirdwood) [reply src/schedule/ll_schedule.c:111]: IIRC the atomic types are used as there is or was a need to add tasks from within other tasks and the scheduler lock was already held at this point. Not sure if this is the case today.
@lyakh the Zephyr timer domain work you are doing **should** be a lot simpler wrt to locking/atomic since this is all done by Zephyr. We should see a significant reduction in complexity.

**Review by lgirdwood — COMMENTED** [review]
Is this intended for rc2 ? Are we happy with validation on TGL 12 ?

**Comment by keyonjie** [comment]
> Is this intended for rc2 ? Are we happy with validation on TGL 12 ?

Yes about the intending for rc2.
For TGL 12 validation, @slawblauciak @mwasko  can you help to cherry-pick related commits (there could be conflicts so other related ones together may needed) to the 12 branch? or do you prefer to create a new branch for the release?

**Comment by lgirdwood** [comment]
@keyonjie can you check the zephyr build CI.

**Comment by marc-hb** [comment]
I've seen similar issues in other PRs, hopefully just a temporary glitch on llvm.org. I re-ran the job and it passed.

https://github.com/thesofproject/sof/pull/4089/checks?check_run_id=2554961695
```
Err:7 http://apt.llvm.org/focal llvm-toolchain-focal-12/main i386 Packages
  File has unexpected size (2110 != 2108). Mirror sync in progress? [IP: 151.101.250.49 443]
```

**Comment by marc-hb** [comment]
```
Err:7 http://apt.llvm.org/focal llvm-toolchain-focal-12/main i386 Packages
  File has unexpected size (2110 != 2108). Mirror sync in progress? [IP: 151.101.250.49 443]
```

I just removed the entire dependency on llvm.org in #4182 , please review.

**Comment by keyonjie** [comment]
> @keyonjie can you check the zephyr build CI.

Yes, as @marc-hb mentioned that looks a common issue for PRs, @marc-hb just helped addressed it.

**Review by lgirdwood — APPROVED** [review]
