### PR TITLE
idc: refactor sending in blocking mode

### LINKED ISSUE #1503: [BUG][WHL] Multi Kernel Error -62 on trigger_pause IPC
**Describe the bug**
After sending trigger_pause FW replies with error: -62

**To Reproduce**
Create playback pipeline on Core 1, capture pipeline on Core 0. Start Streams, play audio, Pause Streams.
Python test case: 
- tests/sof/fw_02_pass_through/test_17_ptp_simple_loopback_multi_kernel_core.py 
- with modification on pipelines core indexes
- playback-iterations parameter 100

**Reproduction Rate**
20%

**Environment**
Tested with python tests

### PR DESCRIPTION
**Pull request by tlauda**
Refactors IDC sending in blocking mode to
utilize DONE interrupt instead of manually
polling for DONE bit. It allows for removal
of spinlock, which prevented longer IDC
timeouts.

Fixes #1503.

Signed-off-by: Tomasz Lauda <tomasz.lauda@linux.intel.com>

### CODE REVIEW

File: src/include/sof/idc.h [hunk 1]
```diff
@@ -35,8 +36,8 @@
 /** \brief IDC send non-blocking flag. */
 #define IDC_NON_BLOCKING	1
 
-/** \brief IDC send timeout in cycles. */
-#define IDC_TIMEOUT	800000
+/** \brief IDC send timeout in microseconds. */
+#define IDC_TIMEOUT	10000
 
 /** \brief IDC task deadline. */
 #define IDC_DEADLINE	100
```
Comment (jajanusz) [inline src/include/sof/idc.h]: `IDC_TIMEOUT` is in microseconds, this one is us or cycles?

Comment (tlauda) [reply src/include/sof/idc.h]: us

**Comment by jajanusz** [comment]
SOFCI TEST

**Comment by tlauda** [comment]
SOFCI TEST

**Comment by tlauda** [comment]
@xiulipan I think there is something wrong with the device test environment.

**Comment by michalgrodzicki** [comment]
@xiulipan  could you provide more details about jenkins CI issue?
