### PR TITLE
init: zephyr: Fix memory leak during secondary core init

### LINKED ISSUE #9005: [BUG] Memory Leak on Secondary Core Power Cycle
**Describe the bug**
A regression has been detected in the power flow code, introduced by commit 5f1e6900d9ecf77c78e16b4d8fedb8a9a669ee49, causing a memory leak on multicore platforms using Zephyr as the RTOS. The issue manifests as repeated memory allocations for secondary cores that are not freed upon powering down. This results in a gradual depletion of available memory, eventually leading to a firmware exception notification from the DSP. The problem was first identified on the LunarLake platform and is likely to affect other multicore platforms due to the shared power flow code.

**To Reproduce**
1. Power up all secondary cores of the DSP on a multicore platform (e.g., LunarLake).
2. Power down all the secondary cores.
3. Repeat steps 1 and 2 until a firmware exception notification is received from the DSP.

**Reproduction Rate**
The issue is reproducible 10/10 times when following the above manual sequence on the LunarLake platform. The reproduction rate is expected to be consistent across other multicore platforms using Zephyr as the RTOS.

**Expected behavior**
Upon powering down the secondary cores, the system should either release the resources allocated during the power-up phase or ensure that they are reused during the next power-up.

**Impact**
This memory leak is a critical issue that leads to resource exhaustion and potential DSP panic after an extended number of power cycles. It is a showstopper for the reliability and stability of the DSP on all affected multicore platforms.

**Environment**
    * SOF: main
    * Platform: LunarLake (and potentially all multicore platforms using Zephyr RTOS)

### PR DESCRIPTION
**Pull request by tmleman**
This patch refines the initialization process for secondary cores in a multicore environment when using Zephyr as the RTOS. The patch introduces a `check_restore` function specifically for Zephyr, which checks if basic core structures (IDC, notifier, schedulers) have been previously allocated and are still present in memory, indicating that the system is not undergoing a cold boot.

By adding this check, the system avoids unnecessary re-allocation of these structures during the power-up sequence of secondary cores, effectively preventing the memory leak observed during repeated power cycle tests.

fix #9005

### CODE REVIEW

**Review by softwarecki — APPROVED** [review]

File: src/init/init.c [hunk 1]
```diff
@@ -87,7 +87,27 @@ static inline void lp_sram_unpack(void)
...
+	struct idc *idc = *idc_get();
+	struct notify *notifier = *arch_notify_get();
+	struct schedulers *schedulers = *arch_schedulers_get();
+
+	/* check whether basic core structures has been already allocated. If they
+	 * are available in memory, it means that this is not cold boot and memory
+	 * has not been powered off.
+	 */
+	if (!idc || !notifier || !schedulers)
+		return 0;
```
Comment (lyakh) [inline src/init/init.c:103]: even though this function returns `int` (can we change it to return `bool`?) still `return idc && notifier && schedulers;` should still work. Also, seeing this check raises a question for me - what if some of these pointers are `NULL`? I think the answer is that this isn't possible, right? If any of these allocations fail initially, the whole initialisation fails, so we never reach this point. That means, that checking just one of these pointers should be enough: if one of them is set, all the others must be set too?

**Review by kv2019i — APPROVED** [review]

File: src/init/init.c (hunk 1 above)
Comment (tmleman) [reply src/init/init.c]: > can we change it to return `bool`?

Done

> what if some of these pointers are `NULL`? I think the answer is that this isn't possible, right?

True, initialization should fail at the start (first initialization). It's definitely the case with the scheduler.

> that checking just one of these pointers should be enough: if one of them is set, all the others must be set too?

I think one would be enough, but more is better, right?

Comment (lyakh) [reply src/init/init.c]: > I think one would be enough, but more is better, right?

@tmleman why and how? *Maybe* it is better, or maybe not. If you claim, that it's better, then I'd like an explanation of why and how and a proper handling of it. So, if you detect that one of them is `NULL` and others aren't, this can mean that the initialisation code got broken. So I would expect an appropriate handling of such a case. Currently a case of some `NULL` and some non-`NULL` seems to indicate some inconsistent state and we leave it at it. A better solution could be adding an explicit "initialisation complete" flag and checking it, instead of using some implicit indicators

File: src/init/init.c [hunk 2]
```diff
@@ -87,7 +87,24 @@ static inline void lp_sram_unpack(void)
 
 #if CONFIG_MULTICORE
 
-#ifndef __ZEPHYR__
+#ifdef __ZEPHYR__
+
+static bool check_restore(void)
```
Comment (lyakh) [inline src/init/init.c:92]: sorry, I didn't say this explicitly - you have to change this function's prototype for non-Zephyr case in line 109 below too then

File: src/init/init.c [hunk 3]
```diff
@@ -87,7 +87,24 @@ static inline void lp_sram_unpack(void)
...
+	 * has not been powered off.
+	 */
+	return !!idc && !!notifier && !!schedulers;
+}
+
+static inline int secondary_core_restore(void) { return 0; };
+
+#else
 
 static int check_restore(void)
```
Comment (lyakh) [inline src/init/init.c:109]: this one has to be changed too

File: src/init/init.c (hunk 1 above)
Comment (tmleman) [reply src/init/init.c]: > this can mean that the initialisation code got broken.

I think you have given the best answer to the question why more is better.

Perhaps it would be helpful to add a piece of code that would handle the case where only part of the components has been initialized. As for the idea with the variable (flag) that would indicate that the initialization has been completed, I don't see the value in it at the moment. What would be the difference compared to checking the state of just one component, for example, one that is initialized last?

At this moment, fixing regressions introduced by the previous refactor is a higher priority for me than starting another one.

**Review by dnikodem — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]
