### PR TITLE
EQ FIR: Bug fix for HiFi3 optimized implementation

### LINKED ISSUE #1625: [BUG] FIR EQ distorts
**Describe the bug**

The FIR EQ component distorts really bad at higher frequencies when built with xt-xcc for HiFi3 platforms (APL). The gcc build works OK. The test filter response is flat and therefore the distortion is not due to amplification. I used topology sof-apl-eq-pcm512x.tplg and created a custom version that contains only FIR (removed IIR). Similar IIR only pipeline works OK as both gcc and xt-xcc build. Therefore the bug must be in HiFi3 FIR version.

The issue looks like internal aliasing. The output spectra looks like the FIR decimates internally by 2 that is clearly a bug. (I haven't tested HiFi EP version).

**To Reproduce**
Playback audio.

**Reproduction Rate**
Always.

**Expected behavior**

**Impact**
No Distortion.

**Environment**
1) Branch name and commit hash of 3 repositories: sof (firmware), linux (kernel driver) and soft (tools & topology).
2) Name of the topology file
3) Name of the platform(s) on which the bug is observed.
4) Reproducibility Rate. If you can only reproduce it randomly, it’s useful to report how many times the bug has been reproduced vs. the number of attempts it’s taken to reproduce the bug.

**Screenshots or console output**
A measured distortion plot with sof_test_perf tool. Normally the distortion curves are fairly constant vs. frequency. In this case distortion jumps after 400 Hz.
UP2 playback s16_THDNF

Please also include the relevant sections from the firmware log and kernel log in the report (and attach the full logs for complete reference). Kernel log is taken from *dmesg* and firmware log from *sof-logger*. See https://thesofproject.github.io/latest/developer_guides/debugability/logger/index.html

### PR DESCRIPTION
**Pull request by singalsu**
This patch fixes two similar mistakes from all the s16/s24/s32 dual
sample computing FIR core that was introduced in a previous update.
The FIR processing frames count processed double amount of samples
in buffer that corrupted FIR delay line and also the output write
to component sink buffer swapped two successive samples within one
channel.

The filter cores for s16 and s24 were simplified a bit since they can
use single output write pointer.

The FIR header file used wrong xtensa header file for HiFi2 while
it should have been for hifi3. Though no issues were observed due to
this mistake.

A check for frames count greater than zero was added into the copy()
function for extra safety. Also the return value from
comp_get_copy_limits() is not checked since the function always
returns zero.

Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>

[ edit: @jajanusz ]
Fixes #1625

### CODE REVIEW

**Comment by singalsu** [comment]
Totally stupid mistakes by me in previous commit for this module... sorry. This confirms that "sounds about right" testing is not enough. I can't run testbench for this component but the objective audio quality measurement tool for e.g. line-out in my other PR can catches quality issues like this.

**Comment by singalsu** [comment]
This fixes SOF issue #1625.

**Comment by tlauda** [comment]
@singalsu Could you resolve the conflicts?

**Comment by jajanusz** [comment]
@singalsu ping

File: src/audio/eq_fir/eq_fir.c [hunk 1]
```diff
@@ -643,26 +643,21 @@ static int eq_fir_copy(struct comp_dev *dev)
...
+	comp_get_copy_limits(dev, &cl);
 
 	/* Check if number of frames to process if it is odd. The
 	 * optimized FIR function to process even number of frames
 	 * is lower load than generic version. In that case process
 	 * one frame with generic FIR and the rest with even frames
 	 * number FIR version.
 	 */
-	if (cl.frames & 0x1) {
+	if (cl.frames > 0 && cl.frames & 0x1) {
```
Comment (lgirdwood) [inline src/audio/eq_fir/eq_fir.c]: No need to check > 0 since you are checking if LSB is set.

Comment (singalsu) [reply src/audio/eq_fir/eq_fir.c]: Yep, you are right.

**Comment by singalsu** [comment]
Updated but I'll still wait to see what is the code scan issue.

**Comment by singalsu** [comment]
SOFCI TEST

File: src/audio/eq_fir/eq_fir.c (hunk 1 above)
Comment (singalsu) [reply src/audio/eq_fir/eq_fir.c]: Done now

**Comment by singalsu** [comment]
@xiulipan @zrombel Is the error above from sof-ci/jenkins/pr-device-test "On-device Test Failed:CML_RVP_HDA:deployfail ICL_RVP_HDA:deployfail CFL_RVP_HDA:timeout" something caused by my PR or a fail in CI system?

**Comment by jajanusz** [comment]
> @xiulipan @zrombel Is the error above from sof-ci/jenkins/pr-device-test "On-device Test Failed:CML_RVP_HDA:deployfail ICL_RVP_HDA:deployfail CFL_RVP_HDA:timeout" something caused by my PR or a fail in CI system?

More likely ci fail, cos it's like this in other PRs also

**Comment by singalsu** [comment]
SOFCI TEST
