### PR TITLE
module_adapter: Modify reset API

### LINKED ISSUE #6034: [BUG] Volume DSP Panic on IPC response timeout, DSP Panic notification
**Describe the bug**

ERROR:Exception DspPanicError occurred at 'C:\\work\\tools\\cavs_scripts-py\\utilities\\ipc_driver.py':171 DSP Panic on IPC response timeout! 0x00000005 0x0DEAD006 0x00004000
ERROR:Exception DspPanicError occurred at 'C:\\work\\tools\\cavs_scripts-py\\utilities\\ipc_driver.py':171 DSP Panic notification received: SOF_IPC_PANIC_EXCEPTION 0x00000005 0x0DEAD006 0x00004000

Bug occurs with a playback iteration greater than 1

Bug was found in:
TestVolumeSimple8000Hz16b16b1ch
TestVolumeSimple8000Hz24b32b4ch
TestVolumeSimple48000Hz32b32b8ch
TestVolumeChangeInMiddle8000Hz32b32b4ch
TestVolumeChangeInMiddle48000Hz32b32b4ch
TestVolumeMultipleChanges8000Hz24b32b2ch
TestVolumeMultipleChanges48000Hz24b32b2ch
TestVolumeMute8000Hz32b32b8ch
TestVolumeMute48000Hz32b32b8ch
TestVolumeInitialRampSimple8000Hz24b32b4ch
TestVolumeInitialRampSimple48000Hz32b32b2ch
TestDiffVolumeChangeInChannels8000Hz24b32b4ch
TestDiffVolumeChangeInChannels48000Hz32b32b4ch

**Topology**
```
TestVolumeSimple

                +--------------------------------+
    +------+    | +---+  +- -+  +---+  +-------+ |
    | Host |----->|Buf|->|Vol|->|Buf|->|SSP Dai|---+
    +------+    | +---+  +-- +  +---+  +-------+ | |
                +--------------------------------+ |
                                                   |
                +------------------+               |
    +------+    | +---+  +-------+ |               |
    | Host |<-----|Buf|<-|SSP Dai|<----------------+
    +------+    | +---+  +-------+ |
                +------------------+

```
Description:
Simultaneous playback and capture on external loopback (same SSP) with signal amplitude verification.
Playback pipeline contains volume component.
Volume gain is explicitly set to 1 before playback starts.

**To Reproduce**
Run tests with diagnostic driver 
with argument: --playback_iterations=2

03_00_TestVolumeSimple8000Hz16b16b1ch

**Reproduction Rate**
100%

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * SOF BRANCH: main HASH: ea72e3e97e10acb27d02c3692b006c4f66fabfe4
2) Name of the platform(s) on which the bug is observed.
    * Platform: TGL RVP

the last working and not working commit:  ebc222dab56868ea3cb0d5abec5057990eae6bb9

**Logs**
[DSPPanicVolume.zip](https://github.com/thesofproject/sof/files/9157675/DSPPanicVolume.zip)

### PR DESCRIPTION
**Pull request by ranj063**
Modify the definition of the reset API in the module adapter interface
to make sure that it should reset the module state back to
MODULE_INITIALIZED and free all memory that was allocated during the
prepare() callback. With this change, stopping and restarting streams
will always be guaranteed to invoke the module's prepare() callback.
Also, fix the passthrough and cadence codec implementation to follow the
new definition.

Fixes #6034

### CODE REVIEW

**Comment by ranj063** [comment]
@LaurentiuM1234 @johnylin76 @dbaluta @lyakh Could you please take a look at this one? I will follow up this one with the remove of the module states after the issue #6034 is fixed.

File: src/audio/module_adapter/module/generic.c [hunk 1]
```diff
@@ -283,7 +283,7 @@ int module_reset(struct processing_module *mod)
 	/* module resets itself to the initial condition after prepare()
 	 * so let's change its state to reflect that.
```
Comment (johnylin76) [inline src/audio/module_adapter/module/generic.c:284]: this comment should be corrected as well

**Comment by johnylin76** [comment]
I am in favor of this fix to align the prepare/reset flow between module API and component(module_adapter) API.

Could you create an github issue for this? It will be helpful for informing our collaborative partners who own the module as well (e.g. dts, waves), and easier to track. Even better to make the track list for all existing modules for adapting the new flow in that issue.

By the way, after this fix, init_process() in module API looks redundant to me as the original purpose is to align API for Windows modules. But actually (not 100% sure) we could regard prepare() as init_process() for Wndows modules.

**Review by lyakh — APPROVED** [review]
looks good to me but I certainly cannot comment on the validity of this change WRT the API conformance

**Review by LaurentiuM1234 — APPROVED** [review]

**Comment by lgirdwood** [comment]
> Could you create an github issue for this? It will be helpful for informing our collaborative partners who own the module as well (e.g. dts, waves), and easier to track. Even better to make the track list for all existing modules for adapting the new flow in that issue.

The intention for MTL on wards would be that all the 3rd parties would use the same programming API that they have used on Windows. e.g. they can use either the C or C++ module API for all OSes and it would be CPU vendor agnostic for them too.

File: src/audio/module_adapter/module/generic.c (hunk 1 above)
Comment (ranj063) [reply src/audio/module_adapter/module/generic.c]: done, thanks!

**Comment by johnylin76** [comment]
> > Could you create an github issue for this? It will be helpful for informing our collaborative partners who own the module as well (e.g. dts, waves), and easier to track. Even better to make the track list for all existing modules for adapting the new flow in that issue.
> 
> The intention for MTL on wards would be that all the 3rd parties would use the same programming API that they have used on Windows. e.g. they can use either the C or C++ module API for all OSes and it would be CPU vendor agnostic for them too.

I think I got your point, although I don't have the information that whether all of our collaborative 3p vendors have the support on Windows. I think yes for Waves, how about the DTS module (Xperi)?

> EDIT: @johnylin76 I wont merge until you've had a chance to review and test.

I had reviewed and the comment is addressed. Thanks.
Honestly, I don't think I am able to test this because both Waves and DTS module require modifications of their wrapper code to align the new flow, otherwise the module won't work or has potential risk of OOM. And that's the reason I recommend to create a github issue for tracking.
It is also fine to me to merge first and request Waves and DTS for the modification later, since this is on mainstream which won't affect the firmware build for production. We can merge it back to production branches until they finish the modification to align the new flow.
@lgirdwood WDYT? Should this fix be blocked until all existing modules are aligned on mainstream, or it's fine to do the alignment later? (Either is fine to me)

**Comment by lgirdwood** [comment]
> It is also fine to me to merge first and request Waves and DTS for the modification later, since this is on mainstream which won't affect the firmware build for production. We can merge it back to production branches until they finish the modification to align the new flow.
> @lgirdwood WDYT? Should this fix be blocked until all existing modules are aligned on mainstream, or it's fine to do the alignment later? (Either is fine to me)

Sorry for the delay, the stable-v2.3 branch has been created so we have 3 months to align the remaining users to the uopdated flow. @ranj063 fyi.
