### PR TITLE
smart amp: fix alignment warning of data passesed in

### LINKED ISSUE #3244: [BUG]Build error with GCC9 in smart_amp_test.c
**Describe the bug**
A new build bug when using GCC9
```
/home/sof/work/sof.git/src/audio/smart_amp_test.c: In function 'smart_amp_set_config':
/home/sof/work/sof.git/src/audio/smart_amp_test.c:93:39: error: taking address of packed member of 'struct sof_abi_hdr' may result in an unaligned pointer value [-Werror=address-of-packed-member]
   93 |  cfg = (struct sof_smart_amp_config *)cdata->data->data;
```

**To Reproduce**
```
docker pull thesofproject/sof:20200728
docker tag thesofproject/sof:20200728 sof
./scripts/docker-run.sh ./scripts/xtensa-build-all.sh cnl
```

**Reproduction Rate**
10/10

**Expected behavior**
The GCC build should pass

### PR DESCRIPTION
**Pull request by lgirdwood**
Fix GGC warning on aligned packed data.

Signed-off-by: Liam Girdwood <liam.r.girdwood@linux.intel.com>

Fixes #3244

### CODE REVIEW

File: src/audio/smart_amp_test.c [hunk 1]
```diff
@@ -90,7 +90,7 @@ static int smart_amp_set_config(struct comp_dev *dev,
 	size_t bs;
 
 	/* Copy new config, find size from header */
-	cfg = (struct sof_smart_amp_config *)cdata->data->data;
+	cfg = ASSUME_ALIGNED(cdata->data->data, 4);
```
Comment (plbossart) [inline src/audio/smart_amp_test.c:93]: is this 4 words or 4 bytes? Maybe sizeof()?

Also typo in commit title

Comment (mmaka1) [reply src/audio/smart_amp_test.c:93]: Yes, sizeof(uint32_t) would be more readable. Defining #define member_size(type, member) sizeof(((type *)0)->member) and using as member_size(sof_smart_amp_config, size) could be even better.

Comment (lgirdwood) [reply src/audio/smart_amp_test.c]: Fixed.
