### PR TITLE
pipeline: atomic schedule of connected pipelines

### LINKED ISSUE #2736: [BUG] lost samples at beginning while stress demux
**Describe the bug**
Lack of samples in demux tests at the beginning in recorded file. Topology scheme below.
Demux in this tests using masking will "redirect" odd channels to dai1 and even channels to dai2.

Topology:
image

**To Reproduce**
Python tests with slim driver on any audio format with playback iterations=100:
test_01_demux_simple_playback.py

**Reproduction Rate**
~16% (when 100 playback iterations)

**Environment**
Windows python tests
FW: b4e8b1e4
Checked on WHL and TGL platform.

Below example for 4ch, 48k, 32/32
**Screenshots or console output**
image

Here is output on dai2 - as expected:
image

**Logs:**
[dma_trace_1_sink.log](https://github.com/thesofproject/sof/files/4444100/dma_trace_1_sink.log)

### PR DESCRIPTION
**Pull request by tlauda**
Implements atomic scheduling of connected pipelines that
supposed to be triggered at the same time. If the trigger
is propagated to the connected pipelines, then the expectation
is that they should be started at the same system tick.
Otherwise it might potentially lead to losing some samples
at the beginning for one of the pipes.

Signed-off-by: Tomasz Lauda <tomasz.lauda@linux.intel.com>

Fixes #2736.

### CODE REVIEW

File: src/audio/pipeline.c [hunk 1]
```diff
@@ -690,6 +677,43 @@ static int pipeline_xrun_handle_trigger(struct pipeline *p, int cmd)
...
+		p = ctx->pipelines[i];
+		if (!p)
+			continue;
+
+		switch (cmd) {
+		case COMP_TRIGGER_PAUSE:
+		case COMP_TRIGGER_STOP:
+		case COMP_TRIGGER_XRUN:
+			pipeline_schedule_cancel(p);
+			p->status = COMP_STATE_PAUSED;
```
Comment (paulstelian97) [inline src/audio/pipeline.c:699]: I assume p is only ever written to on this core? The outside irq_local_disable/enable is really to prevent being interrupted while walking the pipelines array?

Comment (tlauda) [reply src/audio/pipeline.c:699]: Yes, exactly.

Comment (paulstelian97) [reply src/audio/pipeline.c:699]: Just wanted to ensure all assumptions behind the code are correct.

File: src/audio/pipeline.c [hunk 2]
```diff
@@ -125,6 +125,9 @@ struct pipeline_walk_context {
 	void *comp_data;
 	void (*buff_func)(struct comp_buffer *, void *);
 	void *buff_data;
+	/**< pipelines to be scheduled after trigger walk */
+	struct pipeline *pipelines[PPL_MAX_CONNECTED];
+	uint32_t pipeline_count;
```
Comment (lgirdwood) [inline src/audio/pipeline.c:130]: list ?

Comment (tlauda) [reply src/audio/pipeline.c]: Done.

**Comment by lgirdwood** [comment]
Jenkins known issues.
