### PR TITLE
mixer: reset additional check is only needed for playback

### LINKED ISSUE #3096: [BUG] Firmware returns an error on TplgCompFree on test with mixer on capture pipline.
**Describe the bug**
When running simultaneous 3 x capture and 3 x playback on loopback signal on each SSP's with mixer component on one of the capture pipeline, firmware returns an error on TplgCompFree. Error is visible since commit a21cba16d99d642dd55fd3ebdd04201fb1017c40 which check state != COMP_STATE_READY in comp_free.
When sending ipc TplgCompFree on mixer component firmware return -22.

**Topology**
```
+-------------------------+
| +----+   +----+   +---+ |              +----+
| |Host|-->|Buff|-->|Dai| +------------->|SSPx|-----------------+
| +----+   +----+   +---+ |              +----+                 |
+-------------------------+                                     |
                                                                |
+-------------------------+                                     |
| +----+   +----+   +---+ |              +------+               |
| |Host|-->|Buff|-->|Dai| +------------->|SSPx+1|------------+  |
| +----+   +----+   +---+ |              +------+            |  |
+-------------------------+                                  |  |
                                                             |  |
+-------------------------+                                  |  |
| +----+   +----+   +---+ |              +------+            |  |
| |Host|-->|Buff|-->|Dai| +------------->|SSPx+2|---------+  |  |
| +----+   +----+   +---+ |              +------+         |  |  |
+-------------------------+                               |  |  |
                                                          |  |  |
                                                          |  |  |
                                                          |  |  |
                                                          |  |  |
                                    +----------------+    |  |  |
                                    | +----+   +---+ |    |  |  |
                        +-----------+ |Buff|<--|Dai| <----+  |  |
                        |           | +----+   +---+ |       |  |
                        |           +----------------+       |  |
                        |                                    |  |
                        |           +----------------+       |  |
                        |           | +----+   +---+ |       |  |
                        | +---------+ |Buff|<--|Dai| <-------+  |
                        | |         | +----+   +---+ |          |
                        | |         +----------------+          |
                        | |                                     |
+-----------------------v-v-----------------------+             |
| +----+    +----+    +-----+    +----+   +-----+ |             |
| |Host|<---|Buff|<---|Mixer|<---|Buff|<--| Dai |<--------------+
| +----+    +----+    +-----+    +-- -+   +-----+ |
+-------------------------------------------------+
```
**To Reproduce**
Run one of slim driver python tests from file:
test_01_mixer_capture.py

**Reproduction Rate**
100 %

**Expected behavior**
The released components should be in proper state and released without errors.

**Environment**
WHL RVP

Commit: 20ab16c36ece474fc3a55e87d7daa945bdcc9089 from SOF master branch.

**Example logs**
[dma_trace_1.log](https://github.com/thesofproject/sof/files/4829524/dma_trace_1.log)

[2020_06_25_08_03_00.zip](https://github.com/thesofproject/sof/files/4829519/2020_06_25_08_03_00.zip)

### PR DESCRIPTION
**Pull request by tlauda**
Limits additional check in mixer_reset to playback streams only.
For mixer in capture streams the request will always come from downstream,
which means that source components will always be in state >
COMP_STATE_READY. Checking sink component also doesn't make,
because it's the source of the request. The logic is now similar
to the mixer_trigger, where for capture streams we also don't require
additional checks.

Signed-off-by: Tomasz Lauda <tomasz.lauda@linux.intel.com>

### CODE REVIEW

**Comment by lgirdwood** [comment]
Jenkins usual issues.

File: src/audio/mixer.c [hunk 1]
```diff
@@ -351,17 +351,21 @@ static int mixer_copy(struct comp_dev *dev)
...
-		/* only mix the sources with the same state with mixer*/
-		if (source->source->state > COMP_STATE_READY)
-			/* should not reset the downstream components */
-			return 1;
+	if (dir == SOF_IPC_STREAM_PLAYBACK) {
+		list_for_item(blist, &dev->bsource_list) {
+			source = container_of(blist, struct comp_buffer,
+					      sink_list);
+			/* only mix the sources with the same state with mixer*/
+			if (source->source->state > COMP_STATE_READY)
```
Comment (paulstelian97) [inline src/audio/mixer.c:365]: I don't like this comparison itself, although it's from preexisting code. Is there a way to make it not rely on the order in the enum itself?
