### PR TITLE
comp: return warning instead of error in comp_get_model()

### LINKED ISSUE #3068: [TGL][007-drop-stable]"error: ipc error for 0x50040000 size 124" occurred when system boot up.
**Describe the bug**
"error: ipc error for 0x50040000 size 124" occurred when system boot up. Piplines cannot work after issue happened.

**To Reproduce**
1. Boot up system.
2. Check dmesg.

**Reproduction Rate**
100%

**Expected behavior**
system boots up without any error.

**Impact**
"error: ipc error for 0x50040000 size 124" occurred when system boot up.

**Environment**
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev commit:1b2f2606
Revert 6a7c533
Revert cd0a323
FW: https://github.com/thesofproject/sof/tree/tgl-007-drop-stable commit: 3d8a0ac809
TPLG: same path as FW.  sof-tgl-sdw-max98373-rt5682-4ch.tplg rename to  sof-tgl-sdw-max98373-rt5682.tplg
platform: TGL chromebook with rt5682-max98373 sdw mode

**dmesg**
```
[    4.010819] intel-sdw intel-sdw.1: Slave status change
[    4.192153] asix 3-1.1:1.0 eth0: register 'asix' at usb-0000:00:14.0-1.1, ASIX AX88772B USB 2.0 Ethernet, 00:0e:c6:c6:86:b2
[    4.192179] usbcore: registered new interface driver asix
[    4.195196] asix 3-1.1:1.0 enx000ec6c686b2: renamed from eth0
[    4.281567] sof-audio-pci 0000:00:1f.3: Topology: ABI 3:17:0 Kernel ABI 3:17:0
[    4.294920] sof-audio-pci 0000:00:1f.3: ASoC: Parent card not yet available, widget card binding deferred
[    4.297907] sof-audio-pci 0000:00:1f.3: error: ipc error for 0x50040000 size 124
[    4.297911] sof-audio-pci 0000:00:1f.3: error: set/get ctrl ipc comp 13
[    4.297913] sof-audio-pci 0000:00:1f.3: error: kcontrol value get for widget: 13
[    4.299469] sof-audio-pci 0000:00:1f.3: codec_mask = 0x4
[    4.299472] sof-audio-pci 0000:00:1f.3: display power enable
[    4.299473] sof_sdw sof_sdw: snd_hda_codec_device_new: entry
[    4.304974] snd_hda_codec_hdmi ehdaudio0D2: hdmi: pcm_num set to 9
[    4.304977] sof-audio-pci 0000:00:1f.3: display power disable
[    4.305187] sof_sdw sof_sdw: hda_dsp_hdmi_build_controls: no PCM in topology for HDMI converter 4

[    4.305189] sof_sdw sof_sdw: hda_dsp_hdmi_build_controls: no PCM in topology for HDMI converter 5

[    4.305190] sof_sdw sof_sdw: hda_dsp_hdmi_build_controls: no PCM in topology for HDMI converter 6

[    4.305191] sof_sdw sof_sdw: hda_dsp_hdmi_build_controls: no PCM in topology for HDMI converter 7

[    4.305192] sof_sdw sof_sdw: hda_dsp_hdmi_build_controls: no PCM in topology for HDMI converter 8

[    4.305193] sof-audio-pci 0000:00:1f.3: display power enable
[    4.305197] sof-audio-pci 0000:00:1f.3: enable codec wakeup
[    4.307759] sof-audio-pci 0000:00:1f.3: disable codec wakeup
[    4.313418] sof-audio-pci 0000:00:1f.3: display power disable
[    4.314791] sof-audio-pci 0000:00:1f.3: display power enable
[    4.314795] sof-audio-pci 0000:00:1f.3: enable codec wakeup
[    4.317780] sof-audio-pci 0000:00:1f.3: disable codec wakeup
```
[dmesg.log](https://github.com/thesofproject/sof/files/4802306/dmesg.log)
[all-logger.log](https://github.com/thesofproject/sof/files/4802307/all-logger.log)

### PR DESCRIPTION
**Pull request by bkokoszx**
In comp_get_model() function we should return warning in
case not allocated model->data.

fixes #3068 

Signed-off-by: Bartosz Kokoszko <bartoszx.kokoszko@linux.intel.com>

### CODE REVIEW

File: src/audio/component.c [hunk 1]
```diff
@@ -375,6 +375,9 @@ int comp_set_model(struct comp_dev *dev, struct comp_model_data *model,
 	 * memory for whole model data
 	 */
 	if (!cdata->msg_index) {
+		if (!cdata->data->size)
```
Comment (lgirdwood) [inline src/audio/component.c:378]: Why is this valid ? Can we have an inline comment explaining why size 0 models are allowed (otherwise it can look like an erroneous check)

Comment (bkokoszx) [reply src/audio/component.c:378]: @lgirdwood 
I saw that case in #3068.
@keyonjie 
Do you know why requested data size in #3068 is equal to 0?

Comment (mmaka1) [reply src/audio/component.c:378]: If 0 is invalid size that should be responded with 0, the current path is fine (comp_alloc_model_data() but one enhancement would be useful, `if (!model->data)` error message should print the requested size to know immediately what was the reason.

Comment (mmaka1) [reply src/audio/component.c:378]: It also seems that comp_alloc_model_data() works as "realloc" (perhaps comp_realloc_model_data() would be more appropriate name). So "free" of existing model if any should be done first, then size == 0 test, so that if "null model" is provided, the previous one is freed.

Comment (bkokoszx) [reply src/audio/component.c:378]: @mmaka1 
I've updated PR. Now ```comp_free_model_data()``` is before size check and there is no ```comp_free_model_data()``` in ```comp_alloc_model_data()```

**Comment by lgirdwood** [comment]
Jenkins usual issues
