### PR TITLE
schedule: dma_multi_chan: do not skip tasks for dma_domain scheduler

### LINKED ISSUE #3802: [BUG IMX] Input/output error when mixing two streams
**Describe the bug**
Input/output error when when mixing two streams.

**To Reproduce**
$aplay -Dhw:1,0 -f S16_LE -c 2 -r 48000 -t raw /dev/urandom & aplay -Dhw:1,1 -f S16_LE -c 2 -r 48000 -t raw /dev/urandom &

**Reproduction Rate**
100%

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: 5.10
    * SOF: master
2) Name of the topology file
    * Topology: sof-imx8-wm8960-mixer.tplg, sof-imx8-cs42888-mixer.tplg, sof-imx8mp-wm8960-mixer.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform: i.MX8QXP/i.MX8QM/i.MX8MP

**Screenshots or console output**
```
root@imx8qxpc0mek:~# aplay -Dhw:1,0 -f S16_LE -c 2 -r 48000 -t raw /dev/urandom & aplay -Dhw:1,1 -f S16_LE -c 2 -r 48000 -t raw /dev/urandom &
[1] 560
[2] 561
root@imx8qxpc0mek:~# Playing raw data '/dev/urandom' : Playing raw data '/dev/urandom' : Signed 16 bit Little Endian, Signed 16 bit Little Endian, Rate 48000 Hz, Rate 48000 Hz, StereoStereo


root@imx8qxpc0mek:~# aplay: pcm_write:2061: aplay: pcm_write:2061: write error: Input/output errorwrite error: Input/output error


[1]-  Done(1)                 aplay -Dhw:1,0 -f S16_LE -c 2 -r 48000 -t raw /dev/urandom
[2]+  Done(1)                 aplay -Dhw:1,1 -f S16_LE -c 2 -r 48000 -t raw /dev/urandom
root@imx8qxpc0mek:~#
root@imx8qxpc0mek:~# ./sof-logger -t -l /lib/firmware/imx/sof/sof-imx8x.ldc 
         TIMESTAMP              DELTA C# COMPONENT          LOCATION                      CONTENT
[81523859753.437500] (             nan) c0 dai          1.2            src/audio/dai.c:847  WARN dai_copy(): Copy_bytes 0 + avail bytes 0 < period bytes 192, possible glitch
[81523860036.666672] (      283.229156) c0 dai          1.2            src/audio/dai.c:855  WARN dai_copy(): nothing to copy
[81523892089.583344] (    32052.916016) c0 buffer       3.15        src/audio/buffer.c:271  comp_update_buffer_consume(), no bytes to consume, source->comp.id = 13, source->comp.type = 5, sink->comp.id = 0, sink->comp.type = 6
[81523892409.270844] (      319.687500) c0 buffer       1.4         src/audio/buffer.c:231  comp_update_buffer_produce(), no bytes to produce, source->comp.id = 0, source->comp.type = 6, sink->comp.id = 1, sink->comp.type = 5
[81523892734.635422] (      325.364594) c0 pga          1.1   ../audio/volume/volume.c:729  volume_copy(), source_bytes = 0x0, sink_bytes = 0x0
[81523893066.562500] (      331.927094) c0 dai          1.2            src/audio/dai.c:847  WARN dai_copy(): Copy_bytes 0 + avail bytes 0 < period bytes 192, possible glitch
[81523893349.479172] (      282.916656) c0 dai          1.2            src/audio/dai.c:855  WARN dai_copy(): nothing to copy
[81523925364.114594] (    32014.634766) c0 buffer       3.15        src/audio/buffer.c:271  comp_update_buffer_consume(), no bytes to consume, source->comp.id = 13, source->comp.type = 5, sink->comp.id = 0, sink->comp.type = 6
[81523925676.041672] (      311.927094) c0 buffer       1.4         src/audio/buffer.c:231  comp_update_buffer_produce(), no bytes to produce, source->comp.id = 0, source->comp.type = 6, sink->comp.id = 1, sink->comp.type = 5
[81523926021.927094] (      345.885406) c0 pga          1.1   ../audio/volume/volume.c:729  volume_copy(), source_bytes = 0x0, sink_bytes = 0x0
[81523926353.229172] (      331.302094) c0 dai          1.2            src/audio/dai.c:847  WARN dai_copy(): Copy_bytes 0 + avail bytes 0 < period bytes 192, possible glitch
[81523926644.479172] (      291.250000) c0 dai          1.2            src/audio/dai.c:855  WARN dai_copy(): nothing to copy
[81523958758.072922] (    32113.593750) c0 buffer       3.15        src/audio/buffer.c:271  comp_update_buffer_consume(), no bytes to consume, source->comp.id = 13, source->comp.type = 5, sink->comp.id = 0, sink->comp.type = 6
[81523959075.312500] (      317.239594) c0 buffer       1.4         src/audio/buffer.c:231  comp_update_buffer_produce(), no bytes to produce, source->comp.id = 0, source->comp.type = 6, sink->comp.id = 1, sink->comp.type = 5
[81523959400.260422] (      324.947906) c0 pga          1.1   ../audio/volume/volume.c:729  volume_copy(), source_bytes = 0x0, sink_bytes = 0x0
[81523959731.562500] (      331.302094) c0 dai          1.2            src/audio/dai.c:847  WARN dai_copy(): Copy_bytes 0 + avail bytes 0 < period bytes 192, possible glitch
[81523960014.166672] (      282.604156) c0 dai          1.2            src/audio/dai.c:855  WARN dai_copy(): nothing to copy
[81523992138.333344] (    32124.166016) c0 buffer       3.15        src/audio/buffer.c:271  comp_update_buffer_consume(), no bytes to consume, source->comp.id = 13, source->comp.type = 5, sink->comp.id = 0, sink->comp.type = 6
[81523992456.979172] (      318.645844) c0 buffer       1.4         src/audio/buffer.c:231  comp_update_buffer_produce(), no bytes to produce, source->comp.id = 0, source->comp.type = 6, sink->comp.id = 1, sink->comp.type = 5
[81523992788.906250] (      331.927094) c0 pga          1.1   ../audio/volume/volume.c:729  volume_copy(), source_bytes = 0x0, sink_bytes = 0x0
[81523993112.395844] (      323.489594) c0 dai          1.2            src/audio/dai.c:847  WARN dai_copy(): Copy_bytes 0 + avail bytes 0 < period bytes 192, possible glitch
[81523993395.312500] (      282.916656) c0 dai          1.2            src/audio/dai.c:855  WARN dai_copy(): nothing to copy
[81524025452.447922] (    32057.134766) c0 buffer       3.15        src/audio/buffer.c:271  comp_update_buffer_consume(), no bytes to consume, source->comp.id = 13, source->comp.type = 5, sink->comp.id = 0, sink->comp.type = 6
[81524025764.062500] (      311.614594) c0 buffer       1.4         src/audio/buffer.c:231  comp_update_buffer_produce(), no bytes to produce, source->comp.id = 0, source->comp.type = 6, sink->comp.id = 1, sink->comp.type = 5
[81524026087.135422] (      323.072906) c0 pga          1.1   ../audio/volume/volume.c:729  volume_copy(), source_bytes = 0x0, sink_bytes = 0x0
[81524026410.312500] (      323.177094) c0 dai          1.2            src/audio/dai.c:847  WARN dai_copy(): Copy_bytes 0 + avail bytes 0 < period bytes 192, possible glitch
[81524026693.854172] (      283.541656) c0 dai          1.2            src/audio/dai.c:855  WARN dai_copy(): nothing to copy
[81524058770.000000] (    32076.146484) c0 buffer       3.15        src/audio/buffer.c:271  comp_update_buffer_consume(), no bytes to consume, source->comp.id = 13, source->comp.type = 5, sink->comp.id = 0, sink->comp.type = 6
[81524059089.895844] (      319.895844) c0 buffer       1.4         src/audio/buffer.c:231  comp_update_buffer_produce(), no bytes to produce, source->comp.id = 0, source->comp.type = 6, sink->comp.id = 1, sink->comp.type = 5
[81524059414.843750] (      324.947906) c0 pga          1.1   ../audio/volume/volume.c:729  volume_copy(), source_bytes = 0x0, sink_bytes = 0x0
[81524059736.458344] (      321.614594) c0 dai          1.2            src/audio/dai.c:847  WARN dai_copy(): Copy_bytes 0 + avail bytes 0 
```

### PR DESCRIPTION
**Pull request by iuliana-prodan**
Add a full_sync attribute to ll_schdule domain.
This is set to true, for a full synchronous dma_domain
scheduler, which is not time dependent.
By default, it is false.

In full_sync case we use the ratio between the task period
and the registrable task period to do the scheduling, not
the task.start time.

We do this because for the DMA_DOMAIN there are no guarantees
for the accuracy of the period of the registrable task
which drives the entire scheduling.

The second commit sets the full_sync attribute to true for imx platforms.

Fixes: #3802

### CODE REVIEW

File: src/include/sof/schedule/ll_schedule.h [hunk 1]
```diff
@@ -30,6 +30,8 @@ extern struct tr_ctx ll_tr;
```
Comment (dbaluta) [inline src/include/sof/schedule/ll_schedule.h:30]: @iuliana-prodan the patch looks good to me. I understand the reasons behind it. Is it possible at our current level of understanding to specify what is the difference between synchronous and full_sync?

File: src/schedule/dma_multi_chan_domain.c [hunk 2]
```diff
@@ -303,11 +304,23 @@ static bool dma_multi_chan_domain_is_pending(struct ll_schedule_domain *domain,
...
 				continue;
 
-			/* it's too soon for this task */
-			if (!pipe_task->registrable &&
-			    pipe_task->task.start >
-			    platform_timer_get_noirq(timer_get()))
-				continue;
+			if (domain->full_sync) {
+				pdata = ll_sch_get_pdata(&pipe_task->task);
+				assert(pdata);
```
Comment (lgirdwood) [inline src/schedule/dma_multi_chan_domain.c:309]: This should be recoverable. i.e. we should emit some trace and return an error. I know we have assert() in other places, and we should remove, the idea is that we need to build in some survivability when errors do occur so that user space can tear down and rebuild, or developers have working IPC and can debug.

File: src/schedule/dma_multi_chan_domain.c [hunk 3]
```diff
@@ -303,11 +304,23 @@ static bool dma_multi_chan_domain_is_pending(struct ll_schedule_domain *domain,
 			    pipe_task->sched_comp)
 				continue;
 
-			/* it's too soon for this task */
-			if (!pipe_task->registrable &&
-			    pipe_task->task.start >
-			    platform_timer_get_noirq(timer_get()))
-				continue;
+			if (domain->full_sync) {
```
Comment (lgirdwood) [inline src/schedule/dma_multi_chan_domain.c:307]: Can you put a comment here saying what full_sync means and why the action needs to be done differently.

File: src/schedule/ll_schedule.c [hunk 4]
```diff
@@ -323,9 +323,10 @@ static int schedule_ll_task(void *data, struct task *task, uint64_t start,
 			    uint64_t period)
 {
 	struct ll_schedule_data *sch = data;
-	struct ll_task_pdata *pdata;
+	struct ll_task_pdata *pdata, *reg_pdata;
```
Comment (lgirdwood) [inline src/schedule/ll_schedule.c:326]: This should be on a new line.

File: src/schedule/ll_schedule.c [hunk 5]
```diff
@@ -323,9 +323,10 @@ static int schedule_ll_task(void *data, struct task *task, uint64_t start,
...
 	struct list_item *tlist;
-	struct task *curr_task;
+	struct task *curr_task, *registrable_task = NULL;
```
Comment (lgirdwood) [inline src/schedule/ll_schedule.c:328]: ditto

File: src/include/sof/schedule/ll_schedule.h (hunk 1 above)
Comment (dbaluta) [reply src/include/sof/schedule/ll_schedule.h:30]: @iuliana-prodan also can you enhance the commit message in order to better describe what is the current problem.

This 

``We do this because for the DMA_DOMAIN there are no guarantees
for the accuracy of the period of the registrable task
which drives the entire scheduling``` is fine.

We also need to include in the commit message along the lines the scenario we are using and facing issues.

e.g 

In the case we are using a mixer topology there will be 3 pipelines for playback scenarion
- 1 pipeline for pcm1.0  (task 0)
- 1 pipeline for pcm1.1 (task 1)
- 1 pipeline for DAI (task 2)

Each of these pipelines correspond to a task. A

As far as I understood one of the task0 or task1 sometimes starves thus resulting in timeouts on Host.

File: src/schedule/ll_schedule.c [hunk 6]
```diff
@@ -353,6 +354,33 @@ static int schedule_ll_task(void *data, struct task *task, uint64_t start,
 
 	pdata->period = period;
 
+	/* for full synchronous domain, calculate ratio and initialize skip_cnt for task */
+	if (sch->domain->full_sync) {
+		pdata->ratio = 1;
+		pdata->skip_cnt = (uint16_t)(-1);
```
Comment (lgirdwood) [inline src/schedule/ll_schedule.c:360]: It probably best to set a macro to 0xffff and have this as the default skip_cnt, which can then be used throughout the code.

File: src/schedule/ll_schedule.c [hunk 7]
```diff
@@ -353,6 +354,33 @@ static int schedule_ll_task(void *data, struct task *task, uint64_t start,
...
+				break;
+			}
+		}
+
+		/* we found a registrable task */
+		if (registrable_task) {
+			reg_pdata = ll_sch_get_pdata(registrable_task);
+
+			/* the assumption is that the registrable task has the smallest period */
+			assert(period >= reg_pdata->period);
```
Comment (lgirdwood) [inline src/schedule/ll_schedule.c:379]: ditto for assert as above.

File: src/platform/imx8/platform.c [hunk 8]
```diff
@@ -176,6 +176,9 @@ int platform_init(struct sof *sof)
 	sof->platform_dma_domain = dma_multi_chan_domain_init
 			(&sof->dma_info->dma_array[0], 1,
 			 PLATFORM_DEFAULT_CLOCK, false);
+
+	/* i.MX platform DMA domain will be full synchronous, no time dependent */
+	sof->platform_dma_domain->full_sync = true;
```
Comment (lgirdwood) [inline src/platform/imx8/platform.c:181]: Seems like this should be an argument or flag to dma_multi_chan_domain_init()

**Review by lgirdwood — CHANGES_REQUESTED** [review]

File: src/include/sof/schedule/ll_schedule.h (hunk 1 above)
Comment (lgirdwood) [reply src/include/sof/schedule/ll_schedule.h:30]: ack, I'm not fully following the difference between DMA and full sync.

Comment (iuliana-prodan) [reply src/include/sof/schedule/ll_schedule.h:30]: @dbaluta @lgirdwood The difference is that now, the DMA synchronous is still time dependent: the task->start is used to schedule a task.
The full synchronous is not using the time anymore - is based on the period of each task.

I could have put all these changes on synchronous attribute, but I wanted it to have a small impact on the other targets that use dma_multi_chan domain.

Comment (iuliana-prodan) [reply src/include/sof/schedule/ll_schedule.h:30]: Here’s an example of the issue we see on imx. 
In the case of a mixer topology there will be 3 pipelines for playback scenario:
- 1 pipeline for pcm1.0 (task 0);
- 1 pipeline for pcm1.1 (task 1);
- 1 pipeline for DAI (task 2).

Task 2 is the registrable task and this is always scheduled. 
The other tasks (task 0 and task 1) are scheduled based on task->start. 

The problem we see is that, at some point, the DMA transfer from DAI is finished earlier than task->start for one of the task 0 or task 1 and this is not scheduled anymore (based on the check from https://github.com/thesofproject/sof/blob/master/src/schedule/dma_multi_chan_domain.c#L308).
And, task 2 ends up depleting one of the source buffers, thus blocking the entire data flow.

So, task 0 and task 1 should be run at the frequency they were configured with.

@dbaluta I'll add a part of this in the commit message, as you suggested.

File: src/platform/imx8/platform.c (hunk 8 above)
Comment (iuliana-prodan) [reply src/platform/imx8/platform.c:181]: If you agree to add these changes under, the current, synchronous attribute we won't need to modify the function signature(s).

Comment (dbaluta) [reply src/platform/imx8/platform.c:181]: @lgirdwood so one reason for adding a new *mode* (``full_sync``) is that we don't want to force other platforms to use our *optimization*. 
Anyhow, I do think that this might be a real problem on Intel platforms too (although I think none of them uses DMA DAI for scheduling at this moment)

@slawblauciak  @keyonjie can you guys have a look as I've seen you've experimented a little bit with scheduling code.

File: src/include/sof/schedule/ll_schedule.h (hunk 1 above)
Comment (lgirdwood) [reply src/include/sof/schedule/ll_schedule.h:30]: @iuliana-prodan thanks got you now. Can we have this as scheduling type for topology too as a subsequent PR as it seems something we should be specifying at that level along side the other pipeline scheduling config.

File: src/platform/imx8/platform.c (hunk 8 above)
Comment (lgirdwood) [reply src/platform/imx8/platform.c:181]: ok, I think this is a topology scheduler type now.

**Comment by lgirdwood** [comment]
@iuliana-prodan I'm going to tag v1.7-rc1 at some point today, but this is a FIX, so will make it in for rc2 or v1.7 final. It's good work !

File: src/include/sof/schedule/ll_schedule.h (hunk 1 above)
Comment (iuliana-prodan) [reply src/include/sof/schedule/ll_schedule.h:30]: @lgirdwood I've created #3817 for your proposal. Let's continue the discussion there. Thanks!

**Comment by lgirdwood** [comment]
@iuliana-prodan fwiw, I reckon we have about 2 weeks prior to next rc or v1.7 final. So plenty of time.

**Comment by keyonjie** [comment]
@iuliana-prodan @dbaluta what is the periods set of those 3 pipelines in the scenario you described above?

**Comment by iuliana-prodan** [comment]
@keyonjie 
1 pipeline for pcm1.0 (task 0) - 1ms
1 pipeline for pcm1.1 (task 1) - 5ms
1 pipeline for DAI (task 2) - 1ms.
You can check one of the topologies:  sof-imx8*-{codec}-mixer.m4, where codec can be wm8960 or cs42888.

**Comment by keyonjie** [comment]
> @keyonjie
> 1 pipeline for pcm1.0 (task 0) - 1ms
> 1 pipeline for pcm1.1 (task 1) - 5ms
> 1 pipeline for DAI (task 2) - 1ms.
> You can check one of the topologies: sof-imx8*-{codec}-mixer.m4, where codec can be wm8960 or cs42888.

That's exactly same with our BYT platform: sof-cht-nocodec.m4. Isn't the issue already fixed by @lyakh 's PR #3339 ?

**Comment by iuliana-prodan** [comment]
> That's exactly same with our BYT platform: sof-cht-nocodec.m4. Isn't the issue already fixed by @lyakh 's PR #3339 ?
@keyonjie no, on the mixer scenarios this #3339 doesn't fix the problem - even if if you iterate multiple times in schedule_ll_is_pending the current time (https://github.com/thesofproject/sof/blob/master/src/schedule/dma_multi_chan_domain.c#L309) doesn't get greater than task->start. So, the task is still not scheduled.

**Comment by keyonjie** [comment]
> > That's exactly same with our BYT platform: sof-cht-nocodec.m4. Isn't the issue already fixed by @lyakh 's PR #3339 ?
> 
> @keyonjie no, on the mixer scenarios this #3339 doesn't fix the problem - even if if you iterate multiple times in schedule_ll_is_pending the current time (https://github.com/thesofproject/sof/blob/master/src/schedule/dma_multi_chan_domain.c#L309) doesn't get greater than task->start. So, the task is still not scheduled.

This is kind of strange, the 5ms period pipeline should get task->start >= the registered one every 5 iterations, have you printed them(task->start, current time...) out to see what really happen there? I have refinement for this task->start initialization also in my PR https://github.com/thesofproject/sof/pull/3768 and think it may fix the potential issue you mentioned.

File: src/schedule/ll_schedule.c [hunk 9]
```diff
@@ -353,6 +354,33 @@ static int schedule_ll_task(void *data, struct task *task, uint64_t start,
...
+			pdata->ratio = period / reg_pdata->period;
```
Comment (keyonjie) [inline src/schedule/ll_schedule.c:380]: what will happen if the ratio is decimal, e.g. registrable_task with period 3ms and the deep buffer one with period 5ms? Will we still hit similar issue with the PR applied?

**Comment by iuliana-prodan** [comment]
> > > That's exactly same with our BYT platform: sof-cht-nocodec.m4. Isn't the issue already fixed by @lyakh 's PR #3339 ?
> > 
> > 
> > @keyonjie no, on the mixer scenarios this #3339 doesn't fix the problem - even if if you iterate multiple times in schedule_ll_is_pending the current time (https://github.com/thesofproject/sof/blob/master/src/schedule/dma_multi_chan_domain.c#L309) doesn't get greater than task->start. So, the task is still not scheduled.
> 
> This is kind of strange, the 5ms period pipeline should get task->start >= interrupt arrived one every 5 iterations, have you printed them(task->start, current time...) out to see what really happen there? I have refinement for this task->start initialization also in my PR #3768 and think it may fix the potential issue you mentioned.

I've already checked your pull request, I even commented there regarding the mixer issue we have on imx: https://github.com/thesofproject/sof/pull/3768#issuecomment-768509154

File: src/schedule/ll_schedule.c [hunk 10]
```diff
@@ -353,6 +354,33 @@ static int schedule_ll_task(void *data, struct task *task, uint64_t start,
...
+
+			/* registrable task found */
+			if (pipe_task->registrable) {
+				registrable_task = curr_task;
+				break;
+			}
+		}
+
+		/* we found a registrable task */
+		if (registrable_task) {
```
Comment (keyonjie) [inline src/schedule/ll_schedule.c:375]: Be careful that this registrable_task could be invalid if the task is scheduled earlier than the registrable_task.

**Comment by keyonjie** [comment]
> > This is kind of strange, the 5ms period pipeline should get task->start >= interrupt arrived one every 5 iterations, have you printed them(task->start, current time...) out to see what really happen there? I have refinement for this task->start initialization also in my PR #3768 and think it may fix the potential issue you mentioned.
> 
> I've already checked your pull request, I even commented there regarding the mixer issue we have on imx: [#3768 (comment)](https://github.com/thesofproject/sof/pull/3768#issuecomment-768509154)

There is some improvement with the latest version, do you mind to retry it?

**Comment by dbaluta** [comment]
@keyonjie @iuliana-prodan I wonder what is the difference between problem we are both trying to fix. I mean a description of the problem in the natural language and the reason for which it happens.

AFAIK, on IMX mixer scenario:
* task0, task1 are MIXER input tasks
* task2 is MIXER task which also contains the DAI which makes it the task that drivers the scheduling.

Now, what happens:

* it looks like the period of task0 and task2 are very different. task2 has a much smaller period.

Since taks2 is the registrable task, each time task2 is triggered we also check if task0  can be run. Because task0 has a longer
period the scheduler tries to see if it can be scheduled for several times, than it won't try again.

Meanwhile, the timeout from userspace aplay expires and we get an I/O error.

@keyonjie can you try to explain in natural language what happens with the Intel issues?

File: src/schedule/ll_schedule.c (hunk 9 above)
Comment (iuliana-prodan) [reply src/schedule/ll_schedule.c:380]: Based on how the dma_multi_chan_domain is written the assumption is that the other tasks' period is a multiple of the registrable task period. 
Also, the topology files confirm this (at least for imx).

Back to your original question: for 3 and 5 it could happen if the registrable task finishes the DMA transfer earlier than 15ms. But, it will not be fatal, since it can be scheduled latter (at 18ms).

This PR doesn't apply to this scenario, but to the one I described in the beginning.

File: src/schedule/ll_schedule.c (hunk 10 above)
Comment (iuliana-prodan) [reply src/schedule/ll_schedule.c:375]: > Be careful that this registrable_task could be invalid if the task is scheduled earlier than the registrable_task.

yes, I'll fix this.

**Comment by iuliana-prodan** [comment]
The problem is mainly with 1ms period task, not the 5 ms.

**Comment by iuliana-prodan** [comment]
> > > That's exactly same with our BYT platform: sof-cht-nocodec.m4. Isn't the issue already fixed by @lyakh 's PR #3339 ?
> > 
> > 
> > @keyonjie no, on the mixer scenarios this #3339 doesn't fix the problem - even if if you iterate multiple times in schedule_ll_is_pending the current time (https://github.com/thesofproject/sof/blob/master/src/schedule/dma_multi_chan_domain.c#L309) doesn't get greater than task->start. So, the task is still not scheduled.
> 
> This is kind of strange, the 5ms period pipeline should get task->start >= interrupt arrived one every 5 iterations, have you printed them(task->start, current time...) out to see what really happen there? I have refinement for this task->start initialization also in my PR #3768 and think it may fix the potential issue you mentioned. See it here: [efe4e3a](https://github.com/thesofproject/sof/commit/efe4e3a2cde6ae555c61f84d086f6153bf76a8b7)

The problem is mainly with 1ms period task, not the 5 ms.

File: src/schedule/dma_multi_chan_domain.c (hunk 2 above)
Comment (iuliana-prodan) [reply src/schedule/dma_multi_chan_domain.c]: I realize there is no need to check pdata here. This is done in schedule_task_init_ll().

**Comment by dbaluta** [comment]
@iuliana-prodan OK I understand. And this causes a chain reaction. Because the registrable tasks has no data it will cause the DAI to underrun and since we don't have any underrun recovery or something like that the DAI will get into an error state. 

I think we should get this code into our SAI driver. At least we want to see if SAI underrun errors happen and clear it.

https://elixir.bootlin.com/linux/latest/source/sound/soc/fsl/fsl_sai.c#L58

**Comment by iuliana-prodan** [comment]
> @iuliana-prodan OK I understand. And this causes a chain reaction. Because the registrable tasks has no data it will cause the DAI to underrun and since we don't have any underrun recovery or something like that the DAI will get into an error state.
> 
> I think we should get this code into our SAI driver. At least we want to see if SAI underrun errors happen and clear it.
> 
> https://elixir.bootlin.com/linux/latest/source/sound/soc/fsl/fsl_sai.c#L58

@dbaluta There are no underruns or overruns happening in SAI/ESAI. 
The schedule_ll_tasks_run() handler, registered on dma_multi_chan_domain, is always executed, even if there is no data available.
I've tried a simpler scenarios - an aplay of 5 seconds.

The correct behavior is to run aplay, for 5 seconds, and count the number of times the schedule_ll_tasks_run() is executed and how many times the copy_bytes, from dai_copy() (https://github.com/thesofproject/sof/blob/master/src/audio/dai.c#L854) is 0:
```
root@imx8qxpc0mek:~# aplay -Dhw:1,0 -f S16_LE -c 2 -r 48000 -t raw 16/j16.wav -d 5
root@imx8qxpc0mek:~# ./sof-logger -t -l /lib/firmware/imx/sof/sof-imx8x.ldc
...
[18187785632.135418] (      236.510422) c0 ipc                       src/ipc/handler.c:416  ipc: ipc_stream_trigger: comp 0 -> trigger cmd 0x40000
[18187785921.302086] (      289.166656) c0 pipe         1.5       src/audio/pipeline.c:904  pipe trigger cmd 1, **time is = 015af3bec**
[18187786354.531250] (      433.229156) c0 esai         6.0     src/drivers/imx/esai.c:362  ESAI: trigger
[18187786718.125000] (      363.593750) c0 edma                 src/drivers/imx/edma.c:137  EDMA: start(7)
[18187787061.979168] (      343.854156) c0 ll-schedule        ./schedule/ll_schedule.c:383  task add 0x92c30140 pipe-task <f11818eb-e92e-4082-82a3-dc54c604ebb3>
[18187787353.385418] (      291.406250) c0 ll-schedule        ./schedule/ll_schedule.c:387  task params pri 0 flags 0 start 0 period 1000
[18187787730.260418] (      376.875000) c0 ll-schedule        /dma_multi_chan_domain.c:113  dma_multi_chan_domain_register()
[18187787992.447918] (      262.187500) c0 ll-schedule        /dma_multi_chan_domain.c:73   dma_multi_chan_domain_irq_register()
[18187788628.541668] (      636.093750) c0 ll-schedule        /dma_multi_chan_domain.c:201  dma_multi_chan_domain_register OUT: task 0x92c30140, code = 7, ret = 0
[18187789043.281250] (      414.739594) c0 ll-schedule        ./schedule/ll_schedule.c:290  num_tasks 1 total_num_tasks 1
[18187789323.906250] (      280.625000) c0 pipe         1.5       src/audio/pipeline.c:873  On start the cnt_dai_copy0 is 0
[18187789557.812500] (      233.906250) c0 pipe         1.5       src/audio/pipeline.c:876  On start the cnt is 0 and pipe_task is 0x92c30140, , pipe_id = 1
[18354730236.406250] (166940672.000000) c0 ipc                       src/ipc/handler.c:1400 handler: ipc_cmd: command type 1610612736 or hex = 0x60000000
[18354730521.666668] (      285.260406) c0 ipc                       src/ipc/handler.c:1421 handler: ipc_cmd: command SOF_IPC_GLB_STREAM_MSG = 0x60000000
[18354730768.906250] (      247.239578) c0 ipc                       src/ipc/handler.c:468  handler: ipc_glb_stream_message: SOF_IPC_STREAM_TRIG_START/STOP...
[18354730999.635418] (      230.729172) c0 ipc                       src/ipc/handler.c:416  ipc: ipc_stream_trigger: comp 0 -> trigger cmd 0x50000
[18354731267.968750] (      268.333344) c0 pipe         1.5       src/audio/pipeline.c:904  pipe trigger cmd 0, **time is = 0d4bd00ec**
[18354731561.041668] (      293.072906) c0 pipe         1.5       src/audio/pipeline.c:913  On stop the cnt is 5009 and pipe_task is 0x92c30140, on pipe_id = 1
[18354731852.916668] (      291.875000) c0 pipe         1.5       src/audio/pipeline.c:918  On stop the cnt_dai_copy0 is 0
[18354732204.218750] (      351.302094) c0 edma                 src/drivers/imx/edma.c:183  EDMA: stop(7)
[18354732650.416668] (      446.197906) c0 esai         6.0     src/drivers/imx/esai.c:362  ESAI: trigger
[18354733437.812500] (      310.625000) c0 ll-schedule        ./schedule/ll_schedule.c:475  task cancel 0x92c30140 pipe-task <f11818eb-e92e-4082-82a3-dc54c604ebb3>
[18354733833.333336] (      395.520844) c0 ll-schedule        ./schedule/ll_schedule.c:328  num_tasks 0 total_num_tasks 0
[18354734100.000000] (      266.666656) c0 ll-schedule        /dma_multi_chan_domain.c:238  dma_multi_chan_domain_unregister()
[18354734377.552086] (      277.552094) c0 ll-schedule        /dma_multi_chan_domain.c:212  dma_multi_chan_domain_irq_unregister()
[18354734902.552086] (      525.000000) c0 ll-schedule        /dma_multi_chan_domain.c:313  dma_multi_chan_domain_unregister OUT: task 0x92c30140, code = 7
[18355286179.531250] (   551277.000000) c0 ipc                       src/ipc/handler.c:1400 handler: ipc_cmd: command type 1610612736 or hex = 0x60000000
[18355286462.760418] (      283.229156) c0 ipc                       src/ipc/handler.c:1421 handler: ipc_cmd: command SOF_IPC_GLB_STREAM_MSG = 0x60000000
[18355286722.708336] (      259.947906) c0 ipc                       src/ipc/handler.c:460  handler: ipc_glb_stream_message: SOF_IPC_STREAM_PCM_FREE = 0x30000
[18355286983.385418] (      260.677094) c0 pipe         1.5       src/audio/pipeline.c:1005 pipe reset
root@imx8qxpc0mek:~# 
```
time diff = 3,205,350,656 => time_diff /ticks_per_ms = 4812 ticks
ticks_per_ms = 666000
schedule_ll_tasks_run() is executed 5009 times and cnt_dai_copy0 is 0.

To check if SAI gets an underrun, I've always set the copy_bytes, from dai_copy() to 0.
Next, as the above scenario, I've run aplay, for 5 seconds, and count the number of times the schedule_ll_tasks_run() is executed and how many times the copy_bytes, from dai_copy() is 0.
```
root@imx8qxpc0mek:~# aplay -Dhw:1,0 -f S16_LE -c 2 -r 48000 -t raw 16/j16.wav -d 5
root@imx8qxpc0mek:~# ./sof-logger -t -l /lib/firmware/imx/sof/sof-imx8x.ldc
...
[3702852750.208333] (      253.177078) c0 ipc                       src/ipc/handler.c:468  handler: ipc_glb_stream_message: SOF_IPC_STREAM_TRIG_START/STOP...
[3702852984.114583] (      233.906250) c0 ipc                       src/ipc/handler.c:416  ipc: ipc_stream_trigger: comp 0 -> trigger cmd 0x40000
[3702853270.989583] (      286.875000) c0 pipe         1.5       src/audio/pipeline.c:904  pipe trigger cmd 1, **time is = 015bd8275**
[3702853717.447917] (      446.458344) c0 esai         6.0     src/drivers/imx/esai.c:362  ESAI: trigger
[3702854071.979167] (      354.531250) c0 edma                 src/drivers/imx/edma.c:137  EDMA: start(7)
[3702854447.656250] (      375.677094) c0 ll-schedule        ./schedule/ll_schedule.c:383  task add 0x92c30140 pipe-task <f11818eb-e92e-4082-82a3-dc54c604ebb3>
[3702854726.250000] (      278.593750) c0 ll-schedule        ./schedule/ll_schedule.c:387  task params pri 0 flags 0 start 0 period 1000
[3702855121.093750] (      394.843750) c0 ll-schedule        /dma_multi_chan_domain.c:113  dma_multi_chan_domain_register()
[3702855381.666667] (      260.572906) c0 ll-schedule        /dma_multi_chan_domain.c:73   dma_multi_chan_domain_irq_register()
[3702855994.739583] (      613.072937) c0 ll-schedule        /dma_multi_chan_domain.c:201  dma_multi_chan_domain_register OUT: task 0x92c30140, code = 7, ret = 0
[3702856382.083333] (      387.343750) c0 ll-schedule        ./schedule/ll_schedule.c:290  num_tasks 1 total_num_tasks 1
[3702856660.052083] (      277.968750) c0 pipe         1.5       src/audio/pipeline.c:873  On start the cnt_dai_copy0 is 0
[3702856900.781250] (      240.729172) c0 pipe         1.5       src/audio/pipeline.c:876  On start the cnt is 0 and pipe_task is 0x92c30140, , pipe_id = 1
[3840894477.968750] (138037584.000000) c0 ipc                       src/ipc/handler.c:1400 handler: ipc_cmd: command type 1610612736 or hex = 0x60000000
[3840894754.114583] (      276.145844) c0 ipc                       src/ipc/handler.c:1421 handler: ipc_cmd: command SOF_IPC_GLB_STREAM_MSG = 0x60000000
[3840895002.343750] (      248.229172) c0 ipc                       src/ipc/handler.c:468  handler: ipc_glb_stream_message: SOF_IPC_STREAM_TRIG_START/STOP...
[3840895230.364583] (      228.020828) c0 ipc                       src/ipc/handler.c:416  ipc: ipc_stream_trigger: comp 0 -> trigger cmd 0x50000
[3840895497.083333] (      266.718750) c0 pipe         1.5       src/audio/pipeline.c:904  pipe trigger cmd 0, **time is = 0b3b7916a**
[3840895787.656250] (      290.572906) c0 pipe         1.5       src/audio/pipeline.c:913  On stop the cnt is 4142 and pipe_task is 0x92c30140, on pipe_id = 1
[3840896076.979167] (      289.322906) c0 pipe         1.5       src/audio/pipeline.c:918  On stop the cnt_dai_copy0 is 4142
[3840896407.187500] (      330.208344) c0 edma                 src/drivers/imx/edma.c:183  EDMA: stop(7)
[3840896856.822917] (      449.635406) c0 esai         6.0     src/drivers/imx/esai.c:362  ESAI: trigger
[3840897634.739583] (      310.000000) c0 ll-schedule        ./schedule/ll_schedule.c:475  task cancel 0x92c30140 pipe-task <f11818eb-e92e-4082-82a3-dc54c604ebb3>
[3840898015.729167] (      380.989594) c0 ll-schedule        ./schedule/ll_schedule.c:328  num_tasks 0 total_num_tasks 0
[3840898295.364583] (      279.635406) c0 ll-schedule        /dma_multi_chan_domain.c:238  dma_multi_chan_domain_unregister()
[3840898554.791667] (      259.427094) c0 ll-schedule        /dma_multi_chan_domain.c:212  dma_multi_chan_domain_irq_unregister()
[3840899076.510417] (      521.718750) c0 ll-schedule        /dma_multi_chan_domain.c:313  dma_multi_chan_domain_unregister OUT: task 0x92c30140, code = 7
[3841605569.687500] (   706493.187500) c0 ipc                       src/ipc/handler.c:1400 handler: ipc_cmd: command type 1610612736 or hex = 0x60000000
[3841605847.239583] (      277.552094) c0 ipc                       src/ipc/handler.c:1421 handler: ipc_cmd: command SOF_IPC_GLB_STREAM_MSG = 0x60000000
[3841606101.458333] (      254.218750) c0 ipc                       src/ipc/handler.c:460  handler: ipc_glb_stream_message: SOF_IPC_STREAM_PCM_FREE = 0x30000
[3841606360.937500] (      259.479156) c0 pipe         1.5       src/audio/pipeline.c:1005 pipe reset
root@imx8qxpc0mek:~# 
```
time diff = 2,650,410,741 => time_diff /ticks_per_ms = 3979 ticks
ticks_per_ms = 666000
schedule_ll_tasks_run() is executed 4142 times and cnt_dai_copy0 is 4142.

As you can see from the logs, the scheduling is never stopped by SAI/ESAI overrun or overrun since the DMA IRQ is always generated and the registered callback (schedule_ll_tasks_run()) is called.

The scheduling is stopped only when we get GLB_STREAM_MSG: TRIG_STOP from kernel and this happens when host buffer underrun / overrun is detected on the kernel side. The underrun of the host buffer happens because the host_dma_cb() is not called when dai_copy() has 0 bytes to pass to the dma_copy() (it's just a notififier on NOTIFIER_ID_DMA_COPY).

**Review by lgirdwood — APPROVED** [review]
@iuliana-prodan good now, I think this will work fine on Intel too.

**Comment by lgirdwood** [comment]
Jenkins showing DUT kernel boot issue that is unrelated.

**Comment by lgirdwood** [comment]
@dbaluta good for you - make sense - and probably explains an similar intermittent issue we on some of the legacy Intel platfomrs that use the same scheduling config.

**Review by dbaluta — APPROVED** [review]

**Comment by dbaluta** [comment]
@lgirdwood  looks to me.
