### PR TITLE
ipc: header size validation fix

### LINKED ISSUE #3028: [BUG][SDL] IPC Generic: DSP Panic when sending IPC with size 0
**Describe the bug**
When sending ipc to FW with ipc size field set to zero DSP PANIC is detected. Applies to all platforms. TplgBufferNew IPC used as an example.

**To Reproduce**
Run test script: 
04_01_TestFuzzIpcSizeMin

**Reproduction Rate**
100%

**Expected behavior**
IPC Error response from FW

**Environment**
1) SOF FW: branch master commit ef43899 and earlier 
2) Python tests scripts: branch master commit: 81d72ef
3) Platform: Any

**Logs**
[ipc.log](https://github.com/thesofproject/sof/files/4729127/ipc.log)
[dma_trace_1_panic.log](https://github.com/thesofproject/sof/files/4729128/dma_trace_1_panic.log)
[DECODED_COREDUMP.txt](https://github.com/thesofproject/sof/files/4729129/DECODED_COREDUMP.txt)

### PR DESCRIPTION
**Pull request by abonislawski**
This patch will deny IPC headers with size 0

Fixes #3028

### CODE REVIEW

File: src/ipc/handler.c [hunk 1]
```diff
@@ -122,8 +122,8 @@ struct sof_ipc_cmd_hdr *mailbox_validate(void)
 	mailbox_hostbox_read(hdr, SOF_IPC_MSG_MAX_SIZE, 0, sizeof(*hdr));
 
 	/* validate component header */
-	if (hdr->size > SOF_IPC_MSG_MAX_SIZE) {
-		tr_err(&ipc_tr, "ipc: msg too big at 0x%x", hdr->size);
+	if (!hdr->size || hdr->size > SOF_IPC_MSG_MAX_SIZE) {
```
Comment (lgirdwood) [inline src/ipc/handler.c:125]: Should the min size not be sizeof(header) as this will be our smallest message ?

Comment (abonislawski) [reply src/ipc/handler.c]: looks even better, done
