### PR TITLE
pipeline: change pipe reset propagation condition

### LINKED ISSUE #3096: [BUG] Firmware returns an error on TplgCompFree on test with mixer on capture pipline.
**Describe the bug**
When running simultaneous 3 x capture and 3 x playback on loopback signal on each SSP's with mixer component on one of the capture pipeline, firmware returns an error on TplgCompFree. Error is visible since commit a21cba16d99d642dd55fd3ebdd04201fb1017c40 which check state != COMP_STATE_READY in comp_free.
When sending ipc TplgCompFree on mixer component firmware return -22.

**Topology**
```
+-------------------------+
| +----+   +----+   +---+ |              +----+
| |Host|-->|Buff|-->|Dai| +------------->|SSPx|-----------------+
| +----+   +----+   +---+ |              +----+                 |
+-------------------------+                                     |
                                                                |
+-------------------------+                                     |
| +----+   +----+   +---+ |              +------+               |
| |Host|-->|Buff|-->|Dai| +------------->|SSPx+1|------------+  |
| +----+   +----+   +---+ |              +------+            |  |
+-------------------------+                                  |  |
                                                             |  |
+-------------------------+                                  |  |
| +----+   +----+   +---+ |              +------+            |  |
| |Host|-->|Buff|-->|Dai| +------------->|SSPx+2|---------+  |  |
| +----+   +----+   +---+ |              +------+         |  |  |
+-------------------------+                               |  |  |
                                                          |  |  |
                                                          |  |  |
                                                          |  |  |
                                                          |  |  |
                                    +----------------+    |  |  |
                                    | +----+   +---+ |    |  |  |
                        +-----------+ |Buff|<--|Dai| <----+  |  |
                        |           | +----+   +---+ |       |  |
                        |           +----------------+       |  |
                        |                                    |  |
                        |           +----------------+       |  |
                        |           | +----+   +---+ |       |  |
                        | +---------+ |Buff|<--|Dai| <-------+  |
                        | |         | +----+   +---+ |          |
                        | |         +----------------+          |
                        | |                                     |
+-----------------------v-v-----------------------+             |
| +----+    +----+    +-----+    +----+   +-----+ |             |
| |Host|<---|Buff|<---|Mixer|<---|Buff|<--| Dai |<--------------+
| +----+    +----+    +-----+    +-- -+   +-----+ |
+-------------------------------------------------+
```
**To Reproduce**
Run one of slim driver python tests from file:
test_01_mixer_capture.py

**Reproduction Rate**
100 %

**Expected behavior**
The released components should be in proper state and released without errors.

**Environment**
WHL RVP

Commit: 20ab16c36ece474fc3a55e87d7daa945bdcc9089 from SOF master branch.

**Example logs**
[dma_trace_1.log](https://github.com/thesofproject/sof/files/4829524/dma_trace_1.log)

[2020_06_25_08_03_00.zip](https://github.com/thesofproject/sof/files/4829519/2020_06_25_08_03_00.zip)

### PR DESCRIPTION
**Pull request by bkokoszx**
This commit allows propagating pipeline reset to adjacent pipelines
assuming that they have the same schedule component.

fixes #3096 

Signed-off-by: Bartosz Kokoszko <bartoszx.kokoszko@linux.intel.com>

### CODE REVIEW

**Comment by bkokoszx** [comment]
SOFCI TEST

**Comment by bkokoszx** [comment]
@lgirdwood 
I'm not sure, but I think, that it should not break any rules in parameters negotiations between pipelines. @mmaka1 Can you refer to this PR? 

At the moment we defined topology like that (we do not split pipeline 1 into two pipelines ```HOST-BUF```, ```MIX-DAI```):
```
pipe_id = 1
+--------------------------------------------------+
| +------+   +-----+   +-----+   +-----+   +-----+ |   +----+
| | Host |-->| Buf |-->| Mix |-->| Buf |-->| Dai |---->|SSPx|
| +------+   +-----+   +-----+   +-----+   +-----+ |   +----+
+-------------------------^------------------------+    |  |
                          |                             |  |
 pipe_id = 2              |                             |  |
+--------------------+    |                             |  |
| +------+   +-----+ |    |                             |  |
| | Host |-->| Buf |------+                             |  |
| +------+   +-----+ |                                  |  |
+--------------------+    
```
ATM we do not have possibilities to trigger ```HOST-BUF``` separately from ```MIX-DAI```. In this PR I wanted to align reset with our trigger propagation.

**Comment by bkokoszx** [comment]
@lgirdwood 
Could you make re-review and refer to my latest comment?

File: src/audio/pipeline.c [hunk 1]
```diff
@@ -824,12 +824,15 @@ static int pipeline_comp_reset(struct comp_dev *current,
...
+	int is_single_ppl = comp_is_single_pipeline(current, p->source_comp);
+	int is_same_sched =
+		pipeline_is_same_sched_comp(current->pipeline, p);
 	int err;
 
 	pipe_dbg(current->pipeline, "pipeline_comp_reset(), current->comp.id = %u, dir = %u",
 		 dev_comp_id(current), dir);
 
-	if (!comp_is_single_pipeline(current, p->source_comp)) {
+	if (!is_single_ppl && !is_same_sched) {
```
Comment (lgirdwood) [inline src/audio/pipeline.c:835]: Can you add an inline comment here for this conditional since the use case is complex. I'm assuming you are checking for two connected pipelines taht are scheduled with different components ?

Comment (bkokoszx) [reply src/audio/pipeline.c:838]: @lgirdwood 
I've updated comment. I'm checking pipelines that are scheduled with the same schedule component. ATM it is the sam as in ```pipeline_comp_trigger()```:
``` c
/* trigger should propagate to the connected pipelines,
	 * which need to be scheduled together
	 */
	if (!is_single_ppl && !is_same_sched) {
		pipe_dbg(current->pipeline, "pipeline_comp_trigger(), current is from another pipeline");
```

**Comment by bkokoszx** [comment]
@lgirdwood 
Are we able to merge this PR?

**Comment by lgirdwood** [comment]
@bkokoszx yep - looks like a DUT failure.
