### PR TITLE
probes-app: build fix

### LINKED ISSUE #2551: [BUG] SOF tools build fails
**Describe the bug**

I'm using Ubuntu 19.10 and I get this with GCC version 9.2.1

```
singalsu@singalsu-MOBL:~/work/current/sof/sof/tools/build_tools$ make
[  0%] Building C object probes/CMakeFiles/sof-probes.dir/probes_main.c.o
/home/singalsu/work/current/sof/sof/tools/probes/probes_main.c: In function ‘parse_data’:
/home/singalsu/work/current/sof/sof/tools/probes/probes_main.c:222:5: error: converting a packed ‘struct probe_data_packet’ pointer (alignment 1) to a ‘uint32_t’ {aka ‘unsigned int’} pointer (alignment 4) may result in an unaligned pointer value [-Werror=address-of-packed-member]
  222 |     w_ptr = (uint32_t *)packet;
      |     ^~~~~
In file included from /home/singalsu/work/current/sof/sof/tools/probes/probes_main.c:16:
/home/singalsu/work/current/sof/sof/tools/probes/../../src/include/ipc/probe.h:88:8: note: defined here
   88 | struct probe_data_packet {
      |        ^~~~~~~~~~~~~~~~~
/home/singalsu/work/current/sof/sof/tools/probes/probes_main.c:254:26: error: taking address of packed member of ‘struct probe_data_packet’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
  254 |      w_ptr = (uint32_t *)&packet->data;
      |                          ^~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [probes/CMakeFiles/sof-probes.dir/build.make:63: probes/CMakeFiles/sof-probes.dir/probes_main.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:91: probes/CMakeFiles/sof-probes.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

```

**To Reproduce**
Run scripts/build-tools.sh

**Reproduction Rate**
How often does the issue happen ? i.e. 1/10 (once in ten attempts), 1/1000 or all the time.
Does the reproduction rate vary with any other configuration or user action, if so please describe and show the new reproduction rate.

**Expected behavior**

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: {SHA}
    * SOF: {SHA}
2) Name of the topology file
    * Topology: {FILE}
3) Name of the platform(s) on which the bug is observed.
    * Platform: {PLATFORM}

**Screenshots or console output**
If applicable, add a screenshot (drag-and-drop an image), or console logs
(cut-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue.

Please also include the relevant sections from the firmware log and kernel log in the report (and attach the full logs for complete reference). Kernel log is taken from *dmesg* and firmware log from *sof-logger*. See https://thesofproject.github.io/latest/developer_guides/debugability/logger/index.html

### PR DESCRIPTION
**Pull request by abonislawski**
Fixes #2551

### CODE REVIEW

File: src/include/ipc/probe.h [hunk 1]
```diff
@@ -94,7 +94,7 @@ struct probe_data_packet {
 	uint32_t checksum;		/**< CRC32 of header and payload */
 	uint32_t data_size_bytes;	/**< Size of following audio data */
 	uint32_t data[];		/**< Audio data extracted from buffer */
-} __attribute__((packed));
+};
```
Comment (plbossart) [inline src/include/ipc/probe.h]: can you clarify why it's unnecessary? It's used in all other structures defined in this file.

File: tools/probes/probes_main.c [hunk 2]
```diff
@@ -199,6 +199,12 @@ void parse_data(char *file_in)
 	}
 
 	packet = malloc(PACKET_MAX_SIZE);
+	if (packet == NULL) {
```
Comment (plbossart) [inline tools/probes/probes_main.c]: if (!packet)

File: tools/probes/probes_main.c [hunk 3]
```diff
@@ -199,6 +199,12 @@ void parse_data(char *file_in)
...
+		fprintf(stderr, "error: allocation failed, err %d\n",
+			errno);
+		fclose(fd_in);
+		exit(0);
+	}
```
Comment (plbossart) [inline tools/probes/probes_main.c]: You haven't fixed the main issue: 
w_ptr = (uint32_t *)packet;

Comment (plbossart) [reply tools/probes/probes_main.c]: You fixed the issue by removing the packed attribute, that's really odd...

Comment (abonislawski) [reply tools/probes/probes_main.c]: There is nothing wrong with assigning a pointer but it can if there is alignment inconsistency and the error was clear:
error: converting a **packed** ‘struct probe_data_packet’ pointer (**alignment 1**) to a ‘uint32_t’ {aka ‘unsigned int’} pointer (**alignment 4**) may result in an unaligned pointer value

packed attribute defines struct members aligment and this is the true reason for alignment inconsistency

File: src/include/ipc/probe.h (hunk 1 above)
Comment (abonislawski) [reply src/include/ipc/probe.h]: This struct is full of uint32_t which means it will work exactly the same way with and without attribute packed.
So there is no reason to generate false warnings because of forced alignment 1

File: tools/probes/probes_main.c (hunk 2 above)
Comment (abonislawski) [reply tools/probes/probes_main.c]: fixed

Comment (abonislawski) [reply tools/probes/probes_main.c]: fixed

File: tools/probes/probes_main.c (hunk 3 above)
Comment (lgirdwood) [reply tools/probes/probes_main.c]: @abonislawski please use ``` __builtin_assume_aligned(ptr, alignment)```

Comment (abonislawski) [reply tools/probes/probes_main.c]: @lgirdwood can you explain why? Without "packed" we have both alignments equal, no 
assumptions = no errors

Comment (lgirdwood) [reply tools/probes/probes_main.c]: Data must be packed between FW, kernel and userspace since they may all use different compilers that will optimise and can pack differently.

Comment (marc-hb) [reply tools/probes/probes_main.c]: How about `__attribute__((packed, aligned(4)))`? Does that avoid the warning?

Both `aligned(4)` _and_ `packed` because in the surprising case of a compiler aligning uint32_t on 64 bits, I suspect gcc's `aligned(4)` alone behaves like the newer C11 `_Alignas(4)`  which refuses to  "weaken the alignment the type would have had naturally" https://en.cppreference.com/w/c/language/_Alignas

This page claims that `packed` (conceptually ~= `force_aligned(1)` ) can cause slower code http://digitalvampire.org/blog/index.php/2006/07/31/why-you-shouldnt-use-__attribute__packed/
It would be interesting to disassemble and compare.

https://groups.google.com/forum/#!msg/x86-64-abi/IT0wgB6Fd5g/awOmKV7UBgAJ

Comment (abonislawski) [reply tools/probes/probes_main.c]: @lgirdwood ok seems reasonable but is there a real case with the struct like that? Cant imagine other than future 64bits, I will update with alignment assume

@marc-hb yeap, packed and aligned 4 looks the best, great for now (because actually doing nothing) and ready for 64b.
As you said alignment 1 can be slower, not sure if even here when forced 1 but in real its still 4, probably still slower because compiler cannot assume align4

File: src/include/ipc/probe.h (hunk 1 above)
Comment (kv2019i) [reply src/include/ipc/probe.h]: @abonislawski That's not really guaranteed. I don't personally like use of packed structs very much either to implement binary interfaces, but it is faster, so most projects just use them -- and SOF uses them a looot. But, but, without packed it is not guaranteed the struct layout is what you expect, even if it just contains "uint32_t" members. Compiler is free to e.g. align all members to 64bit boundaries if it chooses to. So if this struct is used to cast from/to binary data, then it should be packed.

File: tools/probes/probes_main.c [hunk 4]
```diff
@@ -219,7 +219,7 @@ void parse_data(char *file_in)
 				/* request to copy full data packet */
 				total_data_to_copy = sizeof(struct probe_data_packet) /
 					sizeof(uint32_t);
-				w_ptr = (uint32_t *)packet;
+				w_ptr = __builtin_assume_aligned((uint32_t *)packet, 1);
```
Comment (lgirdwood) [inline tools/probes/probes_main.c]: Btw, I assume we are aligning on 1 byte because we need to synchronise the input stream on the structure header (and this can be caused by interruptions in the input stream) ? If so, lets make this obvious in the commit message and as some inline comments (otherwise folks will see this a a performance bottleneck).

Comment (abonislawski) [reply tools/probes/probes_main.c]: The only issue is GCC warning because probe packet struct is forced to align 1 (by _packed_ attribute). Whatever  (1 or 4) we will put in __builtin_assume_aligned it will be ok for gcc

Comment (lgirdwood) [reply tools/probes/probes_main.c]: Everything is 4 byte aligned looking at the code.

Comment (abonislawski) [reply tools/probes/probes_main.c]: @lgirdwood it is but the struct is forced to be "packed" so the alignment is 1.
Changed assumption to 4, both are okay for gcc

File: tools/probes/probes_main.c [hunk 5]
```diff
@@ -219,7 +219,8 @@ void parse_data(char *file_in)
 				/* request to copy full data packet */
 				total_data_to_copy = sizeof(struct probe_data_packet) /
 					sizeof(uint32_t);
-				w_ptr = (uint32_t *)packet;
+				/* probe_data_packet forced to align 1 */
+				w_ptr = __builtin_assume_aligned((uint32_t *)packet, 4);
```
Comment (lgirdwood) [inline tools/probes/probes_main.c]: can you update the comment too.

Comment (abonislawski) [reply tools/probes/probes_main.c]: I think its valid as error shows:
error: converting a packed ‘struct probe_data_packet’ pointer (alignment 1)
it was forced to 1 by 'packed' so we assume it is 4 here

Comment (lgirdwood) [reply tools/probes/probes_main.c]: @abonislawski but this structure is being read from file into either a buffer that is malloced on at least a 4 byte alignment or the stack (data[]) and is read in chunks of 4 bytes. This is the compiler warning you it's possible the alignment may be 1 byte, but in reality we are telling the compiler that it's 4 bytes based on our mechanism for loading the data. It does not help that we are mixing uint32_t * and struct *, perhaps this needs fixed too.

Comment (abonislawski) [reply tools/probes/probes_main.c]: > it's possible the alignment may be 1 byte

Thats why I have added align 1 info in comment, it may be 1 but we know it will not be 1 so assume 4.

If thats wrong please tell me what I should put in comment and lets close this PR

Comment (lgirdwood) [reply tools/probes/probes_main.c]: 4 in comment and 4 in alignment.

Comment (abonislawski) [reply tools/probes/probes_main.c]: ok done! :)

Comment (marc-hb) [reply tools/probes/probes_main.c]: > This is the compiler warning you it's possible the alignment may be 1 byte,

I think the compiler is only echoing what `packed` ~= `aligned(1)` told it in the first place.

So the current solution seems to be this:
1. `packed`  =>  not aligned
2. `__builtin_assume_aligned(..., 4)` => oh no wait; I changed my mind: actually it is aligned!

What's wrong with `(packed, aligned(4))` and no `__builtin_assume_aligned(..., 4)` ? Fixes the warning for me.

Comment (marc-hb) [reply tools/probes/probes_main.c]: BTW here's a very simple demo of the difference between ` probe_data_packet ((packed))` and `probe_data_packet ((packed, aligned(4))`. In this artificial demo, `((packed))` fails the `_Static_assert` whereas `((packed, aligned(4))` doesn't.
```diff
modified   src/probe/probe.c
@@ -64,9 +64,12 @@ struct probe_pdata {
 	struct probe_dma_ext ext_dma;				  /**< extraction DMA */
 	struct probe_dma_ext inject_dma[CONFIG_PROBE_DMA_MAX];	  /**< injection DMA */
 	struct probe_point probe_points[CONFIG_PROBE_POINTS_MAX]; /**< probe points */
+	uint8_t dummy;
 	struct probe_data_packet header;			  /**< data packet header */
 	struct task dmap_work;					  /**< probe task */
 };
+_Static_assert(offsetof(struct probe_pdata, header) % 4 == 0 ,
+               "probe_data_packet is not 4 aligned");
 
 /**
  * \brief Allocate and initialize probe buffer with correct alignment.
```

PS: there are other, unrelated -Werr failures in `probe.c` with `xtensa-apl-elf-gcc (crosstool-NG 1.23.0.440-3b8c) 7.3.0`. I digress.

**Comment by lgirdwood** [comment]
Lets fix the build and continue discussion if needed. CI UT issues must be unrelated

**Comment by marc-hb** [comment]
> Lets fix the build and continue discussion if needed.

BTW PR #2504 just broke `src/probe/probe.c` in a completely unrelated way.

**Comment by marc-hb** [comment]
> Lets fix the build and continue discussion if needed.

Revert __builtin_assume_aligned(4) probe packet, replace with aligned(4) #2655
