### PR TITLE
comp: fetch params from sink buffer

### LINKED ISSUE #2154: [BUG][APL][PCM512x]"error: ipc error for 0x60010000 size 20" when aplay via(0,0)
**Describe the bug**
Aplay via (0,0) and Speak-test(0,0) can not work,dmesg show "error: ipc error for 0x60010000 size 20"

**To Reproduce**
1.sudo reboot
2.Run "aplay -Dhw:0,0 -f dat -c 2 wav/48California_Dreaming.wav -vv -i" to aplay via (0,0)   or
  Run "speaker-test -Dhw:0,0 -r48000 -f1000 -c2 -t wav -l 10" to do speaker-test

```
ubuntu@cd-apl-up2-pcm512x-07:~$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: sofbxtpcm512x [sof-bxt-pcm512x], device 0: Port5 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofbxtpcm512x [sof-bxt-pcm512x], device 1: HDMI1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofbxtpcm512x [sof-bxt-pcm512x], device 2: HDMI2 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofbxtpcm512x [sof-bxt-pcm512x], device 3: HDMI3 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofbxtpcm512x [sof-bxt-pcm512x], device 4: Media Playback 4 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice
```

**Reproduction Rate**
5/5

**Expected behavior**
Aplay via (0,0) and Speaker-test(0,0) normally

**Impact**
Aplay via (0,0) and Speaker-test (0,0)can not work,dmesg show "error: ipc error for 0x60010000 size 20"

```
ubuntu@cd-apl-up2-pcm512x-07:~$ aplay -Dhw:0,0 -f dat -c 2 wav/48California_Dreaming.wav -vv -i
Playing WAVE 'wav/48California_Dreaming.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
aplay: set_params:1363: Unable to install hw params:
ACCESS:  RW_INTERLEAVED
FORMAT:  S16_LE
SUBFORMAT:  STD
SAMPLE_BITS: 16
FRAME_BITS: 32
CHANNELS: 2
RATE: 48000
PERIOD_TIME: 85000
PERIOD_SIZE: 4080
PERIOD_BYTES: 16320
PERIODS: (4 5)
BUFFER_TIME: 341000
BUFFER_SIZE: 16368
BUFFER_BYTES: 65472
TICK_TIME: 0
ubuntu@cd-apl-up2-pcm512x-07:~$
```

<details>
 <summary>dmesg_error.log</summary>

````
[   41.719205] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x140000 successful
[   41.719223] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x40000 successful
[   41.719228] sof-audio-pci 0000:00:0e.0: period_bytes:0x1080
[   41.719231] sof-audio-pci 0000:00:0e.0: periods:15
[   41.719243] sof-audio-pci 0000:00:0e.0: stream_tag 1
[   41.719253] sof-audio-pci 0000:00:0e.0: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[   41.719603] sof-audio-pci 0000:00:0e.0: error: ipc error for 0x60010000 size 20
[   41.719615] sof-audio-pci 0000:00:0e.0: error: hw params ipc failed for stream 1
[   41.719621] sof-audio-pci 0000:00:0e.0: ASoC: 0000:00:0e.0 hw params failed: -22
[   41.719631]  Port5: ASoC: hw_params FE failed -22
[   41.721064] sof-audio-pci 0000:00:0e.0: pcm: free stream 0 dir 0
[   41.722547] sof-audio-pci 0000:00:0e.0: pcm: close stream 0 dir 0
[   41.725186] pcm512x i2c-104C5122:00: No SCLK, using BCLK: -2
[   41.725208] sof-audio-pci 0000:00:0e.0: pcm: open stream 0 dir 0
[   41.725214] sof-audio-pci 0000:00:0e.0: period min 192 max 16384 bytes
[   41.725218] sof-audio-pci 0000:00:0e.0: period count 2 max 16
[   41.725221] sof-audio-pci 0000:00:0e.0: buffer max 65536 bytes
[   41.725803] sof-audio-pci 0000:00:0e.0: rate_min: 48000 rate_max: 48000
[   41.725808] sof-audio-pci 0000:00:0e.0: channels_min: 2 channels_max: 2
[   41.725815] sof-audio-pci 0000:00:0e.0: rate_min: 48000 rate_max: 48000
[   41.725818] sof-audio-pci 0000:00:0e.0: channels_min: 2 channels_max: 2
[   41.725827] sof-audio-pci 0000:00:0e.0: rate_min: 48000 rate_max: 48000
[   41.725830] sof-audio-pci 0000:00:0e.0: channels_min: 2 channels_max: 2
[   41.725837] sof-audio-pci 0000:00:0e.0: pcm: hw params stream 0 dir 0
[   41.725844] sof-audio-pci 0000:00:0e.0: generating page table for 000000006d854cde size 0x4b00 pages 5
[   41.725855] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x140000 successful
[   41.725875] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x40000 successful
[   41.725881] sof-audio-pci 0000:00:0e.0: period_bytes:0x12c0
[   41.725884] sof-audio-pci 0000:00:0e.0: periods:4
[   41.725895] sof-audio-pci 0000:00:0e.0: stream_tag 1
[   41.725905] sof-audio-pci 0000:00:0e.0: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[   41.726275] sof-audio-pci 0000:00:0e.0: error: ipc error for 0x60010000 size 20
[   41.726291] sof-audio-pci 0000:00:0e.0: error: hw params ipc failed for stream 1
[   41.726301] sof-audio-pci 0000:00:0e.0: ASoC: 0000:00:0e.0 hw params failed: -22
[   41.726308]  Port5: ASoC: hw_params FE failed -22
[   41.727551] sof-audio-pci 0000:00:0e.0: pcm: free stream 0 dir 0
[   41.729215] sof-audio-pci 0000:00:0e.0: rate_min: 48000 rate_max: 48000
[   41.729222] sof-audio-pci 0000:00:0e.0: channels_min: 2 channels_max: 2
[   41.729230] sof-audio-pci 0000:00:0e.0: rate_min: 48000 rate_max: 48000
[   41.729233] sof-audio-pci 0000:00:0e.0: channels_min: 2 channels_max: 2
[   41.729245] sof-audio-pci 0000:00:0e.0: rate_min: 48000 rate_max: 48000
[   41.729248] sof-audio-pci 0000:00:0e.0: channels_min: 2 channels_max: 2
[   41.729258] sof-audio-pci 0000:00:0e.0: pcm: hw params stream 0 dir 0
[   41.729265] sof-audio-pci 0000:00:0e.0: generating page table for 000000006d854cde size 0x4b00 pages 5
[   41.729278] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x140000 successful
[   41.729296] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x40000 successful
[   41.729301] sof-audio-pci 0000:00:0e.0: period_bytes:0x12c0
[   41.729304] sof-audio-pci 0000:00:0e.0: periods:4
[   41.729317] sof-audio-pci 0000:00:0e.0: stream_tag 1
[   41.729327] sof-audio-pci 0000:00:0e.0: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[   41.729667] sof-audio-pci 0000:00:0e.0: error: ipc error for 0x60010000 size 20
[   41.729680] sof-audio-pci 0000:00:0e.0: error: hw params ipc failed for stream 1
[   41.729687] sof-audio-pci 0000:00:0e.0: ASoC: 0000:00:0e.0 hw params failed: -22
[   41.729697]  Port5: ASoC: hw_params FE failed -22
[   41.730806] sof-audio-pci 0000:00:0e.0: pcm: free stream 0 dir 0
[   41.732335] sof-audio-pci 0000:00:0e.0: rate_min: 48000 rate_max: 48000
[   41.732342] sof-audio-pci 0000:00:0e.0: channels_min: 2 channels_max: 2
[   41.732349] sof-audio-pci 0000:00:0e.0: rate_min: 48000 rate_max: 48000
[   41.732352] sof-audio-pci 0000:00:0e.0: channels_min: 2 channels_max: 2
[   41.732364] sof-audio-pci 0000:00:0e.0: rate_min: 48000 rate_max: 48000
[   41.732367] sof-audio-pci 0000:00:0e.0: channels_min: 2 channels_max: 2
[   41.732377] sof-audio-pci 0000:00:0e.0: pcm: hw params stream 0 dir 0
[   41.732384] sof-audio-pci 0000:00:0e.0: generating page table for 000000006d854cde size 0x4b00 pages 5
[   41.732396] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x140000 successful
[   41.732416] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x40000 successful
[   41.732422] sof-audio-pci 0000:00:0e.0: period_bytes:0x540
[   41.732425] sof-audio-pci 0000:00:0e.0: periods:14
[   41.732438] sof-audio-pci 0000:00:0e.0: stream_tag 1
[   41.732449] sof-audio-pci 0000:00:0e.0: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[   41.732773] sof-audio-pci 0000:00:0e.0: error: ipc error for 0x60010000 size 20
[   41.732786] sof-audio-pci 0000:00:0e.0: error: hw params ipc failed for stream 1
[   41.732792] sof-audio-pci 0000:00:0e.0: ASoC: 0000:00:0e.0 hw params failed: -22
[   41.732803]  Port5: ASoC: hw_params FE failed -22
[   41.734189] sof-audio-pci 0000:00:0e.0: pcm: free stream 0 dir 0
[   41.735908] sof-audio-pci 0000:00:0e.0: rate_min: 48000 rate_max: 48000
[   41.735915] sof-audio-pci 0000:00:0e.0: channels_min: 2 channels_max: 2
[   41.735922] sof-audio-pci 0000:00:0e.0: rate_min: 48000 rate_max: 48000
[   41.735925] sof-audio-pci 0000:00:0e.0: channels_min: 2 channels_max: 2
[   41.735937] sof-audio-pci 0000:00:0e.0: rate_min: 48000 rate_max: 48000
[   41.735940] sof-audio-pci 0000:00:0e.0: channels_min: 2 channels_max: 2
[   41.735950] sof-audio-pci 0000:00:0e.0: pcm: hw params stream 0 dir 0
[   41.735957] sof-audio-pci 0000:00:0e.0: generating page table for 000000006d854cde size 0xffc0 pages 16
[   41.735970] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x140000 successful
[   41.735988] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x40000 successful
[   41.735994] sof-audio-pci 0000:00:0e.0: period_bytes:0x12c0
[   41.735997] sof-audio-pci 0000:00:0e.0: periods:13
[   41.736010] sof-audio-pci 0000:00:0e.0: stream_tag 1
[   41.736021] sof-audio-pci 0000:00:0e.0: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[   41.736337] sof-audio-pci 0000:00:0e.0: error: ipc error for 0x60010000 size 20
[   41.736352] sof-audio-pci 0000:00:0e.0: error: hw params ipc failed for stream 1
[   41.736361] sof-audio-pci 0000:00:0e.0: ASoC: 0000:00:0e.0 hw params failed: -22
[   41.736373]  Port5: ASoC: hw_params FE failed -22
[   41.737970] sof-audio-pci 0000:00:0e.0: pcm: free stream 0 dir 0
[   41.739551] sof-audio-pci 0000:00:0e.0: rate_min: 48000 rate_max: 48000
[   41.739558] sof-audio-pci 0000:00:0e.0: channels_min: 2 channels_max: 2
[   41.739565] sof-audio-pci 0000:00:0e.0: rate_min: 48000 rate_max: 48000
[   41.739569] sof-audio-pci 0000:00:0e.0: channels_min: 2 channels_max: 2
[   41.739581] sof-audio-pci 0000:00:0e.0: rate_min: 48000 rate_max: 48000
[   41.739584] sof-audio-pci 0000:00:0e.0: channels_min: 2 channels_max: 2
[   41.739594] sof-audio-pci 0000:00:0e.0: pcm: hw params stream 0 dir 0
[   41.739601] sof-audio-pci 0000:00:0e.0: generating page table for 000000006d854cde size 0xffc0 pages 16
````
</details>

<details>
 <summary>sof_errortrace.log</summary>

````
CORE  LEVEL      COMP_ID                TIMESTAMP            DELTA                FILE_NAME	CONTENT
    0      1          IPC          41228761.770833  41228760.000000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41251938.385417     23176.615234    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41251944.479167         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41251950.781250         6.302083    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41254757.552083      2806.770752    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41254763.541667         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41254769.947917         6.406250    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41258588.854167      3818.906250    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41258594.947917         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41258601.250000         6.302083    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41262294.114583      3692.864502    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41262300.104167         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41262306.354167         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41265205.052083      2898.697998    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41265211.041667         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41265217.187500         6.145833    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41271421.093750      6203.906250    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41271427.083333         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41271433.333333         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41274323.125000      2889.791748    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41274329.218750         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41274335.625000         6.406250    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41277756.510417      3420.885498    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41277762.656250         6.145833 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41277768.906250         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41281070.260417      3301.354248    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41281076.354167         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41281082.604167         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41284299.166667      3216.562500    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41284305.156250         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41284311.562500         6.406250    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41290951.927083      6640.364746    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41290958.020833         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41290964.270833         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41294373.281250      3409.010498    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41294379.270833         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41294385.520833         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41297494.531250      3109.010498    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41297500.625000         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41297521.927083        21.302084    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41301066.406250      3544.479248    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41301072.395833         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41301078.645833         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41304709.791667      3631.145752    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41304715.885417         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41304722.343750         6.458333    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41311145.781250      6423.437500    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41311151.927083         6.145833 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41311158.229167         6.302083    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41314957.760417      3799.531250    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41314963.854167         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41314970.156250         6.302083    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41318451.041667      3480.885498    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41318457.031250         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41318463.489583         6.458333    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41322651.822917      4188.333496    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41322657.916667         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41322664.218750         6.302083    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41326243.125000      3578.906250    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41326249.114583         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41326255.416667         6.302083    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41332252.343750      5996.927246    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41332258.437500         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41332264.687500         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41335320.156250      3055.468750    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41335326.145833         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41335332.395833         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41338493.750000      3161.354248    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41338499.947917         6.197917 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41338521.718750        21.770834    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41341821.927083      3300.208252    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41341828.072917         6.145833 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41341834.322917         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41344665.000000      2830.677002    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41344670.989583         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41344677.187500         6.197917    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41350383.906250      5706.718750    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41350389.791667         5.885417 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41350396.093750         6.302083    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41353311.822917      2915.729248    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41353317.916667         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41353324.166667         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41357211.875000      3887.708252    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41357217.864583         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41357224.114583         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41360292.500000      3068.385498    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41360298.593750         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41360304.843750         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41363293.020833      2988.177002    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41363299.010417         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41363305.260417         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41369093.437500      5788.177246    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41369099.531250         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41369105.937500         6.406250    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41372402.604167      3296.666748    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41372408.750000         6.145833 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41372415.052083         6.302083    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41375498.906250      3083.854248    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41375505.000000         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41375526.875000        21.875000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41378318.229167      2791.354248    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41378324.218750         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41378330.677083         6.458333    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41380967.500000      2636.822998    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41380973.593750         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41380979.895833         6.302083    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41385771.614583      4791.718750    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41385777.604167         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41385783.854167         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41388457.135417      2673.281250    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41388463.229167         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41388469.479167         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41391124.479167      2655.000000    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41391130.468750         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41391136.770833         6.302083    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41393699.270833      2562.500000    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41393705.364583         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41393711.770833         6.406250    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41396312.916667      2601.145752    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41396319.010417         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41396325.260417         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41417780.833333     21455.572266    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41417786.927083         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41417793.177083         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41419905.781250      2112.604248    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41419911.770833         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41419918.177083         6.406250    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41422012.968750      2094.791748    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41422019.062500         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41422025.312500         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41424207.916667      2182.604248    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41424213.906250         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41424220.156250         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41426346.927083      2126.770752    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41426352.916667         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41426359.062500         6.145833    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41430298.958333      3939.895752    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41430304.843750         5.885417 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41430310.989583         6.145833    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41432443.958333      2132.968750    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41432449.947917         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41432456.302083         6.354167    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41434622.656250      2166.354248    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41434628.802083         6.145833 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41434635.104167         6.302083    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41436779.479167      2144.375000    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41436785.572917         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41436791.875000         6.302083    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41438887.604167      2095.729248    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41438893.593750         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41438900.052083         6.458333    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41442925.312500      4025.260498    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41442931.354167         6.041667 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41442937.656250         6.302083    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41445166.562500      2228.906250    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41445172.552083         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41445178.802083         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41447379.010417      2200.208252    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41447385.104167         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41447391.354167         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41449573.854167      2182.500000    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41449579.843750         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41449586.093750         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41451792.968750      2206.875000    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41451799.062500         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41451805.468750         6.406250    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41455963.437500      4157.968750    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41455969.531250         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41455975.781250         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41458258.281250      2282.500000    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41458264.375000         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41458270.625000         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41460467.291667      2196.666748    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41460473.281250         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41460479.687500         6.406250    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41462725.364583      2245.677002    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41462731.458333         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41462737.708333         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41464933.072917      2195.364502    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41464939.062500         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41464945.312500         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41468914.062500      3968.750000    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41468920.156250         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41468926.406250         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41471025.260417      2098.854248    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41471031.250000         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41471037.500000         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41473220.885417      2183.385498    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41473226.979167         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41473233.385417         6.406250    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41475344.427083      2111.041748    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41475350.572917         6.145833 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41475356.875000         6.302083    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41477446.770833      2089.895752    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41477452.760417         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41477458.958333         6.197917    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41481346.197917      3887.239502    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41481352.083333         5.885417 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41481358.437500         6.354167    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41483494.791667      2136.354248    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41483500.781250         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41483522.187500        21.406250    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41485651.458333      2129.270752    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41485657.343750         5.885417 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41485663.489583         6.145833    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41487779.166667      2115.677002    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41487785.156250         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41487791.302083         6.145833    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41489894.114583      2102.812500    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41489900.104167         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41489906.354167         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41493954.270833      4047.916748    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41493960.364583         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41493966.770833         6.406250    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41496230.260417      2263.489502    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41496236.354167         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41496242.604167         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41498453.072917      2210.468750    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41498459.166667         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41498465.416667         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41500665.156250      2199.739502    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41500671.145833         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41500677.552083         6.406250    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41502879.375000      2201.822998    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41502885.468750         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41502891.718750         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41507035.416667      4143.697754    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41507041.406250         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41507047.656250         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41509344.739583      2297.083252    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41509350.833333         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41509357.083333         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41511557.552083      2200.468750    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41511563.541667         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41511569.843750         6.302083    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41513782.239583      2212.395752    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41513788.333333         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41513794.791667         6.458333    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41515924.166667      2129.375000    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41515930.312500         6.145833 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41515936.666667         6.354167    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41536743.541667     20806.875000    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41536749.791667         6.250000 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41536756.093750         6.302083    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41538902.395833      2146.302002    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41538908.385417         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41538914.843750         6.458333    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41540936.093750      2021.250000    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41540942.187500         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41540948.593750         6.406250    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41543053.697917      2105.104248    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41543059.739583         6.041667 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41543066.093750         6.354167    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41545122.656250      2056.562500    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41545128.750000         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41545134.895833         6.145833    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41549044.635417      3909.739502    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41549050.625000         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41549056.770833         6.145833    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41551091.250000      2034.479126    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41551097.343750         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41551103.645833         6.302083    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41553195.208333      2091.562500    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41553201.302083         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41553207.500000         6.197917    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41555250.208333      2042.708374    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41555256.197917         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41555262.343750         6.145833    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41557438.593750      2176.250000    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41557444.479167         5.885417 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41557450.781250         6.302083    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41561757.812500      4307.031250    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41561763.906250         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41561770.156250         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41564052.395833      2282.239502    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41564058.385417         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41564064.687500         6.302083    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41566320.572917      2255.885498    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41566326.666667         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41566332.916667         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41568578.750000      2245.833252    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41568584.739583         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41568591.041667         6.302083    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41570900.052083      2309.010498    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41570906.145833         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41570912.604167         6.458333    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41575398.541667      4485.937500    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41575404.687500         6.145833 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41575410.989583         6.302083    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41577739.114583      2328.125000    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41577745.208333         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41577751.614583         6.406250    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41580106.510417      2354.895752    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41580112.500000         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41580118.958333         6.458333    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41582536.406250      2417.447998    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41582542.604167         6.197917 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41582548.906250         6.302083    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41584938.750000      2389.843750    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41584944.739583         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41584950.989583         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41589239.531250      4288.541504    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41589245.625000         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41589251.875000         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41591533.437500      2281.562500    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41591539.687500         6.250000 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41591545.937500         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41593799.739583      2253.802002    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41593805.729167         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41593812.135417         6.406250    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41596057.447917      2245.312500    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41596063.750000         6.302083 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41596070.000000         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41598341.458333      2271.458252    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41598347.343750         5.885417 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41598353.489583         6.145833    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41602705.260417      4351.770996    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41602711.250000         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41602717.552083         6.302083    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41605047.812500      2330.260498    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41605053.697917         5.885417 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41605059.895833         6.197917    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41607371.406250      2311.510498    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41607377.395833         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41607383.541667         6.145833    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41609702.447917      2318.906250    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41609708.333333         5.885417 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41609714.479167         6.145833    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41612311.822917      2597.343750    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41612317.812500         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41612323.958333         6.145833    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41617314.479167      4990.520996    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41617320.364583         5.885417 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41617326.718750         6.354167    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41619923.541667      2596.822998    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41619929.791667         6.250000 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41619936.197917         6.406250    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41622413.125000      2476.927002    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41622419.114583         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41622425.416667         6.302083    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41624850.208333      2424.791748    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41624856.302083         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41624862.760417         6.458333    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41627354.114583      2491.354248    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41627360.104167         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41627366.510417         6.406250    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41632521.718750      5155.208496    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41632528.281250         6.562500 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41632534.531250         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41635123.593750      2589.062500    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41635129.583333         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41635135.833333         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41637658.385417      2522.552002    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41637664.479167         6.093750 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41637670.729167         6.250000    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41640138.645833      2467.916748    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41640144.635417         5.989583 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
    0      1          IPC          41640151.041667         6.406250    src/ipc/handler.c:298 	ipc: pipe 1 comp 0 params failed -22
    0      1        MIXER 1.3      41642583.333333      2432.291748    src/audio/mixer.c:189 	mixer_params() error: period_bytes = 0
    0      1         PIPE          41642589.583333         6.250000 src/audio/pipeline.c:393 	pipeline_params() error: ret = -22, host->comp.id = 0
````
</details>

***Environment***
platform: APL UP2 with PCM512x in I2S mode
Firmware: feb9e2b2 https://github.com/thesofproject/sof/commits/master
Kernel: 0bdbe73a https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology file: tools/topology/sof-apl-pcm512x.tplg same as firmware

[dmesg20191202.log](https://github.com/thesofproject/sof/files/3909164/dmesg20191202.log)
[sof_errortrace.log](https://github.com/thesofproject/sof/files/3909165/sof_errortrace.log)
[sof_trace.log](https://github.com/thesofproject/sof/files/3909166/sof_trace.log)

### PR DESCRIPTION
**Pull request by bkokoszx**
Fetches params (for mux and demux) from sink buffer
(sink buffer params are set in pipeline_set_params() before
mixer/mux_params()). For mux and mixer components some
of source buffer can be unset yet in mixer/mux_params(). 

Fixes #2154 

Signed-off-by: Bartosz Kokoszko <bartoszx.kokoszko@linux.intel.com>

### CODE REVIEW

File: src/audio/mixer.c [hunk 1]
```diff
@@ -174,25 +174,21 @@ static int mixer_params(struct comp_dev *dev,
...
 	struct comp_buffer *sinkb;
-	struct comp_buffer *sourceb;
 	uint32_t period_bytes;
 
 	trace_mixer_with_ids(dev, "mixer_params()");
 
-	sourceb = list_first_item(&dev->bsource_list, struct comp_buffer,
-				  sink_list);
+	sinkb = list_first_item(&dev->bsink_list, struct comp_buffer,
+							source_list);
```
Comment (ranj063) [inline src/audio/mixer.c]: @bkokoszx just wondering if this should be based on the stream direction instead of always using the sink buffer?

File: src/audio/mixer.c [hunk 2]
```diff
@@ -174,25 +174,21 @@ static int mixer_params(struct comp_dev *dev,
 {
 	struct sof_ipc_comp_config *config = COMP_GET_CONFIG(dev);
 	struct comp_buffer *sinkb;
-	struct comp_buffer *sourceb;
 	uint32_t period_bytes;
 
 	trace_mixer_with_ids(dev, "mixer_params()");
 
-	sourceb = list_first_item(&dev->bsource_list, struct comp_buffer,
```
Comment (xiulipan) [inline src/audio/mixer.c]: @bkokoszx 
I checked with the SRC pipeline with mixer
If I start SRC PCM, the SRC pipeline with mixer can work.
If I start SRC PCM first then the normal PCM, both of them can work.
As mixer will have multiple source, and now the buffer size is set up during HW param, maybe you should try to have some logic to find the active souce instead of use the single sink instead.

PS: You may also need to check the mux and de-mux comp.

Comment (bkokoszx) [reply src/audio/mixer.c]: @xiulipan
I'm not sure whether we need ATM to add logic and search for "active" source since sources and sinks would have same frame_fmt (in my opinion for mixer sink buffer is sufficient). This could be refined during #1280.

I will take a look at mux and demux.

File: src/audio/mixer.c (hunk 1 above)
Comment (bkokoszx) [reply src/audio/mixer.c]: @ranj063 
At the moment I think we should use sink buffer for mixer, because it has one sink (some of source buffers can be unset and as a result ```period_bytes``` can be set to 0 causing errors).

**Comment by plbossart** [comment]
Quickbuild seems to be in the weeds, 4 hours to compile stuff doesn't look quite right
We need to merge this asap to unblock other pending PRs

**Comment by wenqingfu** [comment]
Agree. It's good to go. the bsw failure on kernel module load/unload is another known issue.

**Comment by plbossart** [comment]
I will use my superpowers to unblock CI tests
