### PR TITLE
icl: memory: increase heap buffer size

### LINKED ISSUE #2560: [BUG][JSL][KD] DSP panic happens when running KD pipleline
**Describe the bug**
Run KD pipeline with arecord returns:

[  223.798829] sof-audio-pci 0000:00:1f.3: error: no reply expected, received 0x0
[  223.912254] sof-audio-pci 0000:00:1f.3: firmware boot complete
[  223.952422] sof-audio-pci 0000:00:1f.3: error : DSP panic!
[  223.957961] sof-audio-pci 0000:00:1f.3: status: fw entered - code 00000005
[  223.964977] sof-audio-pci 0000:00:1f.3: error: runtime exception
[  223.971032] sof-audio-pci 0000:00:1f.3: error: trace point 00004000
[  223.977351] sof-audio-pci 0000:00:1f.3: error: panic at :0
[  223.982886] sof-audio-pci 0000:00:1f.3: error: DSP Firmware Oops

**To Reproduce**
arecord -Dhw:0,8 -M -N -c 2 -f S24_LE -r 16000 --buffer-size=68000 /tmp/tmp.wav -vvv -d 5

**Reproduction Rate**
All the time.

**Environment**
DSP FW uses SOF v0.1 release.

Topology is built with the following patch on top of jsl-001-drop-stable
https://github.com/thesofproject/sof/pull/2490

### PR DESCRIPTION
**Pull request by tlauda**
Increases heap buffer size on ICL platform to have
sufficient space for KPB allocation.

Signed-off-by: Tomasz Lauda <tomasz.lauda@linux.intel.com>

### CODE REVIEW

File: src/audio/kpb.c [hunk 1]
```diff
@@ -315,7 +315,7 @@ static void kpb_free_history_buffer(struct hb *buff)
 		_buff = buff->next;
 		rfree(buff);
 		buff = _buff;
-	} while (buff != first_buff);
+	} while (buff && buff != first_buff);
```
Comment (paulstelian97) [inline src/audio/kpb.c]: This is unrelated to the heap buffer increase I think, so it should be a separate commit (if it's even needed)

Comment (tlauda) [reply src/audio/kpb.c]: @paulstelian97 It is a separate commit. And it's needed to not get panic in case buffer is too small.

Comment (paulstelian97) [reply src/audio/kpb.c]: For some reason it didn't show up as separate for me when I reviewed?

Comment (mrajwa) [reply src/audio/kpb.c]: @tlauda, but the history buffer allocator guarantees 'buff->next' is never NULL so the problem you are trying to fix should theoretically never happen, does it?

Comment (tlauda) [reply src/audio/kpb.c]: @mrajwa But it happens. Just don't increase the heap size on JSL.

Comment (lgirdwood) [reply src/audio/kpb.c]: @tlauda  Why JSL ?

Comment (tlauda) [reply src/audio/kpb.c]: @lgirdwood I bet it's generic issue for every platform. I've mentioned JSL, because it's the only platform currently having too less memory to allocate the history buffer. I guess @mrajwa is right and there is another bug in kpb allocation buffer procedure, which leaves one of the items in the linked list NULL. Nevertheless this fix is also needed to make sure we're going to always gracefully recover.

**Comment by tlauda** [comment]
SOFCI TEST

File: src/audio/kpb.c (hunk 1 above)
Comment (lgirdwood) [reply src/audio/kpb.c]: Is this something we can pick up with cmocka UT testing ?

Comment (mrajwa) [reply src/audio/kpb.c]: @lgirdwood, well it only happens when memory allocation fails and we don't have a UT which mimics such case.
@lgirdwood, I know the root cause of it, PR is comming soon.

**Comment by lgirdwood** [comment]
@tlauda jenkins has known errors, just the UT failure.

**Comment by lgirdwood** [comment]
SOFCI TEST
