### PR TITLE
spinlock: improvements and fixes

### LINKED ISSUE #1687: [BUG] -62 IPC ERROR on StreamTrigPause for Multikernel pipelines
**Description**
Topology:
Topology composed of one playback pipeline (on core 0) and one capture pipeline (on core 1). 

Test case:
Stress test is creating streams for both pipelines, plays and captures wave file, gracefully stops streams and free them. Whole process repeats 100 times.

Bug:
When sending Ipc StreamTrigPause to capture stream FW responds with IPC error -62.

**To Reproduce**
Run python test TestPtpSimpleLoopbackMultiKernelCore8000Hz24b32b4ch with 100 playback-iterations.

**Reproduction Rate**
~1%

**Environment**
1) Branch: Master
2) Commit: 0ec0ff73bd2e5438060f6321da95d51170c47da1

**Test logs**
ICL FW trace log
[ICL_dma_trace_1.log](https://github.com/thesofproject/sof/files/3447263/ICL_dma_trace_1.log)

WHL FW trace log
[WHL_dma_trace_1.log](https://github.com/thesofproject/sof/files/3447264/WHL_dma_trace_1.log)

### PR DESCRIPTION
**Pull request by tlauda**
Various improvements and fixes to the spinlock.

Fixes #1687.

### CODE REVIEW

File: src/include/sof/drivers/interrupt.h [hunk 1]
```diff
@@ -163,4 +163,12 @@ static inline void interrupt_global_enable(uint32_t flags)
 	arch_interrupt_global_enable(flags);
 }
 
+/* disables all IRQ sources on current core */
+#define local_irq_save(flags) \
```
Comment (jajanusz) [inline src/include/sof/drivers/interrupt.h]: why not `static inline`?

**Comment by tlauda** [comment]
@xiulipan Could you check what is the last logged trace point for BYT and HSW platforms?

File: src/include/sof/drivers/interrupt.h (hunk 1 above)
Comment (tlauda) [reply src/include/sof/drivers/interrupt.h]: I would need to assign flags everywhere then.

File: src/init/init.c [hunk 2]
```diff
@@ -43,6 +41,8 @@ int master_core_init(struct sof *sof)
 	platform_init_memmap();
 	init_heap(sof);
 
+	interrupt_init();
```
Comment (jajanusz) [inline src/init/init.c]: I think this one would be better as separate commit. It's not spinlock fix

**Comment by xiulipan** [comment]
@tlauda 
I fixed the issue that failed case had no log.
BYT:
https://sof-ci.01.org/sofpr/PR1703/build2735/boottest/dump-byt.txt

```
shim.io: write 0x40 = 	0x0dead006 (old 0x0) 	(233492486) 	|....|
shim.io: write 0x44 = 	0x80000800 (old 0x0) 	(2147485696) 	|....|
irq: send busy interrupt 0x80000800
bridge-io: msg send: 0 type 2 msg 64 size 16 ret 0
```
It seems to be a panic happen here.

HSW:
https://sof-ci.01.org/sofpr/PR1703/build2735/boottest/dump-hsw.txt

File: src/init/init.c (hunk 2 above)
Comment (tlauda) [reply src/init/init.c]: Done.

Comment (jajanusz) [reply src/init/init.c]: thanks

File: src/include/sof/drivers/interrupt.h (hunk 1 above)
Comment (lgirdwood) [inline src/include/sof/drivers/interrupt.h]: This should probably be prefixed with irq_ since these are IRQ APIs e.g irq_local_save()

File: src/arch/xtensa/lib/cpu.c [hunk 3]
```diff
@@ -33,15 +32,14 @@ extern struct xtos_core_data *core_data_ptr[PLATFORM_CORE_COUNT];
...
-static spinlock_t lock = { 0 };
 
 void arch_cpu_enable_core(int id)
 {
 	struct idc_msg power_up = {
 		IDC_MSG_POWER_UP, IDC_MSG_POWER_UP_EXT, id };
 	uint32_t flags;
 
-	spin_lock_irq(&lock, flags);
+	local_irq_save(flags);
```
Comment (lgirdwood) [inline src/arch/xtensa/lib/cpu.c]: infact it maybe makes more sense to rename to irq_local_disable(flags) and irq_local_enable(flags)

**Comment by tlauda** [comment]
@lgirdwood Updated.

**Comment by tlauda** [comment]
SOFCI TEST

**Comment by tlauda** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
@tlauda Jenkins CI showing invalid failure, but cant merge as internal CI showing valid test failures ?

**Comment by keqiaozhang** [comment]
> Some small naming changes needed to help readability but otherwise good.
> @mengdonglin @keqiaozhang can you give this a test on Legacy.

@Jiangxinx  Could you help on this?
