### PR TITLE
Ssp rx flush

### LINKED ISSUE #3525: [BUG][WHL][SSP] Channel swapped with trigger pause/stop/start on capture pipline.
**Describe the bug**
When running simultaneous playback and capture on external loopback (same SSP) with pause, stop and start operation are done on capture stream there are swapped channel after trigger start on captured wave file.

This commit: 242be345ca9f87db29b9cb4b12b91438d932814d fixed swapped channels with pause, stop and start operation on capture stream with dsm component on TGL platform, but problem is still occurs specially on Frame formats where: 
SAMPLE_SIZE=24 bits
CONTAINER_SIZE = 32 bits.

WHL results:
image

Example wave:
image

**Topology**
```
                pipe_plb
                +--------------------+
+----------+    | +------+   +-----+ |   +----+
| Host plb |----->|Buffer|-->| Dai |---->|SSPx|
+----------+    | +------+   +-----+ |   +----+
                +--------------------+    |  |
                pipe_cap                  |  |
                +--------------------+    |  |
+----------+    | +------+   +-----+ |   +----+
| Host cap |<-----|Buffer|<--| Dai |---->|SSPx|
+----------+    | +------+   +-----+ |   +----+
                +--------------------+
```
**To Reproduce**
Slim Driver python test:
test_20_ptp_cap_stream_stop_start_operations.py with --playback_iterations>=10

**Reproduction Rate**
On with Frame format 24/32 - 80%
On other Frame formats - 20%

**Expected behavior**
Channels shouldn't be swapped on recorded files.

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Environment**
I checked it on WHL platform.
SOF master, commit: 8a5059a8c0b1e2d67b404efe26e1b79bb6175b5b

**Example logs**
For WHL:
[02_20_TestPtpCaptureStreamStopStartOperation48000Hz32b32b4ch.zip](https://github.com/thesofproject/sof/files/5383876/02_20_TestPtpCaptureStreamStopStartOperation48000Hz32b32b4ch.zip)

### PR DESCRIPTION
**Pull request by keyonjie**
ssp: refine the RX FIFO flushing logic
    
    The SSSR_BSY is not necessary for flushing, we need to read out entries
    every time the FIFO is not empty. This flushing may need take place
    several rounds, and we need to wait 1 sample time between 2 flushing
    rounds.
    
    Fixes #3525
    
    Signed-off-by: Keyon Jie <yang.jie@linux.intel.com>

### CODE REVIEW

**Comment by keyonjie** [comment]
SOFCI TEST

**Comment by jdrzaszcz** [comment]
Looks like this PR fix this issue: https://github.com/thesofproject/sof/issues/3525 on external loopack.
I ran tests with trigger pause/stop/start on capture pipeline (100 playback iteration for audio format) on WHL RVP with external loopback and there was no swapped channels.

**Comment by keyonjie** [comment]
SOFCI TEST

**Comment by keyonjie** [comment]
> Looks like this PR fix this issue: #3525 on external loopack.
> I ran tests with trigger pause/stop/start on capture pipeline (100 playback iteration for audio format) on WHL RVP with external loopback and there was no swapped channels.

Thank you so much @jdrzaszcz !

Hi @lgirdwood good news that we finally got the external normal SSP capture channel swap issue fixed with this PR, please help to review, we could add similar fixes for BYT next.

**Comment by jdrzaszcz** [comment]
@keyonjie I have a TGL RVP with external loopback on SSP.
I'm running tests with pause/stop/start on capture pipeline and on this platform channels are still swapped.

This is some example log with: dai_info on "ssp_empty_rx_fifo(), before flushing, entries %d"

[dma_trace_1.log](https://github.com/thesofproject/sof/files/5439005/dma_trace_1.log)

**Comment by keyonjie** [comment]
> @keyonjie I have a TGL RVP with external loopback on SSP.
> I'm running tests with pause/stop/start on capture pipeline and on this platform channels are still swapped.
> 
> This is some example log with: dai_info on "ssp_empty_rx_fifo(), before flushing, entries %d"
> 
> [dma_trace_1.log](https://github.com/thesofproject/sof/files/5439005/dma_trace_1.log)

Interesting, so looks there is difference between WHL and TGL, let me debug it more.

File: src/include/sof/lib/clk.h [hunk 1]
```diff
@@ -57,6 +57,8 @@ void clock_low_power_mode(int clock, bool enable);
 
 uint64_t clock_ms_to_ticks(int clock, uint64_t ms);
 
+uint64_t clock_sample_ticks(int clock, uint32_t sample_rate);
```
Comment (lgirdwood) [inline src/include/sof/lib/clk.h:60]: clock_ticks_per_sample(clock, rate);

File: src/lib/clk.c [hunk 2]
```diff
@@ -115,6 +115,19 @@ uint64_t clock_ms_to_ticks(int clock, uint64_t ms)
 	return ticks;
 }
 
+uint64_t clock_sample_ticks(int clock, uint32_t sample_rate)
```
Comment (lgirdwood) [inline src/lib/clk.c:118]: inline comments here explaining usage. I'm assuming we get number of ticks per sample ?

File: src/include/sof/drivers/ssp.h [hunk 3]
```diff
@@ -221,7 +221,7 @@ extern const struct dai_driver ssp_driver;
 #define SSP_MAX_SEND_TIME_PER_SAMPLE 125
 
 /* SSP flush timeout in microseconds */
-#define SSP_RX_FLUSH_TIMEOUT	200
+#define SSP_RX_FLUSH_TIMEOUT	500
```
Comment (lgirdwood) [inline src/include/sof/drivers/ssp.h:224]: Aren't we using rate here ?

**Review by lgirdwood — CHANGES_REQUESTED** [review]

File: src/lib/clk.c (hunk 2 above)
Comment (keyonjie) [reply src/lib/clk.c:118]: yep, let me add inline comments.

File: src/include/sof/lib/clk.h (hunk 1 above)
Comment (keyonjie) [reply src/include/sof/lib/clk.h:60]: > clock_ticks_per_sample(clock, rate);

good, let me change.

File: src/include/sof/drivers/ssp.h (hunk 3 above)
Comment (keyonjie) [reply src/include/sof/drivers/ssp.h:224]: > Aren't we using rate here ?

I wanted to use it as the total timeout control, now I change my mind to use something like this:
```
#define  SSP_RX_FLUSH_SAMPLE_MAX 16
```

Will update it in the PR.

**Comment by keyonjie** [comment]
@lgirdwood FYI that this is to fix normal SSP capture channel swap issue on cAVS (< 2.5) platforms, for cAVS 2.5+, the solution is still open as there is some IP design change and known limitation there. So let's get this merged first before jumping to the TGL issues.

**Comment by keyonjie** [comment]
SOFCI TEST

File: src/lib/clk.c [hunk 4]
```diff
@@ -115,6 +115,19 @@ uint64_t clock_ms_to_ticks(int clock, uint64_t ms)
 	return ticks;
 }
 
+uint64_t clock_ticks_per_sample(int clock, uint32_t sample_rate)
+{
+	struct clock_info *clk_info = clocks_get() + clock;
+	uint32_t ticks_per_msec =
+		clk_info->freqs[clk_info->current_freq_idx].ticks_per_msec;
+	uint64_t ticks_per_sample = ticks_per_msec * 1000 /
```
Comment (lgirdwood) [inline src/lib/clk.c:123]: sample_rate is mandatory here. If it's not passed in then return 0

**Review by lgirdwood — CHANGES_REQUESTED** [review]

File: src/lib/clk.c (hunk 4 above)
Comment (keyonjie) [reply src/lib/clk.c:123]: > sample_rate is mandatory here. If it's not passed in then return 0

Fair, let me change.

File: src/lib/clk.c [hunk 5]
```diff
@@ -115,6 +115,18 @@ uint64_t clock_ms_to_ticks(int clock, uint64_t ms)
...
 }
 
+uint64_t clock_ticks_per_sample(int clock, uint32_t sample_rate)
+{
+	struct clock_info *clk_info = clocks_get() + clock;
+	uint32_t ticks_per_msec =
+		clk_info->freqs[clk_info->current_freq_idx].ticks_per_msec;
+	uint64_t ticks_per_sample = sample_rate ? ticks_per_msec * 1000 / sample_rate : 0;
+
+	platform_shared_commit(clk_info, sizeof(*clk_info));
```
Comment (lgirdwood) [inline src/lib/clk.c:125]: Btw, why are you committing this ? You are not changing anything in clk. I would have expected to invalidate this before we calculate the ticks ?

Comment (keyonjie) [reply src/lib/clk.c:125]: > Btw, why are you committing this ? You are not changing anything in clk. I would have expected to invalidate this before we calculate the ticks ?

Indeed, platform_shared_get() should be used to invalidate the clk_info. It was copy-paste from clock_ms_to_ticks(), let me correct it.

**Review by lgirdwood — APPROVED** [review]
