### PR TITLE
task: increase default stack size for EDF tasks

### LINKED ISSUE #2921: [BUG][APL-nocodec]"error: ipc timed out for 0x80010000 size 216" when do check-kmod-load-unload-after-playback.sh test
**Describe the bug**
"error: ipc timed out for 0x80010000 size 216" when do check-kmod-load-unload-after-playback.sh test
After error occured,all the pipeline can not  work,reboot can recovery

**To Reproduce**
1.sudo reboot
2.cd sof-test
3.cd test-case
4.export TPLG=/lib/firmware/intel/sof-tplg/sof-apl-nocodec.tplg
5../check-kmod-load-unload-after-playback.sh -l 50

**Reproduction Rate**
Round 1: failed at 15/50
Round 2:pass 50/50
Round 3:failed at 33/50

**Expected behavior**
There is o error occured when do check-kmod-load-unload-after-playback.sh test

**Impact**

1."Unable to install hw params" when aplay(0,0),dmesg show "error: ipc timed out for 0x80010000 size 216"

```
ubuntu@sh-apl-up2-nocodec-04:~$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: sofnocodec [sof-nocodec], device 0: Port0 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofnocodec [sof-nocodec], device 1: Port1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofnocodec [sof-nocodec], device 3: Port3 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofnocodec [sof-nocodec], device 5: Port5 (*) []
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 0: sofnocodec [sof-nocodec], device 7: Media Playback 7 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

```

<details>
 <summary>dmesg_error.log</summary>

````
[ 2957.018542] sof-audio-pci 0000:00:0e.0: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[ 2957.018717] sof-audio-pci 0000:00:0e.0: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[ 2957.018729] sof-audio-pci 0000:00:0e.0: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[ 2957.525432] sof-audio-pci 0000:00:0e.0: error: ipc timed out for 0x80010000 size 216
[ 2957.525457] sof-audio-pci 0000:00:0e.0: info: preventing DSP entering D3 state to preserve context
[ 2957.525465] sof-audio-pci 0000:00:0e.0: status: fw entered - code 00000005
[ 2957.525509] sof-audio-pci 0000:00:0e.0: error: unexpected fault 0x00000000 trace 0x00004000
[ 2957.525518] sof-audio-pci 0000:00:0e.0: error: hda irq intsts 0x00000000 intlctl 0xc0000001 rirb 00
[ 2957.525521] sof-audio-pci 0000:00:0e.0: error: dsp irq ppsts 0x00000000 adspis 0x00000000
[ 2957.525527] sof-audio-pci 0000:00:0e.0: error: host status 0x00000000 dsp status 0x00000000 mask 0x00000003
[ 2957.525531] sof-audio-pci 0000:00:0e.0: error: waking up any trace sleepers
[ 2957.525542] sof-audio-pci 0000:00:0e.0: error: failed to set dai config for NoCodec-5
[ 2957.525546] sof-audio-pci 0000:00:0e.0: error: failed to restore pipeline after resume -110
[ 2957.525584] sof-audio-pci 0000:00:0e.0: pcm: open stream 0 dir 0
[ 2957.525588] sof-audio-pci 0000:00:0e.0: period min 192 max 16384 bytes
[ 2957.525591] sof-audio-pci 0000:00:0e.0: period count 2 max 16
[ 2957.525594] sof-audio-pci 0000:00:0e.0: buffer max 65536 bytes
[ 2957.525696] sof-audio-pci 0000:00:0e.0: error: trace IO error
[ 2957.525975] sof-audio-pci 0000:00:0e.0: rate_min: 48000 rate_max: 48000
[ 2957.525979] sof-audio-pci 0000:00:0e.0: channels_min: 2 channels_max: 2
[ 2957.525985] sof-audio-pci 0000:00:0e.0: rate_min: 48000 rate_max: 48000
[ 2957.525988] sof-audio-pci 0000:00:0e.0: channels_min: 2 channels_max: 2
[ 2957.525992] sof-audio-pci 0000:00:0e.0: rate_min: 48000 rate_max: 48000
[ 2957.525995] sof-audio-pci 0000:00:0e.0: channels_min: 2 channels_max: 2
[ 2957.526003] sof-audio-pci 0000:00:0e.0: pcm: hw params stream 0 dir 0
[ 2957.526009] sof-audio-pci 0000:00:0e.0: generating page table for 00000000713a9ddc size 0xffc0 pages 16
[ 2957.526018] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x40000 successful
[ 2957.526035] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x40000 successful
````
</details>

No sof error trace

**Environment**
Platform: APL UP2 with nocodec
Firmware: 782066e0 https://github.com/thesofproject/sof/commits/master
Kernel: d43dc16c https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology file: sof-apl-nocodec.tplg same as firmware

[dmesg0509.log](https://github.com/thesofproject/sof/files/4602971/dmesg0509.log)
[sof-logger0409.log](https://github.com/thesofproject/sof/files/4602972/sof-logger0409.log)

### PR DESCRIPTION
**Pull request by tlauda**
Increases default stack size for EDF tasks. Some of the
IPC operations are very stack heavy, so let's make sure
they won't exceed stack.

Signed-off-by: Tomasz Lauda <tomasz.lauda@linux.intel.com>

Fixes #2921 & #2693.

### CODE REVIEW

File: src/platform/intel/cavs/include/cavs/lib/memory.h [hunk 1]
```diff
@@ -65,7 +65,7 @@
 #define HEAP_BUF_ALIGNMENT		PLATFORM_DCACHE_ALIGN
 
 /** \brief EDF task's default stack size in bytes. */
-#define PLATFORM_TASK_DEFAULT_STACK_SIZE	3072
+#define PLATFORM_TASK_DEFAULT_STACK_SIZE	0x1000
```
Comment (dbaluta) [inline src/platform/intel/cavs/include/cavs/lib/memory.h:68]: Agree with this change. Would be real nice to have some actual data and a stack trace to demonstrate this.
